
#if (defined VSTDLIB_START_SEC_CONST_UNSPECIFIED)
  #undef VSTDLIB_START_SEC_CONST_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined VSTDLIB_STOP_SEC_CONST_UNSPECIFIED)
  #undef VSTDLIB_STOP_SEC_CONST_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined VSTDLIB_START_SEC_VAR_NOINIT_UNSPECIFIED)
  #undef VSTDLIB_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined VSTDLIB_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
  #undef VSTDLIB_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined VSTDLIB_START_SEC_CODE)
  #undef VSTDLIB_START_SEC_CODE
  #undef MEMMAP_ERROR

#elif (defined VSTDLIB_STOP_SEC_CODE)
  #undef VSTDLIB_STOP_SEC_CODE
  #undef MEMMAP_ERROR

#elif (defined FRIF_START_SEC_CONST_UNSPECIFIED)
  #undef FRIF_START_SEC_CONST_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined PDUR_START_SEC_CONST_UNSPECIFIED)
  #undef PDUR_START_SEC_CONST_UNSPECIFIED
  #undef MEMMAP_ERROR

/* Memory section macros for FiM */

#elif (defined FIM_START_SEC_CALIB_UNSPECIFIED)
  #undef FIM_START_SEC_CALIB_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined FIM_STOP_SEC_CALIB_UNSPECIFIED)
  #undef FIM_STOP_SEC_CALIB_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined FIM_START_SEC_VAR_NOINIT_UNSPECIFIED)
  #undef FIM_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined FIM_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
  #undef FIM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef MEMMAP_ERROR
  
/* Memory section macros for Xlock */

#elif (defined XLOCK_START_SEC_VAR_NO_INIT_8)
  #undef XLOCK_START_SEC_VAR_NO_INIT_8
  #undef MEMMAP_ERROR

#elif (defined XLOCK_STOP_SEC_VAR_NO_INIT_8)
  #undef XLOCK_STOP_SEC_VAR_NO_INIT_8
  #undef MEMMAP_ERROR

#elif (defined XLOCK_START_SEC_CODE)
  #undef XLOCK_START_SEC_CODE
  #undef MEMMAP_ERROR

#elif (defined XLOCK_STOP_SEC_CODE)
  #undef XLOCK_STOP_SEC_CODE
  #undef MEMMAP_ERROR
  
#elif (defined RTE_START_SEC_XLOCK_FUNCTIONLOCKING_APPL_CODE)
  #undef RTE_START_SEC_XLOCK_FUNCTIONLOCKING_APPL_CODE
  #undef MEMMAP_ERROR

#elif (defined RTE_STOP_SEC_XLOCK_FUNCTIONLOCKING_APPL_CODE)
  #undef RTE_STOP_SEC_XLOCK_FUNCTIONLOCKING_APPL_CODE
  #undef MEMMAP_ERROR
  
#elif (defined RTE_START_SEC_XLOCK_ERRORREPORTING_APPL_CODE)
  #undef RTE_START_SEC_XLOCK_ERRORREPORTING_APPL_CODE
  #undef MEMMAP_ERROR

#elif (defined RTE_STOP_SEC_XLOCK_ERRORREPORTING_APPL_CODE)
  #undef RTE_STOP_SEC_XLOCK_ERRORREPORTING_APPL_CODE
  #undef MEMMAP_ERROR
  
/* Memory section macros for E2E and E2EPW */

#elif (defined E2E_START_SEC_CODE_LIB)
  #undef E2E_START_SEC_CODE_LIB
  #undef MEMMAP_ERROR

#elif (defined E2E_STOP_SEC_CODE_LIB)
  #undef E2E_STOP_SEC_CODE_LIB
  #undef MEMMAP_ERROR

#elif (defined E2E_START_SEC_CONST_8BIT)
  #undef E2E_START_SEC_CONST_8BIT
  #undef MEMMAP_ERROR

#elif (defined E2E_STOP_SEC_CONST_8BIT)
  #undef E2E_STOP_SEC_CONST_8BIT
  #undef MEMMAP_ERROR

#elif (defined E2EPW_START_SEC_CODE_LIB)
  #undef E2EPW_START_SEC_CODE_LIB
  #undef MEMMAP_ERROR

#elif (defined E2EPW_STOP_SEC_CODE_LIB)
  #undef E2EPW_STOP_SEC_CODE_LIB
  #undef MEMMAP_ERROR

#endif
