
/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains an Rte component template / example code
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Fri Feb 09 11:09:50 CET 2018. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#include "Rte_ComM.h"

/*------------------------[runnable entity skeletons]------------------------*/

void ComM_MainFunction_0 (void)
{
  Std_ReturnType status;

}

void ComM_MainFunction_1 (void)
{
  Std_ReturnType status;

}

Std_ReturnType ComM_RequestComMode (ComM_UserHandleType pdav0, ComM_ModeType ComMode)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType ComM_GetCurrentComMode (ComM_UserHandleType pdav0, P2VAR(ComM_ModeType, AUTOMATIC, RTE_APPL_DATA) ComMode)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType ComM_GetMaxComMode (ComM_UserHandleType pdav0, P2VAR(ComM_ModeType, AUTOMATIC, RTE_APPL_DATA) ComMode)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType ComM_GetRequestedComMode (ComM_UserHandleType pdav0, P2VAR(ComM_ModeType, AUTOMATIC, RTE_APPL_DATA) ComMode)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType ComM_LimitECUToNoComMode (Boolean Status)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType ComM_ReadInhibitCounter (P2VAR(UInt16, AUTOMATIC, RTE_APPL_DATA) CounterValue)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType ComM_ResetInhibitCounter (void)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType ComM_SetECUGroupClassification (ComM_InhibitionStatusType Status)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType ComM_ServiceLimitChannelToNoComMode (ComM_NetworkHandleType pdav0, Boolean Status)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType ComM_GetInhibitionStatus (ComM_NetworkHandleType pdav0, P2VAR(ComM_InhibitionStatusType, AUTOMATIC, RTE_APPL_DATA) Status)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType ComM_ServicePreventWakeUp (ComM_NetworkHandleType pdav0, Boolean Status)
{
  Std_ReturnType status;

  return status;
}

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------

  ------------------------[per instance memory API]--------------------------

*/
/** @} doxygen end group definition */
/*==================[end of file]============================================*/

