
/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains an Rte component template / example code
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Thu Mar 15 14:42:40 CET 2018. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#include "Rte_FLSMGR.h"

/*------------------------[runnable entity skeletons]------------------------*/

void FLSMGR_reFlsMgrMain (void)
{
  uint32 srcBuffAddrU32;
  uint32 sizeU32_1;
  uint32 addrU32_0;
  uint32 destBuffAddrU32;
  uint32 sizeU32_0;
  uint32 addresU32;
  uint32 sizeU32;
  uint32 addrU32;
  GenericByte SCI_SSM_ActStateWsValue;
  boolean FlsPrecondOK;
  Std_ReturnType status;

  Rte_IrvWrite_reFlsMgrMain_FlsPrecondOK(FlsPrecondOK);

  SCI_SSM_ActStateWsValue = Rte_IRead_reFlsMgrMain_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue();

  status = Rte_Call_WspExtFlsCdd_stService_FlsErase(addrU32, sizeU32);

  status = Rte_Call_WspExtFlsCdd_stService_FlsRead(addresU32, sizeU32_0, destBuffAddrU32);

  status = Rte_Call_WspExtFlsCdd_stService_FlsWrite(addrU32_0, sizeU32_1, srcBuffAddrU32);

}

void FLSMGR_reNotificationCallback (uint8 statusU8)
{
  Std_ReturnType status;

}

void FLSMGR_GetPrecondState (P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) PrecondOk)
{
  boolean FlsPrecondOK;
  Std_ReturnType status;

  FlsPrecondOK = Rte_IrvRead_GetPrecondState_FlsPrecondOK();

}

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------

  ------------------------[per instance memory API]--------------------------

*/
/** @} doxygen end group definition */
/*==================[end of file]============================================*/

