
/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains an Rte component template / example code
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Thu May 17 10:44:09 CEST 2018. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#include "Rte_IComSrv.h"

/*------------------------[runnable entity skeletons]------------------------*/

void IComSrv_MainFunction (void)
{
  Std_ReturnType status;

}

void IComSrv_CollectFrame (P2VAR(GenericByte, AUTOMATIC, RTE_APPL_DATA) FrameData, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) FrameLength)
{
  uint8 FrameLength;
  GenericByte FrameData;
  Std_ReturnType status;

  status = Rte_Call_IComDiag_fncDiagFrameHandling_CollectFrame(&FrameData, &FrameLength);

}

void IComSrv_ReceivedFrame (ByteDataPtr FrameData, uint8 FrameLength)
{
  uint8 FrameLength;
  ByteDataPtr FrameData;
  Std_ReturnType status;

  status = Rte_Call_IComDiag_fncDiagFrameHandling_ReceiveFrame(FrameData, FrameLength);

}

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------

  ------------------------[per instance memory API]--------------------------

*/
/** @} doxygen end group definition */
/*==================[end of file]============================================*/

