
/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains an Rte component template / example code
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Fri May 18 15:49:47 CEST 2018. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#include "Rte_SCI_DiagMeas.h"

/*------------------------[runnable entity skeletons]------------------------*/

Std_ReturnType DiagMeas_DcmDspDid_5346_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_5346_ReadData (P2VAR(Dcm_Data0x5346_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_5346_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_534a_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_534a_ReadData (P2VAR(Dcm_Data0x534A_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_534a_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_536e_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_536e_ReadData (P2VAR(Dcm_Data0x536E_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_536e_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_100_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_100_ReadData (P2VAR(Dcm_Data0x0100_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_100_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f199_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_f199_ReadData (P2VAR(Dcm_Data0xF199_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_f199_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f198_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_f198_ReadData (P2VAR(Dcm_Data0xF198_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_f198_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f186_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_f186_ReadData (P2VAR(Dcm_Data0xF186_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_f186_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f194_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_f194_ReadData (P2VAR(Dcm_Data0xF194_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_f194_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f195_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_f195_ReadData (P2VAR(Dcm_Data0xF195_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_f195_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f195_ReadDataLength (P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) DidLength)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f1ab_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_f1ab_ReadData (P2VAR(Dcm_Data0xF1AB_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_f1ab_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f1ab_ReadDataLength (P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) DidLength)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_407_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_407_ReadData (P2VAR(Dcm_Data0x0407_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_407_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_407_ReadDataLength (P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) DidLength)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_40f_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_40f_ReadData (P2VAR(Dcm_Data0x040F_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_40f_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_40f_ReadDataLength (P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) DidLength)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f15b_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_f15b_ReadData (P2VAR(Dcm_Data0xF15B_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_f15b_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f15b_ReadDataLength (P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) DidLength)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_SecurityAccess_0x03_GetSeed (P2VAR(Dcm_SecSeed0x03_ArrayType, AUTOMATIC, RTE_APPL_DATA) Seed, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#else
Std_ReturnType DiagMeas_SecurityAccess_0x03_GetSeed (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Seed, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#endif
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_SecurityAccess_0x03_CompareKey (P2CONST(Dcm_SecKey0x03_ArrayType, AUTOMATIC, RTE_APPL_CONST) Key)
#else
Std_ReturnType DiagMeas_SecurityAccess_0x03_CompareKey (P2CONST(uint8, AUTOMATIC, RTE_APPL_CONST) Key)
#endif
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_SecurityAccess_0x00_GetSeed (P2VAR(Dcm_SecSeed0x00_ArrayType, AUTOMATIC, RTE_APPL_DATA) Seed, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#else
Std_ReturnType DiagMeas_SecurityAccess_0x00_GetSeed (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Seed, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#endif
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_SecurityAccess_0x00_CompareKey (P2CONST(Dcm_SecKey0x00_ArrayType, AUTOMATIC, RTE_APPL_CONST) Key)
#else
Std_ReturnType DiagMeas_SecurityAccess_0x00_CompareKey (P2CONST(uint8, AUTOMATIC, RTE_APPL_CONST) Key)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_ResetService_EcuReset (uint8 resetType, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f199_ConditionCheckWrite (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_f199_WriteData (P2CONST(Dcm_Data0xF199_ArrayType, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#else
Std_ReturnType DiagMeas_DcmDspDid_f199_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f198_ConditionCheckWrite (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_f198_WriteData (P2CONST(Dcm_Data0xF198_ArrayType, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#else
Std_ReturnType DiagMeas_DcmDspDid_f198_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_102_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_102_ReadData (P2VAR(Dcm_Data0x0102_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_102_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_103_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_103_ReadData (P2VAR(Dcm_Data0x0103_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_103_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_286_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_286_ReadData (P2VAR(Dcm_Data0x0286_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_286_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_401_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_401_ReadData (P2VAR(Dcm_Data0x0401_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_401_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

void DiagMeas_MainFunction (void)
{
  uint8 Uuid[6];
  boolean Permission;
  boolean EventFailed;
  uint8 Status_0;
  unsigned char Data_2[128];
  uint16 Index_2;
  uint8 Status;
  uint8 Data_1;
  uint16 Index_1;
  NegativeResponseCodeType ErrorCode;
  uint16 DataLength;
  unsigned char Data_0[128];
  uint16 Index_0;
  uint8 Data;
  uint16 Index;
  boolean BlockChanged_0;
  uint8 DataIndex_0;
  NvM_DstPtrType DstPtr_2;
  uint8 DataIndexPtr_0;
  boolean BlockChanged;
  uint8 DataIndex;
  NvM_ASR40_DstPtrType DstPtr_1;
  uint8 DataIndexPtr;
  NvM_ASR40_RequestResultType RequestResultPtr_0;
  NvM_RequestResultType RequestResultPtr;
  NvM_DstPtrType DstPtr_0;
  NvM_SrcPtrType SrcPtr_0;
  NvM_ASR40_DstPtrType DstPtr;
  NvM_ASR40_SrcPtrType SrcPtr;
  Voltage_u16 Voltage_3;
  Distance_s32 Y_Near;
  Distance_s32 Y;
  Distance_s32 X_Near;
  Distance_s32 X;
  AngleDegree_s16 ThetaNear;
  AngleDegree_s16 Theta;
  boolean BoolVal;
  P2CONST(uint32, AUTOMATIC, AUTOMATIC) FarFieldRssiValues;
  Voltage_s32 Voltage_2;
  Voltage_s32 Voltage_1;
  Voltage_s32 Voltage_0;
  Current_s32 Current_4;
  Current_s32 Current_3;
  Current_s32 Current_2;
  Current_s32 Current_1;
  Current_s32 Current_0;
  uint8 StatusByte;
  Period_u32 Period;
  TempC TempCValue_5;
  P2CONST(SftyBoolTF, AUTOMATIC, AUTOMATIC) SftyBoolValue_2;
  P2CONST(SftyBoolTF, AUTOMATIC, AUTOMATIC) SftyBoolValue_1;
  P2CONST(SftyBoolTF, AUTOMATIC, AUTOMATIC) SftyBoolValue_0;
  P2CONST(SftyBoolTF, AUTOMATIC, AUTOMATIC) SftyBoolValue;
  FodDetectTh Value_2;
  FodDetectTh Value_1;
  FodDetectTh Value_0;
  FodDetectTh Value;
  Distance_s32 PositionYValue_0;
  Distance_s32 PositionYValue;
  Distance_s32 PositionXValue_0;
  Distance_s32 PositionXValue;
  GenericByte GenericByte;
  TempC TempCValue_4;
  TempC TempCValue_3;
  ZMoverPos ZMoverPositionVal;
  Current_s32 Current;
  TempC TempCValue_2;
  GenericByte SCI_SSM_ActStateWsValue;
  GenericByte SCI_WsSafety_SftyMgrState_u8_TValue;
  TempC TempCValue_1;
  Percentage_u16 SCI_IOHW_DutyCycle_u16_TValue;
  Voltage_u16 Voltage;
  GenericByte SCI_DiagMeas_Pwm_LED_u8_TValue_1;
  GenericByte SCI_DiagMeas_Pwm_LED_u8_TValue_0;
  GenericByte SCI_DiagMeas_Pwm_LED_u8_TValue;
  signalsValidity ValidityPosNearValue;
  signalsValidity ValidityPosFarValue;
  TempC TempCValue_0;
  TempC TempCValue;
  Std_ReturnType status;

  TempCValue = Rte_IRead_DiagMeas_MainFunction_WspIoHwAbs_tWpmFan_TempCValue();

  TempCValue_0 = Rte_IRead_DiagMeas_MainFunction_WspIoHwAbs_tWpmSink_TempCValue();

  ValidityPosFarValue = Rte_IRead_DiagMeas_MainFunction_WspFodCan_recPosModSignalsHealth_ValidityPosFarValue();

  ValidityPosNearValue = Rte_IRead_DiagMeas_MainFunction_WspFodCan_recPosModSignalsHealth_ValidityPosNearValue();

  SCI_DiagMeas_Pwm_LED_u8_TValue = Rte_IRead_DiagMeas_MainFunction_WspLedMgr_pwmLedBlue_SCI_DiagMeas_Pwm_LED_u8_TValue();

  SCI_DiagMeas_Pwm_LED_u8_TValue_0 = Rte_IRead_DiagMeas_MainFunction_WspLedMgr_pwmLedGreen_SCI_DiagMeas_Pwm_LED_u8_TValue();

  SCI_DiagMeas_Pwm_LED_u8_TValue_1 = Rte_IRead_DiagMeas_MainFunction_WspLedMgr_pwmLedRed_SCI_DiagMeas_Pwm_LED_u8_TValue();

  Voltage = Rte_IRead_DiagMeas_MainFunction_WspIoHwAbs_uP12V0_Voltage();

  SCI_IOHW_DutyCycle_u16_TValue = Rte_IRead_DiagMeas_MainFunction_WspIoHwAbs_pwmFanSpeed_SCI_IOHW_DutyCycle_u16_TValue();

  TempCValue_1 = Rte_IRead_DiagMeas_MainFunction_WspFodCan_tAmb_TempCValue();

  SCI_WsSafety_SftyMgrState_u8_TValue = Rte_IRead_DiagMeas_MainFunction_WspSafety_stWsSftyMgr_SCI_WsSafety_SftyMgrState_u8_TValue();

  SCI_SSM_ActStateWsValue = Rte_IRead_DiagMeas_MainFunction_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue();

  TempCValue_2 = Rte_IRead_DiagMeas_MainFunction_WspIoHwAbs_tWpmAmb_TempCValue();

  Current = Rte_IRead_DiagMeas_MainFunction_WspZMovCdd_iZMovMeas_Current();

  ZMoverPositionVal = Rte_IRead_DiagMeas_MainFunction_WspZMovCdd_posZM_ZMoverPositionVal();

  TempCValue_3 = Rte_IRead_DiagMeas_MainFunction_WspIoHwAbs_tPpmAmb_TempCValue();

  TempCValue_4 = Rte_IRead_DiagMeas_MainFunction_WspIoHwAbs_tPpmSink_TempCValue();

  GenericByte = Rte_IRead_DiagMeas_MainFunction_WspPwrTrf_stPwrTrf_GenericByte();

  PositionXValue = Rte_IRead_DiagMeas_MainFunction_WspVehDet_posX_PositionXValue();

  PositionXValue_0 = Rte_IRead_DiagMeas_MainFunction_WspVehDet_posXTh_PositionXValue();

  PositionYValue = Rte_IRead_DiagMeas_MainFunction_WspVehDet_posY_PositionYValue();

  PositionYValue_0 = Rte_IRead_DiagMeas_MainFunction_WspVehDet_posYTh_PositionYValue();

  Value = Rte_IRead_DiagMeas_MainFunction_WspFod_stFodStartupChrgTh_Value();

  Value_0 = Rte_IRead_DiagMeas_MainFunction_WspFod_stFodZMDownTh_Value();

  Value_1 = Rte_IRead_DiagMeas_MainFunction_WspFod_stFodZMUpTh_Value();

  Value_2 = Rte_IRead_DiagMeas_MainFunction_WspFod_stFodPreCheckTh_Value();

  SftyBoolValue = Rte_IRead_DiagMeas_MainFunction_WspFod_stFodStartupChrg_SftyBoolValue();

  SftyBoolValue_0 = Rte_IRead_DiagMeas_MainFunction_WspFod_stFodZMDown_SftyBoolValue();

  SftyBoolValue_1 = Rte_IRead_DiagMeas_MainFunction_WspFod_stFodZMUp_SftyBoolValue();

  SftyBoolValue_2 = Rte_IRead_DiagMeas_MainFunction_WspFod_stFodPreCheck_SftyBoolValue();

  TempCValue_5 = Rte_IRead_DiagMeas_MainFunction_WspIoHwAbs_tSbc_TempCValue();

  Period = Rte_IRead_DiagMeas_MainFunction_WspPfcCdd_tiGrid_Period();

  StatusByte = Rte_IRead_DiagMeas_MainFunction_WspIoHwAbs_numCodRes_StatusByte();

  Current_0 = Rte_IRead_DiagMeas_MainFunction_WspB6cdd_iWpcPhas1_Current();

  Current_1 = Rte_IRead_DiagMeas_MainFunction_WspB6cdd_iWpcPhas2_Current();

  Current_2 = Rte_IRead_DiagMeas_MainFunction_WspB6cdd_iWpcPhas3_Current();

  Current_3 = Rte_IRead_DiagMeas_MainFunction_WspPfcCdd_iAcGrid_Current();

  Current_4 = Rte_IRead_DiagMeas_MainFunction_WspIoHwAbs_iWpcIn_Current();

  Voltage_0 = Rte_IRead_DiagMeas_MainFunction_WspPfcCdd_uBoost_Voltage();

  Voltage_1 = Rte_IRead_DiagMeas_MainFunction_WspPfcCdd_uAcGrid_Voltage();

  Voltage_2 = Rte_IRead_DiagMeas_MainFunction_WspIoHwAbs_uP5V0_Voltage();

  FarFieldRssiValues = Rte_IRead_DiagMeas_MainFunction_WspFodCan_recPosData_FarFieldRssiValues();

  BoolVal = Rte_IRead_DiagMeas_MainFunction_WspFodCan_stHallSensorParked_BoolVal();

  Theta = Rte_IRead_DiagMeas_MainFunction_WspPosMgr_posActual_Theta();

  ThetaNear = Rte_IRead_DiagMeas_MainFunction_WspPosMgr_posActual_ThetaNear();

  X = Rte_IRead_DiagMeas_MainFunction_WspPosMgr_posActual_X();

  X_Near = Rte_IRead_DiagMeas_MainFunction_WspPosMgr_posActual_X_Near();

  Y = Rte_IRead_DiagMeas_MainFunction_WspPosMgr_posActual_Y();

  Y_Near = Rte_IRead_DiagMeas_MainFunction_WspPosMgr_posActual_Y_Near();

  Voltage_3 = Rte_IRead_DiagMeas_MainFunction_WspIoHwAbs_uP3V3_Voltage();

  status = Rte_Call_PS_ASR40_NvM_DID_f197_WriteBlock(SrcPtr);

  status = Rte_Call_PS_ASR40_NvM_DID_f197_ReadBlock(DstPtr);

  status = Rte_Call_PS_NvM_DID_f197_WriteBlock(SrcPtr_0);

  status = Rte_Call_PS_NvM_DID_f197_ReadBlock(DstPtr_0);

  status = Rte_Call_PS_NvM_DID_f197_GetErrorStatus(&RequestResultPtr);

  status = Rte_Call_PS_ASR40_NvM_DID_f197_GetErrorStatus(&RequestResultPtr_0);

  status = Rte_Call_PS_ASR40_NvM_DID_f197_GetDataIndex(&DataIndexPtr);

  status = Rte_Call_PS_ASR40_NvM_DID_f197_InvalidateNvBlock();

  status = Rte_Call_PS_ASR40_NvM_DID_f197_RestoreBlockDefaults(DstPtr_1);

  status = Rte_Call_PS_ASR40_NvM_DID_f197_SetDataIndex(DataIndex);

  status = Rte_Call_PS_ASR40_NvM_DID_f197_SetRamBlockStatus(BlockChanged);

  status = Rte_Call_PS_NvM_DID_f197_GetDataIndex(&DataIndexPtr_0);

  status = Rte_Call_PS_NvM_DID_f197_InvalidateNvBlock();

  status = Rte_Call_PS_NvM_DID_f197_RestoreBlockDefaults(DstPtr_2);

  status = Rte_Call_PS_NvM_DID_f197_SetDataIndex(DataIndex_0);

  status = Rte_Call_PS_NvM_DID_f197_SetRamBlockStatus(BlockChanged_0);

  status = Rte_Call_WspNvmExt_fncNvmExtServ_NvmExt_DiagRead(Index, &Data);

  status = Rte_Call_WspNvmExt_fncNvmExtServ_NvmExt_DiagWrite(Index_0, Data_0, DataLength, &ErrorCode);

  status = Rte_Call_WspNvmExt_fncNvmExtServ_NvmExt_Read(Index_1, &Data_1, &Status);

  status = Rte_Call_WspNvmExt_fncNvmExtServ_NvmExt_Write(Index_2, Data_2, &Status_0);

  status = Rte_Call_Event_MAGN_COUPL_NOT_PLAUSIBLE_GetEventFailed(&EventFailed);

  status = Rte_Call_FI_FID_CouplErr_GetFunctionPermission(&Permission);

  status = Rte_Call_WspBleCdd_fncWsUuid_GetUuid(Uuid);

}

Std_ReturnType DiagMeas_DcmDspDid_410_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_410_ReadData (P2VAR(Dcm_Data0x0410_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_410_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f1df_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_f1df_ReadData (P2VAR(Dcm_Data0xF1DF_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_f1df_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f1d5_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_f1d5_ReadData (P2VAR(Dcm_Data0xF1D5_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_f1d5_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_2a30_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_2a30_ReadData (P2VAR(Dcm_Data0x2A30_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_2a30_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f1aa_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_f1aa_ReadData (P2VAR(Dcm_Data0xF1AA_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_f1aa_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f191_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_f191_ReadData (P2VAR(Dcm_Data0xF191_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_f191_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f1a2_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_f1a2_ReadData (P2VAR(Dcm_Data0xF1A2_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_f1a2_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f1a3_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_f1a3_ReadData (P2VAR(Dcm_Data0xF1A3_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_f1a3_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f187_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_f187_ReadData (P2VAR(Dcm_Data0xF187_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_f187_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f19e_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_f19e_ReadData (P2VAR(Dcm_Data0xF19E_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_f19e_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f189_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_f189_ReadData (P2VAR(Dcm_Data0xF189_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_f189_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f197_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_f197_ReadData (P2VAR(Dcm_Data0xF197_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_f197_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_5342_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_5342_ReadData (P2VAR(Dcm_Data0x5342_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_5342_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_53ca_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_53ca_ReadData (P2VAR(Dcm_Data0x53CA_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_53ca_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_53d2_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagMeas_DcmDspDid_53d2_ReadData (P2VAR(Dcm_Data0x53D2_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagMeas_DcmDspDid_53d2_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f190_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f190_ReadData (P2VAR(Dcm_Data0xF190_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f190_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f18c_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f18c_ReadData (P2VAR(Dcm_Data0xF18C_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f18c_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f17c_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f17c_ReadData (P2VAR(Dcm_Data0xF17C_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f17c_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53ea_ReadData (P2VAR(Dcm_Data0x53EA_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53ea_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53ea_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53eb_ReadData (P2VAR(Dcm_Data0x53EB_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53eb_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53eb_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f0_ReadData (P2VAR(Dcm_Data0x53F0_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f0_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f0_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53ec_ReadData (P2VAR(Dcm_Data0x53EC_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53ec_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53ec_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53ed_ReadData (P2VAR(Dcm_Data0x53ED_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53ed_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53ed_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53ee_ReadData (P2VAR(Dcm_Data0x53EE_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53ee_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53ee_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53ef_ReadData (P2VAR(Dcm_Data0x53EF_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53ef_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53ef_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53e3_ReadData (P2VAR(Dcm_Data0x53E3_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53e3_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53e3_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53e4_ReadData (P2VAR(Dcm_Data0x53E4_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53e4_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53e4_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53e0_ReadData (P2VAR(Dcm_Data0x53E0_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53e0_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53e0_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f1_ReadData (P2VAR(Dcm_Data0x53F1_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f1_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f1_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f3_ReadData (P2VAR(Dcm_Data0x53F3_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f3_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f3_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f4_ReadData (P2VAR(Dcm_Data0x53F4_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f4_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f4_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f6_ReadData (P2VAR(Dcm_Data0x53F6_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f6_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f6_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f7_ReadData (P2VAR(Dcm_Data0x53F7_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f7_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f7_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f8_ReadData (P2VAR(Dcm_Data0x53F8_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f8_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f8_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f9_ReadData (P2VAR(Dcm_Data0x53F9_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f9_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53f9_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53fb_ReadData (P2VAR(Dcm_Data0x53FB_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53fb_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53fb_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53fc_ReadData (P2VAR(Dcm_Data0x53FC_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53fc_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53fc_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53fd_ReadData (P2VAR(Dcm_Data0x53FD_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53fd_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53fd_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53ff_ReadData (P2VAR(Dcm_Data0x53FF_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53ff_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_53ff_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5417_ReadData (P2VAR(Dcm_Data0x5417_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5417_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5417_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5426_ReadData (P2VAR(Dcm_Data0x5426_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5426_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5426_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_542d_ReadData (P2VAR(Dcm_Data0x542D_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_542d_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_542d_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_543d_ReadData (P2VAR(Dcm_Data0x543D_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_543d_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_543d_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5431_ReadData (P2VAR(Dcm_Data0x5431_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5431_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5431_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5448_ReadData (P2VAR(Dcm_Data0x5448_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5448_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5448_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5343_ReadData (P2VAR(Dcm_Data0x5343_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5343_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5343_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_41fc_ReadData (P2VAR(Dcm_Data0x41FC_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_41fc_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_41fc_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_4780_ReadData (P2VAR(Dcm_Data0x4780_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_4780_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_4780_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5432_ReadData (P2VAR(Dcm_Data0x5432_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5432_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5432_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5433_ReadData (P2VAR(Dcm_Data0x5433_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5433_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5433_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5435_ReadData (P2VAR(Dcm_Data0x5435_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5435_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5435_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5436_ReadData (P2VAR(Dcm_Data0x5436_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5436_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5436_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5437_ReadData (P2VAR(Dcm_Data0x5437_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5437_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5437_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5438_ReadData (P2VAR(Dcm_Data0x5438_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5438_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5438_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_2b3_ReadData (P2VAR(Dcm_Data0x02B3_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_2b3_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_2b3_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_2d1_ReadData (P2VAR(Dcm_Data0x02D1_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_2d1_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_2d1_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_2ca_ReadData (P2VAR(Dcm_Data0x02CA_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_2ca_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_2ca_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5439_ReadData (P2VAR(Dcm_Data0x5439_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5439_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5439_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_543a_ReadData (P2VAR(Dcm_Data0x543A_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_543a_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_543a_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_543b_ReadData (P2VAR(Dcm_Data0x543B_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_543b_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_543b_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_543c_ReadData (P2VAR(Dcm_Data0x543C_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_543c_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_543c_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_534b_ReadData (P2VAR(Dcm_Data0x534B_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_534b_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_534b_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_54d2_ReadData (P2VAR(Dcm_Data0x54D2_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_54d2_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_54d2_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_534d_ReadData (P2VAR(Dcm_Data0x534D_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_534d_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_534d_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_534f_ReadData (P2VAR(Dcm_Data0x534F_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_534f_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_534f_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5350_ReadData (P2VAR(Dcm_Data0x5350_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5350_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5350_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5351_ReadData (P2VAR(Dcm_Data0x5351_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5351_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5351_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5352_ReadData (P2VAR(Dcm_Data0x5352_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5352_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5352_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5353_ReadData (P2VAR(Dcm_Data0x5353_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5353_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5353_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5354_ReadData (P2VAR(Dcm_Data0x5354_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5354_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5354_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5355_ReadData (P2VAR(Dcm_Data0x5355_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5355_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5355_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_4770_ReadData (P2VAR(Dcm_Data0x4770_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_4770_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_4770_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_476f_ReadData (P2VAR(Dcm_Data0x476F_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_476f_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_476f_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5356_ReadData (P2VAR(Dcm_Data0x5356_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5356_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5356_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5357_ReadData (P2VAR(Dcm_Data0x5357_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5357_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5357_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5358_ReadData (P2VAR(Dcm_Data0x5358_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5358_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5358_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5359_ReadData (P2VAR(Dcm_Data0x5359_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5359_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5359_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_535a_ReadData (P2VAR(Dcm_Data0x535A_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_535a_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_535a_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_535d_ReadData (P2VAR(Dcm_Data0x535D_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_535d_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_535d_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_535e_ReadData (P2VAR(Dcm_Data0x535E_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_535e_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_535e_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_535f_ReadData (P2VAR(Dcm_Data0x535F_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_535f_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_535f_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5361_ReadData (P2VAR(Dcm_Data0x5361_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5361_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5361_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5362_ReadData (P2VAR(Dcm_Data0x5362_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5362_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5362_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5363_ReadData (P2VAR(Dcm_Data0x5363_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5363_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5363_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5364_ReadData (P2VAR(Dcm_Data0x5364_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5364_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5364_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5365_ReadData (P2VAR(Dcm_Data0x5365_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5365_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5365_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5366_ReadData (P2VAR(Dcm_Data0x5366_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5366_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5366_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5367_ReadData (P2VAR(Dcm_Data0x5367_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5367_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5367_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5368_ReadData (P2VAR(Dcm_Data0x5368_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5368_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5368_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_536a_ReadData (P2VAR(Dcm_Data0x536A_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_536a_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_536a_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_543e_ReadData (P2VAR(Dcm_Data0x543E_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_543e_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_543e_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_543f_ReadData (P2VAR(Dcm_Data0x543F_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_543f_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_543f_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5440_ReadData (P2VAR(Dcm_Data0x5440_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5440_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5440_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5441_ReadData (P2VAR(Dcm_Data0x5441_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5441_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5441_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5368_ReadDataLength (P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) DidLength)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5367_ReadDataLength (P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) DidLength)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5366_ReadDataLength (P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) DidLength)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_5365_ReadDataLength (P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) DidLength)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_476f_ReadDataLength (P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) DidLength)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_534f_ReadDataLength (P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) DidLength)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_54d2_ReadDataLength (P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) DidLength)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_534b_ReadDataLength (P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) DidLength)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType DiagMeas_DcmDspDid_f19e_ReadDataLength (P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) DidLength)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_545c_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_545c_ReadData (P2VAR(Dcm_Data0x545C_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_545c_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_545d_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_545d_ReadData (P2VAR(Dcm_Data0x545D_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_545d_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_545e_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_545e_ReadData (P2VAR(Dcm_Data0x545E_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_545e_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_545f_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_545f_ReadData (P2VAR(Dcm_Data0x545F_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_545f_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1a0_ReadData (P2VAR(Dcm_Data0xF1A0_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1a0_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1a0_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1a0_WriteData (P2CONST(Dcm_Data0xF1A0_ArrayType, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1a0_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1a0_ConditionCheckWrite (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1a4_ReadData (P2VAR(Dcm_Data0xF1A4_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1a4_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1a4_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1a4_WriteData (P2CONST(Dcm_Data0xF1A4_ArrayType, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1a4_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1a4_ConditionCheckWrite (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1a1_ReadData (P2VAR(Dcm_Data0xF1A1_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1a1_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1a1_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1a1_WriteData (P2CONST(Dcm_Data0xF1A1_ArrayType, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1a1_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1a1_ConditionCheckWrite (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1b1_ReadData (P2VAR(Dcm_Data0xF1B1_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1b1_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1b1_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1b3_ReadData (P2VAR(Dcm_Data0xF1B3_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1b3_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1b3_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1b1_ReadDataLength (P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) DidLength)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_f1b3_ReadDataLength (P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) DidLength)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff30_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff30_ConditionCheckWrite (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff30_ReadData (P2VAR(Dcm_Data0xFF30_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff30_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff30_WriteData (P2CONST(Dcm_Data0xFF30_ArrayType, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff30_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff31_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff31_ConditionCheckWrite (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff31_ReadData (P2VAR(Dcm_Data0xFF31_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff31_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff31_WriteData (P2CONST(Dcm_Data0xFF31_ArrayType, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff31_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff33_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff33_ConditionCheckWrite (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff33_ReadData (P2VAR(Dcm_Data0xFF33_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff33_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff33_WriteData (P2CONST(Dcm_Data0xFF33_ArrayType, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff33_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff34_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff34_ConditionCheckWrite (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff34_ReadData (P2VAR(Dcm_Data0xFF34_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff34_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff34_WriteData (P2CONST(Dcm_Data0xFF34_ArrayType, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff34_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff35_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff35_ConditionCheckWrite (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff35_ReadData (P2VAR(Dcm_Data0xFF35_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff35_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff35_WriteData (P2CONST(Dcm_Data0xFF35_ArrayType, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff35_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff36_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff36_ConditionCheckWrite (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff36_ReadData (P2VAR(Dcm_Data0xFF36_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff36_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff36_WriteData (P2CONST(Dcm_Data0xFF36_ArrayType, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff36_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff37_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff37_ConditionCheckWrite (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff37_ReadData (P2VAR(Dcm_Data0xFF37_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff37_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff37_WriteData (P2CONST(Dcm_Data0xFF37_ArrayType, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_ff37_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_902_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_902_ConditionCheckWrite (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_902_ReadData (P2VAR(Dcm_Data0x0902_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_902_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_902_WriteData (P2CONST(Dcm_Data0x0902_ArrayType, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_902_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#endif
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_410_WriteData (P2CONST(Dcm_Data0x0410_ArrayType, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_410_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_CONST) data, uint16 dataLength, P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_410_ConditionCheckWrite (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_535b_ReadData (P2VAR(Dcm_Data0x535B_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_535b_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_535b_ReadDataLength (P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) DidLength)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType SCI_DiagMeas_DiagMeas_DcmDspDid_535b_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

void SCI_DiagMeas_IComDiagRequest (ByteDataPtr RequestData, uint8 RequestDataLength, P2VAR(GenericByte, AUTOMATIC, RTE_APPL_DATA) ResultData, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) ResultDataLength)
{
  Std_ReturnType status;

}

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------

  ------------------------[per instance memory API]--------------------------

*/
/** @} doxygen end group definition */
/*==================[end of file]============================================*/

