
/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains an Rte component template / example code
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Tue May 22 10:59:42 CEST 2018. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#include "Rte_SCI_IOHW.h"

/*------------------------[runnable entity skeletons]------------------------*/

void WsIoHwAb_WriteToRte (void)
{
  P2VAR(Current_s32, AUTOMATIC, AUTOMATIC) Current_0;
  Current_s32 Current;
  P2VAR(PfcPwrGood, AUTOMATIC, AUTOMATIC) PfcPwrGood_0;
  PfcPwrGood PfcPwrGood;
  P2VAR(PfcAcOk, AUTOMATIC, AUTOMATIC) PfcAcOk_0;
  PfcAcOk PfcAcOk;
  P2VAR(Percentage_u16, AUTOMATIC, AUTOMATIC) SCI_IOHW_DutyCycle_u16_TValue_0;
  Percentage_u16 SCI_IOHW_DutyCycle_u16_TValue;
  Std_ReturnType status;

  Rte_IWrite_WsIoHwAb_WriteToRte_WspIoHwAbs_pwmFanSpeed_SCI_IOHW_DutyCycle_u16_TValue(SCI_IOHW_DutyCycle_u16_TValue);

  SCI_IOHW_DutyCycle_u16_TValue_0 = Rte_IWriteRef_WsIoHwAb_WriteToRte_WspIoHwAbs_pwmFanSpeed_SCI_IOHW_DutyCycle_u16_TValue();

  Rte_IWrite_WsIoHwAb_WriteToRte_WspIoHwAbs_stPfcAcOk_PfcAcOk(PfcAcOk);

  PfcAcOk_0 = Rte_IWriteRef_WsIoHwAb_WriteToRte_WspIoHwAbs_stPfcAcOk_PfcAcOk();

  Rte_IWrite_WsIoHwAb_WriteToRte_WspIoHwAbs_stPwrGood_PfcPwrGood(PfcPwrGood);

  PfcPwrGood_0 = Rte_IWriteRef_WsIoHwAb_WriteToRte_WspIoHwAbs_stPwrGood_PfcPwrGood();

  Rte_IWrite_WsIoHwAb_WriteToRte_WspIoHwAbs_iWpcIn_Current(Current);

  Current_0 = Rte_IWriteRef_WsIoHwAb_WriteToRte_WspIoHwAbs_iWpcIn_Current();

}

void WsIoHwAb_WriteToMCAL (void)
{
  Percentage_u16 SCI_IOHW_DutyCycle_u16_TValue;
  GenericByte SCI_IOHW_PwmLED_u8_TValue_1;
  GenericByte SCI_IOHW_PwmLED_u8_TValue_0;
  GenericByte SCI_IOHW_PwmLED_u8_TValue;
  Std_ReturnType status;

  SCI_IOHW_PwmLED_u8_TValue = Rte_IRead_WsIoHwAb_WriteToMCAL_WspLedMgr_pwmLedGreen_SCI_IOHW_PwmLED_u8_TValue();

  SCI_IOHW_PwmLED_u8_TValue_0 = Rte_IRead_WsIoHwAb_WriteToMCAL_WspLedMgr_pwmLedRed_SCI_IOHW_PwmLED_u8_TValue();

  SCI_IOHW_PwmLED_u8_TValue_1 = Rte_IRead_WsIoHwAb_WriteToMCAL_WspLedMgr_pwmLedBlue_SCI_IOHW_PwmLED_u8_TValue();

  SCI_IOHW_DutyCycle_u16_TValue = Rte_IRead_WsIoHwAb_WriteToMCAL_WspPwrTrf_pwmFanCtrl_SCI_IOHW_DutyCycle_u16_TValue();

}

void SCI_IOHW_WsIoHwAb_Calc10ms (void)
{
  Dem_EventStatusType EventStatus_12;
  Dem_EventStatusType EventStatus_11;
  Dem_EventStatusType EventStatus_10;
  Dem_EventStatusType EventStatus_9;
  Dem_EventStatusType EventStatus_8;
  Dem_EventStatusType EventStatus_7;
  Dem_EventStatusType EventStatus_6;
  Dem_EventStatusType EventStatus_5;
  Dem_EventStatusType EventStatus_4;
  Dem_EventStatusType EventStatus_3;
  Dem_EventStatusType EventStatus_2;
  Dem_EventStatusType EventStatus_1;
  Dem_EventStatusType EventStatus_0;
  Dem_EventStatusType EventStatus;
  boolean BoolVal_1;
  GenericByte DiagCtrlFreeze;
  uint8 DiagCtrlFan;
  Voltage_u16 Voltage_5;
  boolean BoolVal_0;
  boolean BoolVal;
  P2VAR(Voltage_u16, AUTOMATIC, AUTOMATIC) Voltage_4;
  Voltage_u16 Voltage_3;
  P2VAR(Voltage_s32, AUTOMATIC, AUTOMATIC) Voltage_2;
  Voltage_s32 Voltage_1;
  P2VAR(uint8, AUTOMATIC, AUTOMATIC) StatusByte_2;
  uint8 StatusByte_1;
  P2VAR(uint8, AUTOMATIC, AUTOMATIC) StatusByte_0;
  uint8 StatusByte;
  P2VAR(sint16, AUTOMATIC, AUTOMATIC) Cntr_0;
  sint16 Cntr;
  P2VAR(Current_s16, AUTOMATIC, AUTOMATIC) Current_mA_0;
  Current_s16 Current_mA;
  P2VAR(TempC, AUTOMATIC, AUTOMATIC) TempCValue_10;
  TempC TempCValue_9;
  P2VAR(Voltage_u16, AUTOMATIC, AUTOMATIC) Voltage_0;
  Voltage_u16 Voltage;
  P2VAR(TempC, AUTOMATIC, AUTOMATIC) TempCValue_8;
  TempC TempCValue_7;
  P2VAR(TempC, AUTOMATIC, AUTOMATIC) TempCValue_6;
  TempC TempCValue_5;
  P2VAR(TempC, AUTOMATIC, AUTOMATIC) TempCValue_4;
  TempC TempCValue_3;
  P2VAR(TempC, AUTOMATIC, AUTOMATIC) TempCValue_2;
  TempC TempCValue_1;
  P2VAR(TempC, AUTOMATIC, AUTOMATIC) TempCValue_0;
  TempC TempCValue;
  Std_ReturnType status;

  Rte_IWrite_WsIoHwAb_Calc10ms_WspIoHwAbs_tWpmAmb_TempCValue(TempCValue);

  TempCValue_0 = Rte_IWriteRef_WsIoHwAb_Calc10ms_WspIoHwAbs_tWpmAmb_TempCValue();

  Rte_IWrite_WsIoHwAb_Calc10ms_WspIoHwAbs_tWpmFan_TempCValue(TempCValue_1);

  TempCValue_2 = Rte_IWriteRef_WsIoHwAb_Calc10ms_WspIoHwAbs_tWpmFan_TempCValue();

  Rte_IWrite_WsIoHwAb_Calc10ms_WspIoHwAbs_tWpmSink_TempCValue(TempCValue_3);

  TempCValue_4 = Rte_IWriteRef_WsIoHwAb_Calc10ms_WspIoHwAbs_tWpmSink_TempCValue();

  Rte_IWrite_WsIoHwAb_Calc10ms_WspIoHwAbs_tPpmSink_TempCValue(TempCValue_5);

  TempCValue_6 = Rte_IWriteRef_WsIoHwAb_Calc10ms_WspIoHwAbs_tPpmSink_TempCValue();

  Rte_IWrite_WsIoHwAb_Calc10ms_WspIoHwAbs_tPpmAmb_TempCValue(TempCValue_7);

  TempCValue_8 = Rte_IWriteRef_WsIoHwAb_Calc10ms_WspIoHwAbs_tPpmAmb_TempCValue();

  Rte_IWrite_WsIoHwAb_Calc10ms_WspIoHwAbs_uP12V0_Voltage(Voltage);

  Voltage_0 = Rte_IWriteRef_WsIoHwAb_Calc10ms_WspIoHwAbs_uP12V0_Voltage();

  Rte_IWrite_WsIoHwAb_Calc10ms_WspIoHwAbs_tSbc_TempCValue(TempCValue_9);

  TempCValue_10 = Rte_IWriteRef_WsIoHwAb_Calc10ms_WspIoHwAbs_tSbc_TempCValue();

  Rte_IWrite_WsIoHwAb_Calc10ms_WspIoHwAbs_iZMovRaw_Current_mA(Current_mA);

  Current_mA_0 = Rte_IWriteRef_WsIoHwAb_Calc10ms_WspIoHwAbs_iZMovRaw_Current_mA();

  Rte_IWrite_WsIoHwAb_Calc10ms_WspIoHwAbs_cntZMovEnc_Cntr(Cntr);

  Cntr_0 = Rte_IWriteRef_WsIoHwAb_Calc10ms_WspIoHwAbs_cntZMovEnc_Cntr();

  Rte_IWrite_WsIoHwAb_Calc10ms_WspIoHwAbs_stZMovFault_StatusByte(StatusByte);

  StatusByte_0 = Rte_IWriteRef_WsIoHwAb_Calc10ms_WspIoHwAbs_stZMovFault_StatusByte();

  Rte_IWrite_WsIoHwAb_Calc10ms_WspIoHwAbs_numCodRes_StatusByte(StatusByte_1);

  StatusByte_2 = Rte_IWriteRef_WsIoHwAb_Calc10ms_WspIoHwAbs_numCodRes_StatusByte();

  Rte_IWrite_WsIoHwAb_Calc10ms_WspIoHwAbs_uP5V0_Voltage(Voltage_1);

  Voltage_2 = Rte_IWriteRef_WsIoHwAb_Calc10ms_WspIoHwAbs_uP5V0_Voltage();

  Rte_IWrite_WsIoHwAb_Calc10ms_WspIoHwAbs_uP3V3_Voltage(Voltage_3);

  Voltage_4 = Rte_IWriteRef_WsIoHwAb_Calc10ms_WspIoHwAbs_uP3V3_Voltage();

  BoolVal = Rte_IRead_WsIoHwAb_Calc10ms_WspZMovCdd_dirCCW_BoolVal();

  BoolVal_0 = Rte_IRead_WsIoHwAb_Calc10ms_WspZMovCdd_dirCW_BoolVal();

  Voltage_5 = Rte_IRead_WsIoHwAb_Calc10ms_WspZMovCdd_uMot_Voltage();

  DiagCtrlFan = Rte_IRead_WsIoHwAb_Calc10ms_WspDiagCtrl_cmdFanCtrl_DiagCtrlFan();

  DiagCtrlFreeze = Rte_IRead_WsIoHwAb_Calc10ms_WspDiagCtrl_cmdFanFreeze_DiagCtrlFreeze();

  BoolVal_1 = Rte_IRead_WsIoHwAb_Calc10ms_WspSafety_cmdRcdTst_BoolVal();

  status = Rte_Call_Event_B6_TEMP_SC_TO_GND_SetEventStatus(EventStatus);

  status = Rte_Call_Event_B6_TEMP_SC_TO_SUP_SetEventStatus(EventStatus_0);

  status = Rte_Call_Event_INCORRECT_CODING_RESISTOR_SetEventStatus(EventStatus_1);

  status = Rte_Call_Event_OPEN_CIRCUIT_CODING_RESISTOR_SetEventStatus(EventStatus_2);

  status = Rte_Call_Event_P3V3_S_VOLTAGE_SENSOR_OVERVOLTAGE_SetEventStatus(EventStatus_3);

  status = Rte_Call_Event_P3V3_S_VOLTAGE_SENSOR_UNDERVOLTAGE_SetEventStatus(EventStatus_4);

  status = Rte_Call_Event_P5V0_SENSOR_SHORT_SUPP_SetEventStatus(EventStatus_5);

  status = Rte_Call_Event_P5V0_VOLTAGE_OVERVOLTAGE_SetEventStatus(EventStatus_6);

  status = Rte_Call_Event_P5V0_VOLTAGE_UNDERVOLTAGE_SetEventStatus(EventStatus_7);

  status = Rte_Call_Event_PFC_TEMP_SC_TO_GND_SetEventStatus(EventStatus_8);

  status = Rte_Call_Event_PFC_TEMP_SC_TO_SUP_SetEventStatus(EventStatus_9);

  status = Rte_Call_Event_RECT_TEMP_SC_TO_GND_SetEventStatus(EventStatus_10);

  status = Rte_Call_Event_SHORT_CIRCUIT_CODING_RESISTOR_SetEventStatus(EventStatus_11);

  status = Rte_Call_Event_RECT_TEMP_SC_TO_SUP_SetEventStatus(EventStatus_12);

}

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------

  ------------------------[per instance memory API]--------------------------

*/
/** @} doxygen end group definition */
/*==================[end of file]============================================*/

