
/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains an Rte component template / example code
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Mon Apr 16 09:34:11 CEST 2018. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#include "Rte_SCI_SftyIO.h"

/*------------------------[runnable entity skeletons]------------------------*/

void WsSftyIo_Read_fromHW (void)
{
  WdgM_CheckpointIdType CheckpointId;
  P2VAR(SftyBoolED, AUTOMATIC, AUTOMATIC) SCI_SftyIO_SftyEnableDisableValue_2;
  SftyBoolED SCI_SftyIO_SftyEnableDisableValue_1;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_SftyIO_SelftestIn_u8_TValue_0;
  GenericByte SCI_SftyIO_SelftestIn_u8_TValue;
  P2VAR(SftyBoolED, AUTOMATIC, AUTOMATIC) SCI_SftyIO_SftyEnableDisableValue_0;
  SftyBoolED SCI_SftyIO_SftyEnableDisableValue;
  Std_ReturnType status;

  Rte_IWrite_WsSftyIo_Read_fromHW_PP_WS_Disable_SCI_SftyIO_SftyEnableDisableValue(&SCI_SftyIO_SftyEnableDisableValue);

  SCI_SftyIO_SftyEnableDisableValue_0 = Rte_IWriteRef_WsSftyIo_Read_fromHW_PP_WS_Disable_SCI_SftyIO_SftyEnableDisableValue();

  Rte_IWrite_WsSftyIo_Read_fromHW_PP_SelfTest_SCI_SftyIO_SelftestIn_u8_TValue(SCI_SftyIO_SelftestIn_u8_TValue);

  SCI_SftyIO_SelftestIn_u8_TValue_0 = Rte_IWriteRef_WsSftyIo_Read_fromHW_PP_SelfTest_SCI_SftyIO_SelftestIn_u8_TValue();

  Rte_IWrite_WsSftyIo_Read_fromHW_PP_ASCStatus_SCI_SftyIO_SftyEnableDisableValue(&SCI_SftyIO_SftyEnableDisableValue_1);

  SCI_SftyIO_SftyEnableDisableValue_2 = Rte_IWriteRef_WsSftyIo_Read_fromHW_PP_ASCStatus_SCI_SftyIO_SftyEnableDisableValue();

  status = Rte_Call_alive_WdgMSvEnt_SftyIoReadFromHw_CheckpointReached(CheckpointId);

  status = Rte_Call_alive_WdgMSvEnt_SftyIoReadFromHw_UpdateAliveCounter();

}

void WsSftyIo_Write_toHW (void)
{
  WdgM_CheckpointIdType CheckpointId;
  P2CONST(SftyBoolED, AUTOMATIC, AUTOMATIC) SCI_SftyIO_SftyEnableDisableValue_0;
  P2CONST(SftyBoolOO, AUTOMATIC, AUTOMATIC) SCI_SftyIO_SftyOnOffValue;
  GenericByte SCI_SftyIO_SelftestIn_u8_TValue;
  P2CONST(SftyBoolED, AUTOMATIC, AUTOMATIC) SCI_SftyIO_SftyEnableDisableValue;
  Std_ReturnType status;

  SCI_SftyIO_SftyEnableDisableValue = Rte_IRead_WsSftyIo_Write_toHW_RP_WS_Disable_SCI_SftyIO_SftyEnableDisableValue();

  SCI_SftyIO_SelftestIn_u8_TValue = Rte_IRead_WsSftyIo_Write_toHW_RP_SelfTest_SCI_SftyIO_SelftestIn_u8_TValue();

  SCI_SftyIO_SftyOnOffValue = Rte_IRead_WsSftyIo_Write_toHW_RP_ResetASC_SCI_SftyIO_SftyOnOffValue();

  SCI_SftyIO_SftyEnableDisableValue_0 = Rte_IRead_WsSftyIo_Write_toHW_RP_EnableZmover_b_T_SCI_SftyIO_SftyEnableDisableValue();

  status = Rte_Call_alive_WdgMSvEnt_SftyIoWriteToHw_CheckpointReached(CheckpointId);

  status = Rte_Call_alive_WdgMSvEnt_SftyIoWriteToHw_UpdateAliveCounter();

}

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------

  ------------------------[per instance memory API]--------------------------

*/
/** @} doxygen end group definition */
/*==================[end of file]============================================*/

