
/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains an Rte component template / example code
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Fri May 04 14:43:36 CEST 2018. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#include "Rte_SCI_ZMover.h"

/*------------------------[runnable entity skeletons]------------------------*/

void Zmover_MainFunction (void)
{
  Dem_EventStatusType EventStatus_12;
  Dem_EventStatusType EventStatus_11;
  Dem_EventStatusType EventStatus_10;
  Dem_EventStatusType EventStatus_9;
  Dem_EventStatusType EventStatus_8;
  Dem_EventStatusType EventStatus_7;
  Dem_EventStatusType EventStatus_6;
  Dem_EventStatusType EventStatus_5;
  Dem_EventStatusType EventStatus_4;
  Dem_EventStatusType EventStatus_3;
  Dem_EventStatusType EventStatus_2;
  Dem_EventStatusType EventStatus_1;
  Dem_EventStatusType EventStatus_0;
  Dem_EventStatusType EventStatus;
  GenericByte SCI_SSM_ActStateWsValue;
  GenericByte DiagCtrlZMovDir;
  GenericByte DiagCtrlFreeze;
  uint8 StatusByte_5;
  boolean BoolVal_6;
  boolean BoolVal_5;
  sint16 Cntr;
  Current_s16 Current_mA;
  Rpm_s16 ZMoverMotSpeedVal_2;
  uint8 StatusByte_4;
  Rpm_s16 ZMoverMotSpeedVal_1;
  uint8 StatusByte_3;
  P2CONST(NvmZMPos, AUTOMATIC, AUTOMATIC) ZMPos;
  P2VAR(boolean, AUTOMATIC, AUTOMATIC) BoolVal_4;
  boolean BoolVal_3;
  P2VAR(zMoverIsActive, AUTOMATIC, AUTOMATIC) Value_0;
  zMoverIsActive Value;
  P2VAR(Voltage_u16, AUTOMATIC, AUTOMATIC) Voltage_0;
  Voltage_u16 Voltage;
  P2VAR(boolean, AUTOMATIC, AUTOMATIC) BoolVal_2;
  boolean BoolVal_1;
  P2VAR(boolean, AUTOMATIC, AUTOMATIC) BoolVal_0;
  boolean BoolVal;
  P2VAR(uint8, AUTOMATIC, AUTOMATIC) StatusByte_2;
  uint8 StatusByte_1;
  P2VAR(uint8, AUTOMATIC, AUTOMATIC) StatusByte_0;
  uint8 StatusByte;
  P2VAR(ZMoverPos, AUTOMATIC, AUTOMATIC) ZMoverPositionVal_0;
  ZMoverPos ZMoverPositionVal;
  P2VAR(Rpm_s16, AUTOMATIC, AUTOMATIC) ZMoverMotSpeedVal_0;
  Rpm_s16 ZMoverMotSpeedVal;
  P2VAR(Current_s32, AUTOMATIC, AUTOMATIC) Current_0;
  Current_s32 Current;
  Std_ReturnType status;

  Rte_IWrite_Zmover_MainFunction_WspZMovCdd_iMeas_Current(Current);

  Current_0 = Rte_IWriteRef_Zmover_MainFunction_WspZMovCdd_iMeas_Current();

  Rte_IWrite_Zmover_MainFunction_WspZMovCdd_vMot_ZMoverMotSpeedVal(ZMoverMotSpeedVal);

  ZMoverMotSpeedVal_0 = Rte_IWriteRef_Zmover_MainFunction_WspZMovCdd_vMot_ZMoverMotSpeedVal();

  Rte_IWrite_Zmover_MainFunction_WspZMovCdd_posZM_ZMoverPositionVal(ZMoverPositionVal);

  ZMoverPositionVal_0 = Rte_IWriteRef_Zmover_MainFunction_WspZMovCdd_posZM_ZMoverPositionVal();

  Rte_IWrite_Zmover_MainFunction_WspZMovCdd_stParked_StatusByte(StatusByte);

  StatusByte_0 = Rte_IWriteRef_Zmover_MainFunction_WspZMovCdd_stParked_StatusByte();

  Rte_IWrite_Zmover_MainFunction_WspZMovCdd_stZMOpCtrl_StatusByte(StatusByte_1);

  StatusByte_2 = Rte_IWriteRef_Zmover_MainFunction_WspZMovCdd_stZMOpCtrl_StatusByte();

  Rte_IWrite_Zmover_MainFunction_WspZMovCdd_dirCCW_BoolVal(BoolVal);

  BoolVal_0 = Rte_IWriteRef_Zmover_MainFunction_WspZMovCdd_dirCCW_BoolVal();

  Rte_IWrite_Zmover_MainFunction_WspZMovCdd_dirCW_BoolVal(BoolVal_1);

  BoolVal_2 = Rte_IWriteRef_Zmover_MainFunction_WspZMovCdd_dirCW_BoolVal();

  Rte_IWrite_Zmover_MainFunction_WspZMovCdd_uMot_Voltage(Voltage);

  Voltage_0 = Rte_IWriteRef_Zmover_MainFunction_WspZMovCdd_uMot_Voltage();

  Rte_IWrite_Zmover_MainFunction_WspZMovCdd_stZMoverActive_Value(Value);

  Value_0 = Rte_IWriteRef_Zmover_MainFunction_WspZMovCdd_stZMoverActive_Value();

  Rte_IWrite_Zmover_MainFunction_WspZMovCdd_stPlayProtActive_BoolVal(BoolVal_3);

  BoolVal_4 = Rte_IWriteRef_Zmover_MainFunction_WspZMovCdd_stPlayProtActive_BoolVal();

  ZMPos = Rte_IRead_Zmover_MainFunction_WspConf_posZM_ZMPos();

  StatusByte_3 = Rte_IRead_Zmover_MainFunction_WspStMgr_stAcReqZM_StatusByte();

  ZMoverMotSpeedVal_1 = Rte_IRead_Zmover_MainFunction_WspStMgr_vReqZM_ZMoverMotSpeedVal();

  StatusByte_4 = Rte_IRead_Zmover_MainFunction_WspPwrTrf_stAcReqZM_StatusByte();

  ZMoverMotSpeedVal_2 = Rte_IRead_Zmover_MainFunction_WspPwrTrf_vReqZM_ZMoverMotSpeedVal();

  Current_mA = Rte_IRead_Zmover_MainFunction_WspIoHwAbs_iZMovRaw_Current_mA();

  Cntr = Rte_IRead_Zmover_MainFunction_WspIoHwAbs_cntZMovEnc_Cntr();

  BoolVal_5 = Rte_IRead_Zmover_MainFunction_WspFodCan_stHallSensorParked_BoolVal();

  BoolVal_6 = Rte_IRead_Zmover_MainFunction_WspFodCan_stReedSensorParked_BoolVal();

  StatusByte_5 = Rte_IRead_Zmover_MainFunction_WspIoHwAbs_stZMovFault_StatusByte();

  DiagCtrlFreeze = Rte_IRead_Zmover_MainFunction_WspDiagCtrl_cmdZMovFreeze_DiagCtrlFreeze();

  DiagCtrlZMovDir = Rte_IRead_Zmover_MainFunction_WspDiagCtrl_dirZMov_DiagCtrlZMovDir();

  SCI_SSM_ActStateWsValue = Rte_IRead_Zmover_MainFunction_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue();

  status = Rte_Call_Event_ZMOVER_CURRENT_HIGH_SetEventStatus(EventStatus);

  status = Rte_Call_Event_ZMOVER_POWER_DEFECT_SetEventStatus(EventStatus_0);

  status = Rte_Call_Event_ZMOVER_HALL_SENSOR_DEFECT_SetEventStatus(EventStatus_1);

  status = Rte_Call_Event_ZMOVER_HALL_MIN_POSITION_SENSOR_DEFECT_SetEventStatus(EventStatus_2);

  status = Rte_Call_Event_ZMOVER_SWITCH_MIN_POSITION_SENSOR_DEFECT_SetEventStatus(EventStatus_3);

  status = Rte_Call_Event_ZMOVER_ACTUATOR_DEFECT_SetEventStatus(EventStatus_4);

  status = Rte_Call_Event_ZMOVER_MOVE_RANDOM_SetEventStatus(EventStatus_5);

  status = Rte_Call_Event_Z_MOVER_WAS_LOWERED_WITH_ACTIVE_FORCE_SetEventStatus(EventStatus_6);

  status = Rte_Call_Event_ZMOVER_MOTOR_OVERHEAT_SetEventStatus(EventStatus_7);

  status = Rte_Call_Event_PINCH_PROTECTION_WAS_ACTIVE_SetEventStatus(EventStatus_8);

  status = Rte_Call_Event_ZMOVER_CURRENT_OFFSET_SetEventStatus(EventStatus_9);

  status = Rte_Call_Event_ZMOVER_MOTOR_NEGATIV_OVERLOAD_SetEventStatus(EventStatus_10);

  status = Rte_Call_Event_ZMOVER_MOTOR_POSITIV_OVERLOAD_SetEventStatus(EventStatus_11);

  status = Rte_Call_Event_Z_MOVER_ACTIVIATION_TIMEOUT_SetEventStatus(EventStatus_12);

}

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------

  ------------------------[per instance memory API]--------------------------

*/
/** @} doxygen end group definition */
/*==================[end of file]============================================*/

