
/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains an Rte component template / example code
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Fri Aug 25 16:41:34 CEST 2017. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#include "Rte_SCI_PosFar.h"

/*------------------------[runnable entity skeletons]------------------------*/

void PosFar_mainFunction (void)
{
  ErrorState WSErrorState;
  uint16 ErrorId;
  P2CONST(PosDataV40, AUTOMATIC, AUTOMATIC) PosDataVal;
  boolean Val_2;
  boolean Val_1;
  float32 Val_0;
  float32 Val;
  Distance_s16 PositionYValue;
  Distance_s16 PositionXValue;
  AngleDegree_s16 AngleValue;
  P2VAR(PosF32, AUTOMATIC, AUTOMATIC) SCI_PosFar_PosF32_TValue_4;
  PosF32 SCI_PosFar_PosF32_TValue_3;
  P2VAR(PosF32, AUTOMATIC, AUTOMATIC) SCI_PosFar_PosF32_TValue_2;
  PosF32 SCI_PosFar_PosF32_TValue_1;
  P2VAR(PosF32, AUTOMATIC, AUTOMATIC) SCI_PosFar_PosF32_TValue_0;
  PosF32 SCI_PosFar_PosF32_TValue;
  Std_ReturnType status;

  Rte_IWrite_PosFar_mainFunction_PP_FarX_f32_T_SCI_PosFar_PosF32_TValue(SCI_PosFar_PosF32_TValue);

  SCI_PosFar_PosF32_TValue_0 = Rte_IWriteRef_PosFar_mainFunction_PP_FarX_f32_T_SCI_PosFar_PosF32_TValue();

  Rte_IWrite_PosFar_mainFunction_PP_FarY_f32_T_SCI_PosFar_PosF32_TValue(SCI_PosFar_PosF32_TValue_1);

  SCI_PosFar_PosF32_TValue_2 = Rte_IWriteRef_PosFar_mainFunction_PP_FarY_f32_T_SCI_PosFar_PosF32_TValue();

  Rte_IWrite_PosFar_mainFunction_PP_FarT_f32_T_SCI_PosFar_PosF32_TValue(SCI_PosFar_PosF32_TValue_3);

  SCI_PosFar_PosF32_TValue_4 = Rte_IWriteRef_PosFar_mainFunction_PP_FarT_f32_T_SCI_PosFar_PosF32_TValue();

  AngleValue = Rte_IRead_PosFar_mainFunction_PosTrjOfflPosT_AngleValue();

  PositionXValue = Rte_IRead_PosFar_mainFunction_PosTrjOfflPosX_PositionXValue();

  PositionYValue = Rte_IRead_PosFar_mainFunction_PosTrjOfflPosY_PositionYValue();

  Val = Rte_IRead_PosFar_mainFunction_RP_StrAngl_Val();

  Val_0 = Rte_IRead_PosFar_mainFunction_RP_TrjE_Val();

  Val_1 = Rte_IRead_PosFar_mainFunction_PosFarActivate_Val();

  Val_2 = Rte_IRead_PosFar_mainFunction_PosFarReset_Val();

  PosDataVal = Rte_IRead_PosFar_mainFunction_RP_PosData_PosDataVal();

  status = Rte_Call_RP_PosFarError_SetErrorState(ErrorId, WSErrorState);

}

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------

  ------------------------[per instance memory API]--------------------------

*/
/** @} doxygen end group definition */
/*==================[end of file]============================================*/

