
/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains an Rte component template / example code
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Tue May 22 10:59:42 CEST 2018. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#include "Rte_SCI_Protec.h"

/*------------------------[runnable entity skeletons]------------------------*/

void Protec_10ms (void)
{
  Dem_EventStatusType EventStatus_7;
  Dem_EventStatusType EventStatus_6;
  Dem_EventStatusType EventStatus_5;
  Dem_EventStatusType EventStatus_4;
  Dem_EventStatusType EventStatus_3;
  Dem_EventStatusType EventStatus_2;
  Dem_EventStatusType EventStatus_1;
  Dem_EventStatusType EventStatus_0;
  Dem_EventStatusType EventStatus;
  boolean BoolVal;
  Voltage_s32 Voltage_0;
  Voltage_s32 Voltage;
  Current_s32 Current_3;
  Current_s32 Current_2;
  Current_s32 Current_1;
  Current_s32 Current_0;
  uint8 StatusByte;
  Period_u32 Period;
  Current_s32 Current;
  Std_ReturnType status;

  Current = Rte_IRead_Protec_10ms_WspZMovCdd_iZMovMeas_Current();

  Period = Rte_IRead_Protec_10ms_WspPfcCdd_tiGrid_Period();

  StatusByte = Rte_IRead_Protec_10ms_WspIoHwAbs_numCodRes_StatusByte();

  Current_0 = Rte_IRead_Protec_10ms_WspB6cdd_iWpcPhas1_Current();

  Current_1 = Rte_IRead_Protec_10ms_WspB6cdd_iWpcPhas2_Current();

  Current_2 = Rte_IRead_Protec_10ms_WspB6cdd_iWpcPhas3_Current();

  Current_3 = Rte_IRead_Protec_10ms_WspPfcCdd_iAcGrid_Current();

  Voltage = Rte_IRead_Protec_10ms_WspPfcCdd_uAcGrid_Voltage();

  Voltage_0 = Rte_IRead_Protec_10ms_WspPfcCdd_uBoost_Voltage();

  BoolVal = Rte_IRead_Protec_10ms_WspSafety_cmdRcdTst_BoolVal();

  status = Rte_Call_Event_BOOST_VOLTAGE_IS_TOO_HIGH_SetEventStatus(EventStatus);

  status = Rte_Call_Event_BOOST_VOLTAGE_IS_TOO_LOW_SetEventStatus(EventStatus_0);

  status = Rte_Call_Event_GRID_INPUT_CURRENT_HIGH_SetEventStatus(EventStatus_1);

  status = Rte_Call_Event_GRID_INPUT_VOLTAGE_HIGH_SetEventStatus(EventStatus_2);

  status = Rte_Call_Event_GRID_INPUT_VOLTAGE_LOW_SetEventStatus(EventStatus_3);

  status = Rte_Call_Event_PWR_GRD_FREQ_HIGH_SetEventStatus(EventStatus_4);

  status = Rte_Call_Event_PWR_GRD_FREQ_LOW_SetEventStatus(EventStatus_5);

  status = Rte_Call_Event_WPC_INPUT_POWER_HIGH_SetEventStatus(EventStatus_6);

  status = Rte_Call_Event_PWR_GRD_CURRENT_NOT_PLAUSIBLE_SetEventStatus(EventStatus_7);

}

void SCI_Protec_Protec_100ms (void)
{
  Dem_EventStatusType EventStatus_4;
  Dem_EventStatusType EventStatus_3;
  Dem_EventStatusType EventStatus_2;
  Dem_EventStatusType EventStatus_1;
  Dem_EventStatusType EventStatus_0;
  Dem_EventStatusType EventStatus;
  boolean BoolVal;
  TempC TempCVal_s16_3;
  TempC TempCVal_s16_2;
  TempC TempCVal_s16_1;
  TempC TempCVal_s16_0;
  TempC TempCVal_s16;
  ErrorCode_u32 SCI_Protec_BlueToothComFail_u32_TValue;
  Std_ReturnType status;

  SCI_Protec_BlueToothComFail_u32_TValue = Rte_IRead_Protec_100ms_WspBleCdd_stBleComFail_SCI_Protec_BlueToothComFail_u32_TValue();

  TempCVal_s16 = Rte_IRead_Protec_100ms_WspFodCan_tAmb_TempCVal_s16();

  TempCVal_s16_0 = Rte_IRead_Protec_100ms_WspIoHwAbs_tPpmAmb_TempCVal_s16();

  TempCVal_s16_1 = Rte_IRead_Protec_100ms_WspIoHwAbs_tPpmSink_TempCVal_s16();

  TempCVal_s16_2 = Rte_IRead_Protec_100ms_WspIoHwAbs_tWpmFan_TempCVal_s16();

  TempCVal_s16_3 = Rte_IRead_Protec_100ms_WspIoHwAbs_tWpmSink_TempCVal_s16();

  BoolVal = Rte_IRead_Protec_100ms_WspSafety_cmdRcdTst_BoolVal();

  status = Rte_Call_Event_B6_TEMP_HIGH_SetEventStatus(EventStatus);

  status = Rte_Call_Event_B6_TEMP_LOW_SetEventStatus(EventStatus_0);

  status = Rte_Call_Event_BOOST_TEMP_HIGH_SetEventStatus(EventStatus_1);

  status = Rte_Call_Event_BOOST_TEMP_LOW_SetEventStatus(EventStatus_2);

  status = Rte_Call_Event_FOD_OVERTEMPERATURE_SetEventStatus(EventStatus_3);

  status = Rte_Call_Event_FOD_UNDERTEMPERATURE_SetEventStatus(EventStatus_4);

}

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------

  ------------------------[per instance memory API]--------------------------

*/
/** @} doxygen end group definition */
/*==================[end of file]============================================*/

