
/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains an Rte component template / example code
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Mon Jul 17 14:20:30 CEST 2017. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#include "Rte_SCI_ComMgr.h"

/*------------------------[runnable entity skeletons]------------------------*/

void ComMgr_Rx_MainFunction (void)
{
  GenericWord SignalValue_0;
  GenericByte SignalId_0;
  GenericWord SignalValue;
  GenericByte SignalId;
  Power_u16 PowerValue;
  GenericByte SCI_ComMgr_GenericByteValue_39;
  GenericByte SCI_ComMgr_GenericByteValue_38;
  GenericWord SCI_ComMgr_GenericWordValue_2;
  GenericByte SCI_ComMgr_GenericByteValue_37;
  GenericByte SCI_ComMgr_GenericByteValue_36;
  GenericByte SCI_ComMgr_GenericByteValue_35;
  GenericByte SCI_ComMgr_GenericByteValue_34;
  GenericByte SCI_ComMgr_GenericByteValue_33;
  GenericByte SCI_ComMgr_GenericByteValue_32;
  GenericByte SCI_ComMgr_GenericByteValue_31;
  GenericByte SCI_ComMgr_GenericByteValue_30;
  GenericByte SCI_ComMgr_GenericByteValue_29;
  P2CONST(SftyBoolOO, AUTOMATIC, AUTOMATIC) SCI_ComMgr_SftyBoolValue;
  GenericByte SCI_ComMgr_GenericByteValue_28;
  GenericByte SCI_ComMgr_GenericByteValue_27;
  GenericByte SCI_ComMgr_ActStateWsValue;
  GenericByte SCI_ComMgr_GenericByteValue_26;
  GenericByte SCI_ComMgr_GenericByteValue_25;
  GenericByte SCI_ComMgr_GenericByteValue_24;
  GenericByte SCI_ComMgr_GenericByteValue_23;
  TrueFalse SCI_ComMgr_Z_MoverDownValue;
  TrueFalse SCI_ComMgr_Z_MoverUpValue;
  GenericByte SCI_ComMgr_GenericByteValue_22;
  GenericByte SCI_ComMgr_GenericByteValue_21;
  GenericByte SCI_ComMgr_GenericByteValue_20;
  AngleDegree_s16 SCI_ComMgr_AngleValue_0;
  Distance_s16 SCI_ComMgr_PositionXValue_0;
  Distance_s16 SCI_ComMgr_PositionYValue_0;
  GenericByte SCI_ComMgr_GenericByteValue_19;
  GenericByte SCI_ComMgr_GenericByteValue_18;
  GenericByte SCI_ComMgr_GenericByteValue_17;
  GenericByte SCI_ComMgr_GenericByteValue_16;
  GenericByte SCI_ComMgr_GenericByteValue_15;
  GenericByte SCI_ComMgr_GenericByteValue_14;
  GenericByte SCI_ComMgr_GenericByteValue_13;
  GenericByte SCI_ComMgr_GenericByteValue_12;
  GenericByte SCI_ComMgr_GenericByteValue_11;
  GenericByte SCI_ComMgr_GenericByteValue_10;
  GenericByte SCI_ComMgr_GenericByteValue_9;
  GenericByte SCI_ComMgr_GenericByteValue_8;
  GenericByte SCI_ComMgr_GenericByteValue_7;
  GenericByte SCI_ComMgr_GenericByteValue_6;
  GenericByte SCI_ComMgr_GenericByteValue_5;
  GenericByte SCI_ComMgr_GenericByteValue_4;
  GenericByte SCI_ComMgr_GenericByteValue_3;
  GenericWord SCI_ComMgr_GenericWordValue_1;
  GenericWord SCI_ComMgr_GenericWordValue_0;
  GenericWord SCI_ComMgr_GenericWordValue;
  GenericByte SCI_ComMgr_GenericByteValue_2;
  GenericByte SCI_ComMgr_GenericByteValue_1;
  GenericByte SCI_ComMgr_GenericByteValue_0;
  GenericByte SCI_ComMgr_GenericByteValue;
  AngleDegree_s16 SCI_ComMgr_AngleValue;
  Distance_s16 SCI_ComMgr_PositionYValue;
  Distance_s16 SCI_ComMgr_PositionXValue;
  Std_ReturnType status;

  SCI_ComMgr_PositionXValue = Rte_IRead_ComMgr_Rx_MainFunction_RP_Panel_PositionX_SCI_ComMgr_PositionXValue();

  SCI_ComMgr_PositionYValue = Rte_IRead_ComMgr_Rx_MainFunction_RP_Panel_PositionY_SCI_ComMgr_PositionYValue();

  SCI_ComMgr_AngleValue = Rte_IRead_ComMgr_Rx_MainFunction_RP_Panel_Verdrehwinkel_SCI_ComMgr_AngleValue();

  SCI_ComMgr_GenericByteValue = Rte_IRead_ComMgr_Rx_MainFunction_RP_Feldgroesse_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_0 = Rte_IRead_ComMgr_Rx_MainFunction_RP_Kopplungsfaktor_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_1 = Rte_IRead_ComMgr_Rx_MainFunction_RP_DutyCycle2_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_2 = Rte_IRead_ComMgr_Rx_MainFunction_RP_DutyCycle1_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericWordValue = Rte_IRead_ComMgr_Rx_MainFunction_RP_Out_DCVol_Boost_SCI_ComMgr_GenericWordValue();

  SCI_ComMgr_GenericWordValue_0 = Rte_IRead_ComMgr_Rx_MainFunction_RP_Out_DCCurr_Buck_SCI_ComMgr_GenericWordValue();

  SCI_ComMgr_GenericWordValue_1 = Rte_IRead_ComMgr_Rx_MainFunction_RP_Out_DCCur_Boost_SCI_ComMgr_GenericWordValue();

  SCI_ComMgr_GenericByteValue_3 = Rte_IRead_ComMgr_Rx_MainFunction_RP_FehStromausfall_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_4 = Rte_IRead_ComMgr_Rx_MainFunction_RP_ErrorEarthing_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_5 = Rte_IRead_ComMgr_Rx_MainFunction_RP_DerTempMosfet_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_6 = Rte_IRead_ComMgr_Rx_MainFunction_RP_DerTempCoil_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_7 = Rte_IRead_ComMgr_Rx_MainFunction_RP_DerTempCaps_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_8 = Rte_IRead_ComMgr_Rx_MainFunction_RP_DeratngLowACVol_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_9 = Rte_IRead_ComMgr_Rx_MainFunction_RP_ErrGridVoltLow_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_10 = Rte_IRead_ComMgr_Rx_MainFunction_RP_ErrGridVoltHigh_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_11 = Rte_IRead_ComMgr_Rx_MainFunction_RP_ErrEarthingCurr_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_12 = Rte_IRead_ComMgr_Rx_MainFunction_RP_FehUeberspanung_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_13 = Rte_IRead_ComMgr_Rx_MainFunction_RP_FehUnterspanung_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_14 = Rte_IRead_ComMgr_Rx_MainFunction_RP_FehTempMosfet_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_15 = Rte_IRead_ComMgr_Rx_MainFunction_RP_FehlerUeberlast_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_16 = Rte_IRead_ComMgr_Rx_MainFunction_RP_FehlerTempCoil_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_17 = Rte_IRead_ComMgr_Rx_MainFunction_RP_FehlerTempCaps_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_18 = Rte_IRead_ComMgr_Rx_MainFunction_RP_FehCANTimeout_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_19 = Rte_IRead_ComMgr_Rx_MainFunction_RP_PosRel_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_PositionYValue_0 = Rte_IRead_ComMgr_Rx_MainFunction_RP_Y_Coordinate_SCI_ComMgr_PositionYValue();

  SCI_ComMgr_PositionXValue_0 = Rte_IRead_ComMgr_Rx_MainFunction_RP_X_Coordinate_SCI_ComMgr_PositionXValue();

  SCI_ComMgr_AngleValue_0 = Rte_IRead_ComMgr_Rx_MainFunction_RP_BAP_AWC_Winkel_SCI_ComMgr_AngleValue();

  SCI_ComMgr_GenericByteValue_20 = Rte_IRead_ComMgr_Rx_MainFunction_RP_Panel_State_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_21 = Rte_IRead_ComMgr_Rx_MainFunction_RP_zMovrIsChargPos_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_22 = Rte_IRead_ComMgr_Rx_MainFunction_RP_zMoverLocked_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_Z_MoverUpValue = Rte_IRead_ComMgr_Rx_MainFunction_RP_zMoverIsUp_SCI_ComMgr_Z_MoverUpValue();

  SCI_ComMgr_Z_MoverDownValue = Rte_IRead_ComMgr_Rx_MainFunction_RP_zMoverIsDown_SCI_ComMgr_Z_MoverDownValue();

  SCI_ComMgr_GenericByteValue_23 = Rte_IRead_ComMgr_Rx_MainFunction_RP_zMoverActive_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_24 = Rte_IRead_ComMgr_Rx_MainFunction_RP_Z_soll_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_25 = Rte_IRead_ComMgr_Rx_MainFunction_RP_Z_ist_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_26 = Rte_IRead_ComMgr_Rx_MainFunction_RP_Verz_Temp_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_ActStateWsValue = Rte_IRead_ComMgr_Rx_MainFunction_RP_WSD_State_SCI_ComMgr_ActStateWsValue();

  SCI_ComMgr_GenericByteValue_27 = Rte_IRead_ComMgr_Rx_MainFunction_RP_Verz_zMover_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_28 = Rte_IRead_ComMgr_Rx_MainFunction_RP_Verz_LOP_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_SftyBoolValue = Rte_IRead_ComMgr_Rx_MainFunction_RP_Verz_FOD_SCI_ComMgr_SftyBoolValue();

  SCI_ComMgr_GenericByteValue_29 = Rte_IRead_ComMgr_Rx_MainFunction_RP_Fehler_zMover_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_30 = Rte_IRead_ComMgr_Rx_MainFunction_RP_Fehler_LOP_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_31 = Rte_IRead_ComMgr_Rx_MainFunction_RP_Fehler_FOD_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_32 = Rte_IRead_ComMgr_Rx_MainFunction_RP_Fehler_Komm_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_33 = Rte_IRead_ComMgr_Rx_MainFunction_RP_DerTempWsLow_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_34 = Rte_IRead_ComMgr_Rx_MainFunction_RP_DerTempWsHigh_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_35 = Rte_IRead_ComMgr_Rx_MainFunction_RP_DerObUIOutput_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_36 = Rte_IRead_ComMgr_Rx_MainFunction_RP_ChrgrEfficiency_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_37 = Rte_IRead_ComMgr_Rx_MainFunction_RP_DeratingRate_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericWordValue_2 = Rte_IRead_ComMgr_Rx_MainFunction_RP_AC_Istspannung_SCI_ComMgr_GenericWordValue();

  SCI_ComMgr_GenericByteValue_38 = Rte_IRead_ComMgr_Rx_MainFunction_RP_AC_Iststrom_SCI_ComMgr_GenericByteValue();

  SCI_ComMgr_GenericByteValue_39 = Rte_IRead_ComMgr_Rx_MainFunction_RP_WsSftyMgr_State_SCI_ComMgr_GenericByteValue();

  PowerValue = Rte_IRead_ComMgr_Rx_MainFunction_RP_MaxLadLeistung_PowerValue();

  status = Rte_Call_RP_BleCom_Read(SignalId, &SignalValue);

  status = Rte_Call_RP_BleCom_Write(SignalId_0, SignalValue_0);

}

void ComMgr_Tx_MainFunction (void)
{
  GenericWord SignalValue_0;
  GenericByte SignalId_0;
  GenericWord SignalValue;
  GenericByte SignalId;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_62;
  GenericByte SCI_ComMgr_GenericByteValue_61;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_60;
  GenericByte SCI_ComMgr_GenericByteValue_59;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_58;
  GenericByte SCI_ComMgr_GenericByteValue_57;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_56;
  GenericByte SCI_ComMgr_GenericByteValue_55;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_54;
  GenericByte SCI_ComMgr_GenericByteValue_53;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_52;
  GenericByte SCI_ComMgr_GenericByteValue_51;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_50;
  GenericByte SCI_ComMgr_GenericByteValue_49;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_48;
  GenericByte SCI_ComMgr_GenericByteValue_47;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_46;
  GenericByte SCI_ComMgr_GenericByteValue_45;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_44;
  GenericByte SCI_ComMgr_GenericByteValue_43;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_42;
  GenericByte SCI_ComMgr_GenericByteValue_41;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_40;
  GenericByte SCI_ComMgr_GenericByteValue_39;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_38;
  GenericByte SCI_ComMgr_GenericByteValue_37;
  P2VAR(GenericWord, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericWordValue_20;
  GenericWord SCI_ComMgr_GenericWordValue_19;
  P2VAR(GenericWord, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericWordValue_18;
  GenericWord SCI_ComMgr_GenericWordValue_17;
  P2VAR(GenericWord, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericWordValue_16;
  GenericWord SCI_ComMgr_GenericWordValue_15;
  P2VAR(GenericWord, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericWordValue_14;
  GenericWord SCI_ComMgr_GenericWordValue_13;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_36;
  GenericByte SCI_ComMgr_GenericByteValue_35;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_34;
  GenericByte SCI_ComMgr_GenericByteValue_33;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_32;
  GenericByte SCI_ComMgr_GenericByteValue_31;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_30;
  GenericByte SCI_ComMgr_GenericByteValue_29;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_28;
  GenericByte SCI_ComMgr_GenericByteValue_27;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_26;
  GenericByte SCI_ComMgr_GenericByteValue_25;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_24;
  GenericByte SCI_ComMgr_GenericByteValue_23;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_22;
  GenericByte SCI_ComMgr_GenericByteValue_21;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_20;
  GenericByte SCI_ComMgr_GenericByteValue_19;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_18;
  GenericByte SCI_ComMgr_GenericByteValue_17;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_16;
  GenericByte SCI_ComMgr_GenericByteValue_15;
  P2VAR(Current_s32, AUTOMATIC, AUTOMATIC) SCI_ComMgr_Measured_charging_current_s32_TValue_0;
  Current_s32 SCI_ComMgr_Measured_charging_current_s32_TValue;
  P2VAR(Current_s32, AUTOMATIC, AUTOMATIC) SCI_ComMgr_Requested_charging_current_s32_TValue_0;
  Current_s32 SCI_ComMgr_Requested_charging_current_s32_TValue;
  P2VAR(Voltage_s32, AUTOMATIC, AUTOMATIC) SCI_ComMgr_Measured_oru_hv_ac_in_s32_TValue_0;
  Voltage_s32 SCI_ComMgr_Measured_oru_hv_ac_in_s32_TValue;
  P2VAR(Voltage_s32, AUTOMATIC, AUTOMATIC) SCI_ComMgr_Measured_oru_hv_dc_out_s32_TValue_0;
  Voltage_s32 SCI_ComMgr_Measured_oru_hv_dc_out_s32_TValue;
  P2VAR(Voltage_s32, AUTOMATIC, AUTOMATIC) SCI_ComMgr_Maximum_battery_voltage_s32_TValue_0;
  Voltage_s32 SCI_ComMgr_Maximum_battery_voltage_s32_TValue;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_14;
  GenericByte SCI_ComMgr_GenericByteValue_13;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_12;
  GenericByte SCI_ComMgr_GenericByteValue_11;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_10;
  GenericByte SCI_ComMgr_GenericByteValue_9;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_8;
  GenericByte SCI_ComMgr_GenericByteValue_7;
  P2VAR(GenericWord, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericWordValue_12;
  GenericWord SCI_ComMgr_GenericWordValue_11;
  P2VAR(GenericWord, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericWordValue_10;
  GenericWord SCI_ComMgr_GenericWordValue_9;
  P2VAR(GenericWord, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericWordValue_8;
  GenericWord SCI_ComMgr_GenericWordValue_7;
  P2VAR(GenericWord, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericWordValue_6;
  GenericWord SCI_ComMgr_GenericWordValue_5;
  P2VAR(GenericWord, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericWordValue_4;
  GenericWord SCI_ComMgr_GenericWordValue_3;
  P2VAR(GenericWord, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericWordValue_2;
  GenericWord SCI_ComMgr_GenericWordValue_1;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_6;
  GenericByte SCI_ComMgr_GenericByteValue_5;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_4;
  GenericByte SCI_ComMgr_GenericByteValue_3;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_2;
  GenericByte SCI_ComMgr_GenericByteValue_1;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericByteValue_0;
  GenericByte SCI_ComMgr_GenericByteValue;
  P2VAR(GenericWord, AUTOMATIC, AUTOMATIC) SCI_ComMgr_GenericWordValue_0;
  GenericWord SCI_ComMgr_GenericWordValue;
  Std_ReturnType status;

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_EPS_Zahnstangen_Pos_SCI_ComMgr_GenericWordValue(SCI_ComMgr_GenericWordValue);

  SCI_ComMgr_GenericWordValue_0 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_EPS_Zahnstangen_Pos_SCI_ComMgr_GenericWordValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_EPS_VZ_Zahnstangenposition_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue);

  SCI_ComMgr_GenericByteValue_0 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_EPS_VZ_Zahnstangenposition_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_EPS_QBit_Zahnstangen_Pos_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_1);

  SCI_ComMgr_GenericByteValue_2 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_EPS_QBit_Zahnstangen_Pos_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_HAL_VZ_Radwinkel_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_3);

  SCI_ComMgr_GenericByteValue_4 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_HAL_VZ_Radwinkel_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_HAL_QBit_Radwinkel_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_5);

  SCI_ComMgr_GenericByteValue_6 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_HAL_QBit_Radwinkel_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_HAL_Radwinkel_SCI_ComMgr_GenericWordValue(SCI_ComMgr_GenericWordValue_1);

  SCI_ComMgr_GenericWordValue_2 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_HAL_Radwinkel_SCI_ComMgr_GenericWordValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_ESP_Wegimpuls_VL_SCI_ComMgr_GenericWordValue(SCI_ComMgr_GenericWordValue_3);

  SCI_ComMgr_GenericWordValue_4 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_ESP_Wegimpuls_VL_SCI_ComMgr_GenericWordValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_ESP_Wegimpuls_VR_SCI_ComMgr_GenericWordValue(SCI_ComMgr_GenericWordValue_5);

  SCI_ComMgr_GenericWordValue_6 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_ESP_Wegimpuls_VR_SCI_ComMgr_GenericWordValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_ESP_Wegimpuls_HL_SCI_ComMgr_GenericWordValue(SCI_ComMgr_GenericWordValue_7);

  SCI_ComMgr_GenericWordValue_8 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_ESP_Wegimpuls_HL_SCI_ComMgr_GenericWordValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_ESP_Wegimpuls_HR_SCI_ComMgr_GenericWordValue(SCI_ComMgr_GenericWordValue_9);

  SCI_ComMgr_GenericWordValue_10 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_ESP_Wegimpuls_HR_SCI_ComMgr_GenericWordValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_BR_Reifenumfang_SCI_ComMgr_GenericWordValue(SCI_ComMgr_GenericWordValue_11);

  SCI_ComMgr_GenericWordValue_12 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_BR_Reifenumfang_SCI_ComMgr_GenericWordValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_Abregelung_Temperatur_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_7);

  SCI_ComMgr_GenericByteValue_8 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_Abregelung_Temperatur_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_Temperatur_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_9);

  SCI_ComMgr_GenericByteValue_10 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_Temperatur_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_AB_Deaktivierung_HV_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_11);

  SCI_ComMgr_GenericByteValue_12 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_AB_Deaktivierung_HV_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_CmdWSDStateMachine_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_13);

  SCI_ComMgr_GenericByteValue_14 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_CmdWSDStateMachine_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_U_DC_MAX_ORU_SCI_ComMgr_Maximum_battery_voltage_s32_TValue(SCI_ComMgr_Maximum_battery_voltage_s32_TValue);

  SCI_ComMgr_Maximum_battery_voltage_s32_TValue_0 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_U_DC_MAX_ORU_SCI_ComMgr_Maximum_battery_voltage_s32_TValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_U_DC_ACT_ORU_SCI_ComMgr_Measured_oru_hv_dc_out_s32_TValue(SCI_ComMgr_Measured_oru_hv_dc_out_s32_TValue);

  SCI_ComMgr_Measured_oru_hv_dc_out_s32_TValue_0 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_U_DC_ACT_ORU_SCI_ComMgr_Measured_oru_hv_dc_out_s32_TValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_U_AC_ACT_ORU_SCI_ComMgr_Measured_oru_hv_ac_in_s32_TValue(SCI_ComMgr_Measured_oru_hv_ac_in_s32_TValue);

  SCI_ComMgr_Measured_oru_hv_ac_in_s32_TValue_0 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_U_AC_ACT_ORU_SCI_ComMgr_Measured_oru_hv_ac_in_s32_TValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_I_DC_REQ_ORU_SCI_ComMgr_Requested_charging_current_s32_TValue(SCI_ComMgr_Requested_charging_current_s32_TValue);

  SCI_ComMgr_Requested_charging_current_s32_TValue_0 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_I_DC_REQ_ORU_SCI_ComMgr_Requested_charging_current_s32_TValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_I_DC_ACT_ORU_SCI_ComMgr_Measured_charging_current_s32_TValue(SCI_ComMgr_Measured_charging_current_s32_TValue);

  SCI_ComMgr_Measured_charging_current_s32_TValue_0 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_I_DC_ACT_ORU_SCI_ComMgr_Measured_charging_current_s32_TValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_Poshilfe_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_15);

  SCI_ComMgr_GenericByteValue_16 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_Poshilfe_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_Status_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_17);

  SCI_ComMgr_GenericByteValue_18 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_Status_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_BMS_IstModus_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_19);

  SCI_ComMgr_GenericByteValue_20 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_BMS_IstModus_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_ReqzMoverOnly_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_21);

  SCI_ComMgr_GenericByteValue_22 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_ReqzMoverOnly_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_HVLM_AWC_Sollmodus_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_23);

  SCI_ComMgr_GenericByteValue_24 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_HVLM_AWC_Sollmodus_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_HVLM_Zustand_LED_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_25);

  SCI_ComMgr_GenericByteValue_26 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_HVLM_Zustand_LED_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_St_Spgfreiheit_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_27);

  SCI_ComMgr_GenericByteValue_28 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_St_Spgfreiheit_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_DerTempObLow_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_29);

  SCI_ComMgr_GenericByteValue_30 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_DerTempObLow_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_DerTempObHigh_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_31);

  SCI_ComMgr_GenericByteValue_32 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_DerTempObHigh_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_Fehlerstatus_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_33);

  SCI_ComMgr_GenericByteValue_34 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_Fehlerstatus_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_BMS_Fehlerstatus_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_35);

  SCI_ComMgr_GenericByteValue_36 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_BMS_Fehlerstatus_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_IstSpannung_SCI_ComMgr_GenericWordValue(SCI_ComMgr_GenericWordValue_13);

  SCI_ComMgr_GenericWordValue_14 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_IstSpannung_SCI_ComMgr_GenericWordValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_IstStrom_SCI_ComMgr_GenericWordValue(SCI_ComMgr_GenericWordValue_15);

  SCI_ComMgr_GenericWordValue_16 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_IstStrom_SCI_ComMgr_GenericWordValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_BMS_Max_LSpannung_SCI_ComMgr_GenericWordValue(SCI_ComMgr_GenericWordValue_17);

  SCI_ComMgr_GenericWordValue_18 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_BMS_Max_LSpannung_SCI_ComMgr_GenericWordValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_HVLM_AWC_Sollstrom_SCI_ComMgr_GenericWordValue(SCI_ComMgr_GenericWordValue_19);

  SCI_ComMgr_GenericWordValue_20 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_HVLM_AWC_Sollstrom_SCI_ComMgr_GenericWordValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_EVCCID_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_37);

  SCI_ComMgr_GenericByteValue_38 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_EVCCID_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_UH_Tag_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_39);

  SCI_ComMgr_GenericByteValue_40 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_UH_Tag_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_UH_Stunde_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_41);

  SCI_ComMgr_GenericByteValue_42 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_UH_Stunde_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_UH_Sekunde_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_43);

  SCI_ComMgr_GenericByteValue_44 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_UH_Sekunde_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_UH_Monat_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_45);

  SCI_ComMgr_GenericByteValue_46 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_UH_Monat_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_UH_Minute_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_47);

  SCI_ComMgr_GenericByteValue_48 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_UH_Minute_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_UH_Jahr_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_49);

  SCI_ComMgr_GenericByteValue_50 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_UH_Jahr_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_DGN_Verlernzaehler_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_51);

  SCI_ComMgr_GenericByteValue_52 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_DGN_Verlernzaehler_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_FA_Hoehenwert_VR_00_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_53);

  SCI_ComMgr_GenericByteValue_54 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_FA_Hoehenwert_VR_00_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_FA_Hoehenwert_VL_00_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_55);

  SCI_ComMgr_GenericByteValue_56 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_FA_Hoehenwert_VL_00_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_FA_Hoehenwert_HR_00_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_57);

  SCI_ComMgr_GenericByteValue_58 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_FA_Hoehenwert_HR_00_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_FA_Hoehenwert_HL_00_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_59);

  SCI_ComMgr_GenericByteValue_60 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_FA_Hoehenwert_HL_00_SCI_ComMgr_GenericByteValue();

  Rte_IWrite_ComMgr_Tx_MainFunction_PP_OruSftyMgr_State_SCI_ComMgr_GenericByteValue(SCI_ComMgr_GenericByteValue_61);

  SCI_ComMgr_GenericByteValue_62 = Rte_IWriteRef_ComMgr_Tx_MainFunction_PP_OruSftyMgr_State_SCI_ComMgr_GenericByteValue();

  status = Rte_Call_RP_BleCom_Read(SignalId, &SignalValue);

  status = Rte_Call_RP_BleCom_Write(SignalId_0, SignalValue_0);

}

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------

  ------------------------[per instance memory API]--------------------------

*/
/** @} doxygen end group definition */
/*==================[end of file]============================================*/

