
/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains an Rte component template / example code
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Wed Jul 26 11:00:29 CEST 2017. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#include "Rte_SCI_PosNear.h"

/*------------------------[runnable entity skeletons]------------------------*/

void PosNear_MainFunction (void)
{
  ErrorState WSErrorState;
  uint16 ErrorId;
  P2CONST(PosDataV40, AUTOMATIC, AUTOMATIC) PosDataVal;
  P2VAR(PosF32, AUTOMATIC, AUTOMATIC) SCI_PosNear_PosF32_TValue_4;
  PosF32 SCI_PosNear_PosF32_TValue_3;
  P2VAR(PosF32, AUTOMATIC, AUTOMATIC) SCI_PosNear_PosF32_TValue_2;
  PosF32 SCI_PosNear_PosF32_TValue_1;
  P2VAR(PosF32, AUTOMATIC, AUTOMATIC) SCI_PosNear_PosF32_TValue_0;
  PosF32 SCI_PosNear_PosF32_TValue;
  Std_ReturnType status;

  Rte_IWrite_PosNear_MainFunction_PP_NearX_f32_T_SCI_PosNear_PosF32_TValue(SCI_PosNear_PosF32_TValue);

  SCI_PosNear_PosF32_TValue_0 = Rte_IWriteRef_PosNear_MainFunction_PP_NearX_f32_T_SCI_PosNear_PosF32_TValue();

  Rte_IWrite_PosNear_MainFunction_PP_NearY_f32_T_SCI_PosNear_PosF32_TValue(SCI_PosNear_PosF32_TValue_1);

  SCI_PosNear_PosF32_TValue_2 = Rte_IWriteRef_PosNear_MainFunction_PP_NearY_f32_T_SCI_PosNear_PosF32_TValue();

  Rte_IWrite_PosNear_MainFunction_PP_NearT_f32_T_SCI_PosNear_PosF32_TValue(SCI_PosNear_PosF32_TValue_3);

  SCI_PosNear_PosF32_TValue_4 = Rte_IWriteRef_PosNear_MainFunction_PP_NearT_f32_T_SCI_PosNear_PosF32_TValue();

  PosDataVal = Rte_IRead_PosNear_MainFunction_RP_PosData_PosDataVal();

  status = Rte_Call_RP_PosNearError_SetErrorState(ErrorId, WSErrorState);

}

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------

  ------------------------[per instance memory API]--------------------------

*/
/** @} doxygen end group definition */
/*==================[end of file]============================================*/

