
/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains an Rte component template / example code
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Tue May 22 10:59:43 CEST 2018. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#include "Rte_SCI_WsSafety.h"

/*------------------------[runnable entity skeletons]------------------------*/

void Sfty_MainFunction (void)
{
  Dem_EventStatusType EventStatus;
  WdgM_CheckpointIdType CheckpointId;
  boolean EventFailed;
  boolean BoolVal_1;
  Distance_s32 Y;
  Distance_s32 X;
  TempC TempCVal_s16_4;
  TempC TempCVal_s16_3;
  TempC TempCVal_s16_2;
  ZMoverPos ZMoverPositionVal;
  Rpm_s16 ZMoverMotSpeedVal;
  Current_s32 Current;
  TempC TempCVal_s16_1;
  TempC TempCVal_s16_0;
  TempC TempCVal_s16;
  P2CONST(SftyBoolTF, AUTOMATIC, AUTOMATIC) SftyBoolValue_3;
  P2CONST(SftyBoolTF, AUTOMATIC, AUTOMATIC) SftyBoolValue_2;
  P2CONST(SftyBoolTF, AUTOMATIC, AUTOMATIC) SftyBoolValue_1;
  P2CONST(SftyBoolTF, AUTOMATIC, AUTOMATIC) SftyBoolValue_0;
  P2CONST(SftyBoolTF, AUTOMATIC, AUTOMATIC) SftyBoolValue;
  P2CONST(SftyBoolOO, AUTOMATIC, AUTOMATIC) SCI_WsSafety_SftyOnOffValue_2;
  GenericByte SCI_WsSafety_SelftestIn_u8_TValue_1;
  P2CONST(PosTxPlausiData, AUTOMATIC, AUTOMATIC) SCI_WsSafety_PosTxPlausiDataValue;
  P2CONST(SftyBoolED, AUTOMATIC, AUTOMATIC) SCI_WsSafety_SftyEnableDisableValue_4;
  P2CONST(SftyBoolOO, AUTOMATIC, AUTOMATIC) SCI_WsSafety_SftyOnOffValue_1;
  P2CONST(SftyBoolED, AUTOMATIC, AUTOMATIC) SCI_WsSafety_SftyEnableDisableValue_3;
  GenericByte SCI_WsSafety_OruSftyMgrState_u8_TValue;
  GenericByte SCI_WsSafety_ActStateWsValue;
  P2VAR(boolean, AUTOMATIC, AUTOMATIC) BoolVal_0;
  boolean BoolVal;
  P2VAR(PP_Verz_FOD, AUTOMATIC, AUTOMATIC) Value_0;
  PP_Verz_FOD Value;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_WsSafety_SelftestIn_u8_TValue_0;
  GenericByte SCI_WsSafety_SelftestIn_u8_TValue;
  P2VAR(SftyBoolED, AUTOMATIC, AUTOMATIC) SCI_WsSafety_SftyEnableDisableValue_2;
  SftyBoolED SCI_WsSafety_SftyEnableDisableValue_1;
  P2VAR(SftyBoolOO, AUTOMATIC, AUTOMATIC) SCI_WsSafety_SftyOnOffValue_0;
  SftyBoolOO SCI_WsSafety_SftyOnOffValue;
  P2VAR(SftyBoolED, AUTOMATIC, AUTOMATIC) SCI_WsSafety_SftyEnableDisableValue_0;
  SftyBoolED SCI_WsSafety_SftyEnableDisableValue;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_WsSafety_SftyMgrState_u8_TValue_0;
  GenericByte SCI_WsSafety_SftyMgrState_u8_TValue;
  SftyErrorState ErrorStateSafety_struct_u32;
  uint8 WspSafetyTempState;
  uint8 WspSafetyPosState;
  uint8 WspSafetyPinchState;
  Std_ReturnType status;

  WspSafetyPinchState = Rte_IrvIRead_Sfty_MainFunction_WspSafetyPinchState();

  WspSafetyPosState = Rte_IrvIRead_Sfty_MainFunction_WspSafetyPosState();

  WspSafetyTempState = Rte_IrvIRead_Sfty_MainFunction_WspSafetyTempState();

  Rte_IrvWrite_Sfty_MainFunction_ErrorStateSafety_struct_u32(&ErrorStateSafety_struct_u32);

  Rte_IWrite_Sfty_MainFunction_PP_SftyMgrState_u8_T_SCI_WsSafety_SftyMgrState_u8_TValue(SCI_WsSafety_SftyMgrState_u8_TValue);

  SCI_WsSafety_SftyMgrState_u8_TValue_0 = Rte_IWriteRef_Sfty_MainFunction_PP_SftyMgrState_u8_T_SCI_WsSafety_SftyMgrState_u8_TValue();

  Rte_IWrite_Sfty_MainFunction_PP_WS_Disable_u8_T_SCI_WsSafety_SftyEnableDisableValue(&SCI_WsSafety_SftyEnableDisableValue);

  SCI_WsSafety_SftyEnableDisableValue_0 = Rte_IWriteRef_Sfty_MainFunction_PP_WS_Disable_u8_T_SCI_WsSafety_SftyEnableDisableValue();

  Rte_IWrite_Sfty_MainFunction_PP_ASCReset_u8_T_SCI_WsSafety_SftyOnOffValue(&SCI_WsSafety_SftyOnOffValue);

  SCI_WsSafety_SftyOnOffValue_0 = Rte_IWriteRef_Sfty_MainFunction_PP_ASCReset_u8_T_SCI_WsSafety_SftyOnOffValue();

  Rte_IWrite_Sfty_MainFunction_PP_Z_Mover_Ena_u1_T_SCI_WsSafety_SftyEnableDisableValue(&SCI_WsSafety_SftyEnableDisableValue_1);

  SCI_WsSafety_SftyEnableDisableValue_2 = Rte_IWriteRef_Sfty_MainFunction_PP_Z_Mover_Ena_u1_T_SCI_WsSafety_SftyEnableDisableValue();

  Rte_IWrite_Sfty_MainFunction_PP_SelfTestOut_u8_T_SCI_WsSafety_SelftestIn_u8_TValue(SCI_WsSafety_SelftestIn_u8_TValue);

  SCI_WsSafety_SelftestIn_u8_TValue_0 = Rte_IWriteRef_Sfty_MainFunction_PP_SelfTestOut_u8_T_SCI_WsSafety_SelftestIn_u8_TValue();

  Rte_IWrite_Sfty_MainFunction_PP_Verz_FOD_Value(Value);

  Value_0 = Rte_IWriteRef_Sfty_MainFunction_PP_Verz_FOD_Value();

  Rte_IWrite_Sfty_MainFunction_WspSafety_cmdRcdTst_BoolVal(BoolVal);

  BoolVal_0 = Rte_IWriteRef_Sfty_MainFunction_WspSafety_cmdRcdTst_BoolVal();

  SCI_WsSafety_ActStateWsValue = Rte_IRead_Sfty_MainFunction_RP_SysMgrMode_u8_T_SCI_WsSafety_ActStateWsValue();

  SCI_WsSafety_OruSftyMgrState_u8_TValue = Rte_IRead_Sfty_MainFunction_RP_OruSftyMgrState_u8_T_SCI_WsSafety_OruSftyMgrState_u8_TValue();

  SCI_WsSafety_SftyEnableDisableValue_3 = Rte_IRead_Sfty_MainFunction_RP_WS_DisableState_u8_T_SCI_WsSafety_SftyEnableDisableValue();

  SCI_WsSafety_SftyOnOffValue_1 = Rte_IRead_Sfty_MainFunction_RP_ObjectDetectState_u8_T_SCI_WsSafety_SftyOnOffValue();

  SCI_WsSafety_SftyEnableDisableValue_4 = Rte_IRead_Sfty_MainFunction_RP_ASC_DetectState_u8_T_SCI_WsSafety_SftyEnableDisableValue();

  SCI_WsSafety_PosTxPlausiDataValue = Rte_IRead_Sfty_MainFunction_RP_POS_SC_State_u8_T_SCI_WsSafety_PosTxPlausiDataValue();

  SCI_WsSafety_SelftestIn_u8_TValue_1 = Rte_IRead_Sfty_MainFunction_RP_SelftestIn_u8_T_SCI_WsSafety_SelftestIn_u8_TValue();

  SCI_WsSafety_SftyOnOffValue_2 = Rte_IRead_Sfty_MainFunction_RP_VD_Status_SCI_WsSafety_SftyOnOffValue();

  SftyBoolValue = Rte_IRead_Sfty_MainFunction_RP_FodCheckDuringChrg_SftyBoolValue();

  SftyBoolValue_0 = Rte_IRead_Sfty_MainFunction_RP_FodCheckStartUpChrg_SftyBoolValue();

  SftyBoolValue_1 = Rte_IRead_Sfty_MainFunction_RP_FodCheckZMDown_SftyBoolValue();

  SftyBoolValue_2 = Rte_IRead_Sfty_MainFunction_RP_FodCheckZMUp_SftyBoolValue();

  SftyBoolValue_3 = Rte_IRead_Sfty_MainFunction_RP_FodPreCheck_SftyBoolValue();

  TempCVal_s16 = Rte_IRead_Sfty_MainFunction_FodCanAmbTemp_TempCVal_s16();

  TempCVal_s16_0 = Rte_IRead_Sfty_MainFunction_PpmAmbTemp_TempCVal_s16();

  TempCVal_s16_1 = Rte_IRead_Sfty_MainFunction_PpmSinkTemp_TempCVal_s16();

  Current = Rte_IRead_Sfty_MainFunction_RP_WspZMoverCurrent_Current();

  ZMoverMotSpeedVal = Rte_IRead_Sfty_MainFunction_RP_WspZMoverMotSpeed_ZMoverMotSpeedVal();

  ZMoverPositionVal = Rte_IRead_Sfty_MainFunction_RP_WspZMoverPosition_ZMoverPositionVal();

  TempCVal_s16_2 = Rte_IRead_Sfty_MainFunction_WpmAmbTemp_TempCVal_s16();

  TempCVal_s16_3 = Rte_IRead_Sfty_MainFunction_WpmFanTemp_TempCVal_s16();

  TempCVal_s16_4 = Rte_IRead_Sfty_MainFunction_WpmSinkTemp_TempCVal_s16();

  X = Rte_IRead_Sfty_MainFunction_WspPosMgr_posActual_X();

  Y = Rte_IRead_Sfty_MainFunction_WspPosMgr_posActual_Y();

  BoolVal_1 = Rte_IRead_Sfty_MainFunction_WspBleCdd_stRcdTstDone_BoolVal();

  status = Rte_Call_Event_PINCH_PROTECTION_WAS_ACTIVE_GetEventFailed(&EventFailed);

  status = Rte_Call_alive_WdgMSvEnt_SftyMain_CheckpointReached(CheckpointId);

  status = Rte_Call_alive_WdgMSvEnt_SftyMain_UpdateAliveCounter();

  status = Rte_Call_Event_WPC_ASC_ACTIVE_PAD_SetEventStatus(EventStatus);

}

void SCI_WsSafety_WspSafetyCalc (void)
{
  WdgM_CheckpointIdType CheckpointId;
  Dem_EventStatusType EventStatus_0;
  Dem_EventStatusType EventStatus;
  TempC TempCVal_s16_4;
  TempC TempCVal_s16_3;
  TempC TempCVal_s16_2;
  ZMoverPos ZMoverPositionVal;
  Rpm_s16 ZMoverMotSpeedVal;
  Current_s32 Current;
  P2CONST(SftyBoolED, AUTOMATIC, AUTOMATIC) SCI_WsSafety_SftyEnableDisableValue_0;
  P2CONST(SftyBoolOO, AUTOMATIC, AUTOMATIC) SCI_WsSafety_SftyOnOffValue_0;
  GenericByte SCI_WsSafety_ActStateWsValue;
  GenericByte SCI_WsSafety_SelftestIn_u8_TValue;
  GenericByte SCI_WsSafety_OruSftyMgrState_u8_TValue;
  P2CONST(SftyBoolOO, AUTOMATIC, AUTOMATIC) SCI_WsSafety_SftyOnOffValue;
  P2CONST(SftyBoolED, AUTOMATIC, AUTOMATIC) SCI_WsSafety_SftyEnableDisableValue;
  TempC TempCVal_s16_1;
  TempC TempCVal_s16_0;
  TempC TempCVal_s16;
  P2CONST(SftyBoolTF, AUTOMATIC, AUTOMATIC) SftyBoolValue_3;
  P2CONST(SftyBoolTF, AUTOMATIC, AUTOMATIC) SftyBoolValue_2;
  P2CONST(SftyBoolTF, AUTOMATIC, AUTOMATIC) SftyBoolValue_1;
  P2CONST(SftyBoolTF, AUTOMATIC, AUTOMATIC) SftyBoolValue_0;
  P2CONST(SftyBoolTF, AUTOMATIC, AUTOMATIC) SftyBoolValue;
  P2CONST(PosTxPlausiData, AUTOMATIC, AUTOMATIC) SCI_WsSafety_PosTxPlausiDataValue;
  uint8 WspSafetyTempState;
  uint8 WspSafetyPosState;
  Std_ReturnType status;

  Rte_IrvIWrite_WspSafetyCalc_WspSafetyPosState(WspSafetyPosState);

  Rte_IrvIWrite_WspSafetyCalc_WspSafetyTempState(WspSafetyTempState);

  SCI_WsSafety_PosTxPlausiDataValue = Rte_IRead_WspSafetyCalc_RP_POS_SC_State_u8_T_SCI_WsSafety_PosTxPlausiDataValue();

  SftyBoolValue = Rte_IRead_WspSafetyCalc_RP_FodCheckDuringChrg_SftyBoolValue();

  SftyBoolValue_0 = Rte_IRead_WspSafetyCalc_RP_FodCheckStartUpChrg_SftyBoolValue();

  SftyBoolValue_1 = Rte_IRead_WspSafetyCalc_RP_FodCheckZMDown_SftyBoolValue();

  SftyBoolValue_2 = Rte_IRead_WspSafetyCalc_RP_FodCheckZMUp_SftyBoolValue();

  SftyBoolValue_3 = Rte_IRead_WspSafetyCalc_RP_FodPreCheck_SftyBoolValue();

  TempCVal_s16 = Rte_IRead_WspSafetyCalc_FodCanAmbTemp_TempCVal_s16();

  TempCVal_s16_0 = Rte_IRead_WspSafetyCalc_PpmAmbTemp_TempCVal_s16();

  TempCVal_s16_1 = Rte_IRead_WspSafetyCalc_PpmSinkTemp_TempCVal_s16();

  SCI_WsSafety_SftyEnableDisableValue = Rte_IRead_WspSafetyCalc_RP_ASC_DetectState_u8_T_SCI_WsSafety_SftyEnableDisableValue();

  SCI_WsSafety_SftyOnOffValue = Rte_IRead_WspSafetyCalc_RP_ObjectDetectState_u8_T_SCI_WsSafety_SftyOnOffValue();

  SCI_WsSafety_OruSftyMgrState_u8_TValue = Rte_IRead_WspSafetyCalc_RP_OruSftyMgrState_u8_T_SCI_WsSafety_OruSftyMgrState_u8_TValue();

  SCI_WsSafety_SelftestIn_u8_TValue = Rte_IRead_WspSafetyCalc_RP_SelftestIn_u8_T_SCI_WsSafety_SelftestIn_u8_TValue();

  SCI_WsSafety_ActStateWsValue = Rte_IRead_WspSafetyCalc_RP_SysMgrMode_u8_T_SCI_WsSafety_ActStateWsValue();

  SCI_WsSafety_SftyOnOffValue_0 = Rte_IRead_WspSafetyCalc_RP_VD_Status_SCI_WsSafety_SftyOnOffValue();

  SCI_WsSafety_SftyEnableDisableValue_0 = Rte_IRead_WspSafetyCalc_RP_WS_DisableState_u8_T_SCI_WsSafety_SftyEnableDisableValue();

  Current = Rte_IRead_WspSafetyCalc_RP_WspZMoverCurrent_Current();

  ZMoverMotSpeedVal = Rte_IRead_WspSafetyCalc_RP_WspZMoverMotSpeed_ZMoverMotSpeedVal();

  ZMoverPositionVal = Rte_IRead_WspSafetyCalc_RP_WspZMoverPosition_ZMoverPositionVal();

  TempCVal_s16_2 = Rte_IRead_WspSafetyCalc_WpmAmbTemp_TempCVal_s16();

  TempCVal_s16_3 = Rte_IRead_WspSafetyCalc_WpmFanTemp_TempCVal_s16();

  TempCVal_s16_4 = Rte_IRead_WspSafetyCalc_WpmSinkTemp_TempCVal_s16();

  status = Rte_Call_Event_SAFETY_SHUTDOWN_TEMPERATURE_PAD_SetEventStatus(EventStatus);

  status = Rte_Call_Event_SAFETY_SHUTDOWN_TEMPERATURE_WU_SetEventStatus(EventStatus_0);

  status = Rte_Call_alive_WdgMSvEnt_SftyCalc_CheckpointReached(CheckpointId);

  status = Rte_Call_alive_WdgMSvEnt_SftyCalc_UpdateAliveCounter();

}

void SCI_WsSafety_WspSafetyPinch (void)
{
  WdgM_CheckpointIdType CheckpointId;
  Dem_EventStatusType EventStatus;
  TempC TempCVal_s16_4;
  TempC TempCVal_s16_3;
  TempC TempCVal_s16_2;
  P2CONST(SftyBoolED, AUTOMATIC, AUTOMATIC) SCI_WsSafety_SftyEnableDisableValue_0;
  P2CONST(SftyBoolOO, AUTOMATIC, AUTOMATIC) SCI_WsSafety_SftyOnOffValue_0;
  GenericByte SCI_WsSafety_ActStateWsValue;
  GenericByte SCI_WsSafety_SelftestIn_u8_TValue;
  GenericByte SCI_WsSafety_OruSftyMgrState_u8_TValue;
  P2CONST(SftyBoolOO, AUTOMATIC, AUTOMATIC) SCI_WsSafety_SftyOnOffValue;
  P2CONST(SftyBoolTF, AUTOMATIC, AUTOMATIC) SftyBoolValue_3;
  P2CONST(SftyBoolTF, AUTOMATIC, AUTOMATIC) SftyBoolValue_2;
  P2CONST(SftyBoolTF, AUTOMATIC, AUTOMATIC) SftyBoolValue_1;
  P2CONST(SftyBoolTF, AUTOMATIC, AUTOMATIC) SftyBoolValue_0;
  P2CONST(SftyBoolTF, AUTOMATIC, AUTOMATIC) SftyBoolValue;
  P2CONST(SftyBoolED, AUTOMATIC, AUTOMATIC) SCI_WsSafety_SftyEnableDisableValue;
  TempC TempCVal_s16_1;
  TempC TempCVal_s16_0;
  TempC TempCVal_s16;
  ZMoverPos ZMoverPositionVal;
  Rpm_s16 ZMoverMotSpeedVal;
  Current_s32 Current;
  P2CONST(PosTxPlausiData, AUTOMATIC, AUTOMATIC) SCI_WsSafety_PosTxPlausiDataValue;
  uint8 WspSafetyPinchState;
  uint8 WspSafetyPosState;
  Std_ReturnType status;

  Rte_IrvIWrite_WspSafetyPinch_WspSafetyPosState(WspSafetyPosState);

  Rte_IrvIWrite_WspSafetyPinch_WspSafetyPinchState(WspSafetyPinchState);

  SCI_WsSafety_PosTxPlausiDataValue = Rte_IRead_WspSafetyPinch_RP_POS_SC_State_u8_T_SCI_WsSafety_PosTxPlausiDataValue();

  Current = Rte_IRead_WspSafetyPinch_RP_WspZMoverCurrent_Current();

  ZMoverMotSpeedVal = Rte_IRead_WspSafetyPinch_RP_WspZMoverMotSpeed_ZMoverMotSpeedVal();

  ZMoverPositionVal = Rte_IRead_WspSafetyPinch_RP_WspZMoverPosition_ZMoverPositionVal();

  TempCVal_s16 = Rte_IRead_WspSafetyPinch_FodCanAmbTemp_TempCVal_s16();

  TempCVal_s16_0 = Rte_IRead_WspSafetyPinch_PpmAmbTemp_TempCVal_s16();

  TempCVal_s16_1 = Rte_IRead_WspSafetyPinch_PpmSinkTemp_TempCVal_s16();

  SCI_WsSafety_SftyEnableDisableValue = Rte_IRead_WspSafetyPinch_RP_ASC_DetectState_u8_T_SCI_WsSafety_SftyEnableDisableValue();

  SftyBoolValue = Rte_IRead_WspSafetyPinch_RP_FodCheckDuringChrg_SftyBoolValue();

  SftyBoolValue_0 = Rte_IRead_WspSafetyPinch_RP_FodCheckStartUpChrg_SftyBoolValue();

  SftyBoolValue_1 = Rte_IRead_WspSafetyPinch_RP_FodCheckZMDown_SftyBoolValue();

  SftyBoolValue_2 = Rte_IRead_WspSafetyPinch_RP_FodCheckZMUp_SftyBoolValue();

  SftyBoolValue_3 = Rte_IRead_WspSafetyPinch_RP_FodPreCheck_SftyBoolValue();

  SCI_WsSafety_SftyOnOffValue = Rte_IRead_WspSafetyPinch_RP_ObjectDetectState_u8_T_SCI_WsSafety_SftyOnOffValue();

  SCI_WsSafety_OruSftyMgrState_u8_TValue = Rte_IRead_WspSafetyPinch_RP_OruSftyMgrState_u8_T_SCI_WsSafety_OruSftyMgrState_u8_TValue();

  SCI_WsSafety_SelftestIn_u8_TValue = Rte_IRead_WspSafetyPinch_RP_SelftestIn_u8_T_SCI_WsSafety_SelftestIn_u8_TValue();

  SCI_WsSafety_ActStateWsValue = Rte_IRead_WspSafetyPinch_RP_SysMgrMode_u8_T_SCI_WsSafety_ActStateWsValue();

  SCI_WsSafety_SftyOnOffValue_0 = Rte_IRead_WspSafetyPinch_RP_VD_Status_SCI_WsSafety_SftyOnOffValue();

  SCI_WsSafety_SftyEnableDisableValue_0 = Rte_IRead_WspSafetyPinch_RP_WS_DisableState_u8_T_SCI_WsSafety_SftyEnableDisableValue();

  TempCVal_s16_2 = Rte_IRead_WspSafetyPinch_WpmAmbTemp_TempCVal_s16();

  TempCVal_s16_3 = Rte_IRead_WspSafetyPinch_WpmFanTemp_TempCVal_s16();

  TempCVal_s16_4 = Rte_IRead_WspSafetyPinch_WpmSinkTemp_TempCVal_s16();

  status = Rte_Call_Event_PINCH_PROTECTION_WAS_ACTIVE_SetEventStatus(EventStatus);

  status = Rte_Call_alive_WdgMSvEnt_SftyPinch_CheckpointReached(CheckpointId);

  status = Rte_Call_alive_WdgMSvEnt_SftyPinch_UpdateAliveCounter();

}

void Safety_GetSafetyErrorState (P2VAR(uint32, AUTOMATIC, RTE_APPL_DATA) SafetyErrorState)
{
  SftyErrorState ErrorStateSafety_struct_u32;
  Std_ReturnType status;

  Rte_IrvRead_Safety_GetSafetyErrorState_ErrorStateSafety_struct_u32(&ErrorStateSafety_struct_u32);

}

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------

  ------------------------[per instance memory API]--------------------------

*/
/** @} doxygen end group definition */
/*==================[end of file]============================================*/

