
/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains an Rte component template / example code
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Wed Apr 11 12:30:11 CEST 2018. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#include "Rte_SCI_B6Bridge.h"

/*------------------------[runnable entity skeletons]------------------------*/

void b6b_readMCAL (void)
{
  Dem_FaultDetectionCounterType EventIdFaultDetectionCounter_1;
  Dem_DTCType DTCofEvent_1;
  Dem_DTCKindType DTCKind_1;
  boolean EventTested_1;
  boolean EventFailed_1;
  Dem_EventStatusExtendedType EventStatusExtended_1;
  Dem_EventStatusType EventStatus_1;
  Dem_FaultDetectionCounterType EventIdFaultDetectionCounter_0;
  Dem_DTCType DTCofEvent_0;
  Dem_DTCKindType DTCKind_0;
  boolean EventTested_0;
  boolean EventFailed_0;
  Dem_EventStatusExtendedType EventStatusExtended_0;
  Dem_EventStatusType EventStatus_0;
  Dem_FaultDetectionCounterType EventIdFaultDetectionCounter;
  Dem_DTCType DTCofEvent;
  Dem_DTCKindType DTCKind;
  boolean EventTested;
  boolean EventFailed;
  Dem_EventStatusExtendedType EventStatusExtended;
  Dem_EventStatusType EventStatus;
  P2VAR(Voltage_u16, AUTOMATIC, AUTOMATIC) Voltage_0;
  Voltage_u16 Voltage;
  P2VAR(Current_s32, AUTOMATIC, AUTOMATIC) Current_4;
  Current_s32 Current_3;
  P2VAR(Current_s32, AUTOMATIC, AUTOMATIC) Current_2;
  Current_s32 Current_1;
  P2VAR(Current_s32, AUTOMATIC, AUTOMATIC) Current_0;
  Current_s32 Current;
  P2VAR(PhaseShift, AUTOMATIC, AUTOMATIC) PhaseShiftValue_0;
  PhaseShift PhaseShiftValue;
  P2VAR(uint16, AUTOMATIC, AUTOMATIC) Count_4;
  uint16 Count_3;
  P2VAR(uint16, AUTOMATIC, AUTOMATIC) Count_2;
  uint16 Count_1;
  P2VAR(uint16, AUTOMATIC, AUTOMATIC) Count_0;
  uint16 Count;
  P2VAR(Power_u16, AUTOMATIC, AUTOMATIC) PowerValue_0;
  Power_u16 PowerValue;
  P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_B6Bridge_B6B_State_u8_TValue_0;
  GenericByte SCI_B6Bridge_B6B_State_u8_TValue;
  Std_ReturnType status;

  Rte_IWrite_b6b_readMCAL_WspB6Cdd_stB6_SCI_B6Bridge_B6B_State_u8_TValue(SCI_B6Bridge_B6B_State_u8_TValue);

  SCI_B6Bridge_B6B_State_u8_TValue_0 = Rte_IWriteRef_b6b_readMCAL_WspB6Cdd_stB6_SCI_B6Bridge_B6B_State_u8_TValue();

  Rte_IWrite_b6b_readMCAL_WspB6cdd_pwrB6Meas_PowerValue(PowerValue);

  PowerValue_0 = Rte_IWriteRef_b6b_readMCAL_WspB6cdd_pwrB6Meas_PowerValue();

  Rte_IWrite_b6b_readMCAL_WspB6cdd_numZeroCrossU_Count(Count);

  Count_0 = Rte_IWriteRef_b6b_readMCAL_WspB6cdd_numZeroCrossU_Count();

  Rte_IWrite_b6b_readMCAL_WspB6cdd_numZeroCrossV_Count(Count_1);

  Count_2 = Rte_IWriteRef_b6b_readMCAL_WspB6cdd_numZeroCrossV_Count();

  Rte_IWrite_b6b_readMCAL_WspB6cdd_numZeroCrossW_Count(Count_3);

  Count_4 = Rte_IWriteRef_b6b_readMCAL_WspB6cdd_numZeroCrossW_Count();

  Rte_IWrite_b6b_readMCAL_WspB6cdd_phiB6Meas_PhaseShiftValue(PhaseShiftValue);

  PhaseShiftValue_0 = Rte_IWriteRef_b6b_readMCAL_WspB6cdd_phiB6Meas_PhaseShiftValue();

  Rte_IWrite_b6b_readMCAL_WspB6cdd_iWpcPhas1_Current(Current);

  Current_0 = Rte_IWriteRef_b6b_readMCAL_WspB6cdd_iWpcPhas1_Current();

  Rte_IWrite_b6b_readMCAL_WspB6cdd_iWpcPhas2_Current(Current_1);

  Current_2 = Rte_IWriteRef_b6b_readMCAL_WspB6cdd_iWpcPhas2_Current();

  Rte_IWrite_b6b_readMCAL_WspB6cdd_iWpcPhas3_Current(Current_3);

  Current_4 = Rte_IWriteRef_b6b_readMCAL_WspB6cdd_iWpcPhas3_Current();

  Rte_IWrite_b6b_readMCAL_WspB6cdd_uAvrg_Voltage(Voltage);

  Voltage_0 = Rte_IWriteRef_b6b_readMCAL_WspB6cdd_uAvrg_Voltage();

  status = Rte_Call_Event_WPC_IN_CURRENT_HIGH_SetEventStatus(EventStatus);

  status = Rte_Call_Event_WPC_IN_CURRENT_HIGH_ResetEventStatus();

  status = Rte_Call_Event_WPC_IN_CURRENT_HIGH_GetEventStatus(&EventStatusExtended);

  status = Rte_Call_Event_WPC_IN_CURRENT_HIGH_GetEventFailed(&EventFailed);

  status = Rte_Call_Event_WPC_IN_CURRENT_HIGH_GetEventTested(&EventTested);

  status = Rte_Call_Event_WPC_IN_CURRENT_HIGH_GetDTCOfEvent(DTCKind, &DTCofEvent);

  status = Rte_Call_Event_WPC_IN_CURRENT_HIGH_PrestoreFreezeFrame();

  status = Rte_Call_Event_WPC_IN_CURRENT_HIGH_ClearPrestoredFreezeFrame();

  status = Rte_Call_Event_WPC_IN_CURRENT_HIGH_GetFaultDetectionCounter(&EventIdFaultDetectionCounter);

  status = Rte_Call_Event_WPC_INPUT_POWER_LOW_SetEventStatus(EventStatus_0);

  status = Rte_Call_Event_WPC_INPUT_POWER_LOW_ResetEventStatus();

  status = Rte_Call_Event_WPC_INPUT_POWER_LOW_GetEventStatus(&EventStatusExtended_0);

  status = Rte_Call_Event_WPC_INPUT_POWER_LOW_GetEventFailed(&EventFailed_0);

  status = Rte_Call_Event_WPC_INPUT_POWER_LOW_GetEventTested(&EventTested_0);

  status = Rte_Call_Event_WPC_INPUT_POWER_LOW_GetDTCOfEvent(DTCKind_0, &DTCofEvent_0);

  status = Rte_Call_Event_WPC_INPUT_POWER_LOW_PrestoreFreezeFrame();

  status = Rte_Call_Event_WPC_INPUT_POWER_LOW_ClearPrestoredFreezeFrame();

  status = Rte_Call_Event_WPC_INPUT_POWER_LOW_GetFaultDetectionCounter(&EventIdFaultDetectionCounter_0);

  status = Rte_Call_Event_WPC_INPUT_POWER_HIGH_SetEventStatus(EventStatus_1);

  status = Rte_Call_Event_WPC_INPUT_POWER_HIGH_ResetEventStatus();

  status = Rte_Call_Event_WPC_INPUT_POWER_HIGH_GetEventStatus(&EventStatusExtended_1);

  status = Rte_Call_Event_WPC_INPUT_POWER_HIGH_GetEventFailed(&EventFailed_1);

  status = Rte_Call_Event_WPC_INPUT_POWER_HIGH_GetEventTested(&EventTested_1);

  status = Rte_Call_Event_WPC_INPUT_POWER_HIGH_GetDTCOfEvent(DTCKind_1, &DTCofEvent_1);

  status = Rte_Call_Event_WPC_INPUT_POWER_HIGH_PrestoreFreezeFrame();

  status = Rte_Call_Event_WPC_INPUT_POWER_HIGH_ClearPrestoredFreezeFrame();

  status = Rte_Call_Event_WPC_INPUT_POWER_HIGH_GetFaultDetectionCounter(&EventIdFaultDetectionCounter_1);

}

void b6b_writeMCAL (void)
{
  Power_u16 PowerValue;
  Freq_u32 Val;
  Std_ReturnType status;

  Val = Rte_IRead_b6b_writeMCAL_WspPwrTrf_frqB6Req_Val();

  PowerValue = Rte_IRead_b6b_writeMCAL_WspPwrTrf_pwrB6Req_PowerValue();

}

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------

  ------------------------[per instance memory API]--------------------------

*/
/** @} doxygen end group definition */
/*==================[end of file]============================================*/

