
/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains an Rte component template / example code
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Fri Feb 09 11:09:49 CET 2018. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#include "Rte_SwC_StdComMUser.h"

/*------------------------[runnable entity skeletons]------------------------*/

void SwC_StdComMUser_StdComMUser_Runnable10ms (void)
{
  SesCtrlType SesCtrl;
  ComM_ModeType ComMode_0;
  ComM_ModeType ComMode;
  P2VAR(DT_NM_AWC_NM_aktiv_Tmin, AUTOMATIC, AUTOMATIC) NM_AWC_NM_aktiv_Tmin_NMH_AWC_MLBevo_HCAN_0;
  DT_NM_AWC_NM_aktiv_Tmin NM_AWC_NM_aktiv_Tmin_NMH_AWC_MLBevo_HCAN;
  P2VAR(DT_NM_AWC_NM_aktiv_KL15, AUTOMATIC, AUTOMATIC) NM_AWC_NM_aktiv_KL15_NMH_AWC_MLBevo_HCAN_0;
  DT_NM_AWC_NM_aktiv_KL15 NM_AWC_NM_aktiv_KL15_NMH_AWC_MLBevo_HCAN;
  P2VAR(DT_NM_AWC_NM_aktiv_Diagnose, AUTOMATIC, AUTOMATIC) NM_AWC_NM_aktiv_Diagnose_NMH_AWC_MLBevo_HCAN_0;
  DT_NM_AWC_NM_aktiv_Diagnose NM_AWC_NM_aktiv_Diagnose_NMH_AWC_MLBevo_HCAN;
  Std_ReturnType status;

  Rte_IWrite_StdComMUser_Runnable10ms_PPort_NM_active_Diag_NM_AWC_NM_aktiv_Diagnose_NMH_AWC_MLBevo_HCAN(NM_AWC_NM_aktiv_Diagnose_NMH_AWC_MLBevo_HCAN);

  NM_AWC_NM_aktiv_Diagnose_NMH_AWC_MLBevo_HCAN_0 = Rte_IWriteRef_StdComMUser_Runnable10ms_PPort_NM_active_Diag_NM_AWC_NM_aktiv_Diagnose_NMH_AWC_MLBevo_HCAN();

  Rte_IWrite_StdComMUser_Runnable10ms_PPort_NM_active_T15_NM_AWC_NM_aktiv_KL15_NMH_AWC_MLBevo_HCAN(NM_AWC_NM_aktiv_KL15_NMH_AWC_MLBevo_HCAN);

  NM_AWC_NM_aktiv_KL15_NMH_AWC_MLBevo_HCAN_0 = Rte_IWriteRef_StdComMUser_Runnable10ms_PPort_NM_active_T15_NM_AWC_NM_aktiv_KL15_NMH_AWC_MLBevo_HCAN();

  Rte_IWrite_StdComMUser_Runnable10ms_PPort_NM_active_TMin_NM_AWC_NM_aktiv_Tmin_NMH_AWC_MLBevo_HCAN(NM_AWC_NM_aktiv_Tmin_NMH_AWC_MLBevo_HCAN);

  NM_AWC_NM_aktiv_Tmin_NMH_AWC_MLBevo_HCAN_0 = Rte_IWriteRef_StdComMUser_Runnable10ms_PPort_NM_active_TMin_NM_AWC_NM_aktiv_Tmin_NMH_AWC_MLBevo_HCAN();

  status = Rte_Call_UR_ComMUser_MLBevo_HCAN_RequestComMode(ComMode);

  status = Rte_Call_UR_ComMUser_MLBevo_HCAN_GetCurrentComMode(&ComMode_0);

  status = Rte_Call_DCMServices_GetSesCtrlType(&SesCtrl);

}

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------

  ------------------------[per instance memory API]--------------------------

*/
/** @} doxygen end group definition */
/*==================[end of file]============================================*/

