
/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains an Rte component template / example code
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Fri Feb 09 11:09:50 CET 2018. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#include "Rte_SwCDiagData.h"

/*------------------------[runnable entity skeletons]------------------------*/

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagData_Did_2bd_Read (P2VAR(Dcm_Data0x02BD_ArrayType, AUTOMATIC, RTE_APPL_DATA) data)
#else
Std_ReturnType DiagData_Did_2bd_Read (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data)
#endif
{
  DT_UH_Sekunde_Rx SIG_UH_Sekunde;
  DT_UH_Jahr_Rx SIG_UH_Jahr;
  DT_UH_Minute_Rx SIG_UH_Minute;
  DT_UH_Monat_Rx SIG_UH_Monat;
  DT_UH_Stunde_Rx SIG_UH_Stunde;
  DT_UH_Tag_Rx SIG_UH_Tag;
  Std_ReturnType status;

  status = Rte_Read_Port_Diagnose1_SIG_UH_Tag(&SIG_UH_Tag);

  status = Rte_Read_Port_Diagnose1_SIG_UH_Stunde(&SIG_UH_Stunde);

  status = Rte_Read_Port_Diagnose1_SIG_UH_Monat(&SIG_UH_Monat);

  status = Rte_Read_Port_Diagnose1_SIG_UH_Minute(&SIG_UH_Minute);

  status = Rte_Read_Port_Diagnose1_SIG_UH_Jahr(&SIG_UH_Jahr);

  status = Rte_Read_Port_Diagnose1_SIG_UH_Sekunde(&SIG_UH_Sekunde);

  return status;
}

Std_ReturnType DiagData_Did_2bd_ConditionCheckRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Std_ReturnType status;

  return status;
}

void DiagData_ServiceHandler (void)
{
  boolean BlockChanged_0;
  uint8 CounterValue;
  boolean BlockChanged;
  uint8 DGN_Verlernzaehler;
  Std_ReturnType status;

  DGN_Verlernzaehler = Rte_IRead_ServiceHandler_Diagnose_01_DGN_Verlernzaehler();

  status = Rte_Call_PS_NvM_SwCDiagData_Mileage_SetRamBlockStatus(BlockChanged);

  status = Rte_Call_ExtAgingCycle_SetAgingCycleCounterValue(CounterValue);

  status = Rte_Call_PS_NvM_SwCDiagData_UnlearnCounter_SetRamBlockStatus(BlockChanged_0);

}

Std_ReturnType DiagData_CheckEnvConditionRead (P2VAR(NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) Nrc)
{
  Std_ReturnType status;

  return status;
}

#ifdef RTE_PTR2ARRAYTYPE_PASSING
Std_ReturnType DiagData_ReadEnvData (P2VAR(Dem_Did0x0002_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data)
#else
Std_ReturnType DiagData_ReadEnvData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data)
#endif
{
  DT_UH_Sekunde_Rx SIG_UH_Sekunde;
  DT_UH_Jahr_Rx SIG_UH_Jahr;
  DT_UH_Minute_Rx SIG_UH_Minute;
  DT_UH_Monat_Rx SIG_UH_Monat;
  DT_KBI_Kilometerstand_Rx SIG_KBI_Kilometerstand;
  DT_UH_Stunde_Rx SIG_UH_Stunde;
  DT_UH_Tag_Rx SIG_UH_Tag;
  Std_ReturnType status;

  status = Rte_Read_Port_Diagnose1_SIG_UH_Tag(&SIG_UH_Tag);

  status = Rte_Read_Port_Diagnose1_SIG_UH_Stunde(&SIG_UH_Stunde);

  status = Rte_Read_Port_Diagnose1_SIG_KBI_Kilometerstand(&SIG_KBI_Kilometerstand);

  status = Rte_Read_Port_Diagnose1_SIG_UH_Monat(&SIG_UH_Monat);

  status = Rte_Read_Port_Diagnose1_SIG_UH_Minute(&SIG_UH_Minute);

  status = Rte_Read_Port_Diagnose1_SIG_UH_Jahr(&SIG_UH_Jahr);

  status = Rte_Read_Port_Diagnose1_SIG_UH_Sekunde(&SIG_UH_Sekunde);

  return status;
}

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------

  ------------------------[per instance memory API]--------------------------

*/
/** @} doxygen end group definition */
/*==================[end of file]============================================*/

