
/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains an Rte component template / example code
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Fri Feb 09 14:59:51 CET 2018. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#include "Rte_WdgM.h"

/*------------------------[runnable entity skeletons]------------------------*/

void WdgM_MainFunction (void)
{
  uint8 mode_WdgMSvEnt_StMgr_0;
  uint8 mode_WdgMSvEnt_FodMgr_0;
  uint8 mode_WdgMSvEnt_VehDetMain_0;
  uint8 mode_WdgMSvEnt_VehDetDwnSmpl_0;
  uint8 mode_WdgMSvEnt_SftyIoWriteToHw_0;
  uint8 mode_WdgMSvEnt_SftyPinch_0;
  uint8 mode_WdgMSvEnt_SftyCalc_0;
  uint8 mode_WdgMSvEnt_SftyMain_0;
  uint8 mode_WdgMSvEnt_SftyIoReadFromHw_0;
  uint8 globalMode_0;
  uint8 mode_WdgMSvEnt_StMgr;
  uint8 mode_WdgMSvEnt_FodMgr;
  uint8 mode_WdgMSvEnt_VehDetMain;
  uint8 mode_WdgMSvEnt_VehDetDwnSmpl;
  uint8 mode_WdgMSvEnt_SftyIoWriteToHw;
  uint8 mode_WdgMSvEnt_SftyPinch;
  uint8 mode_WdgMSvEnt_SftyCalc;
  uint8 mode_WdgMSvEnt_SftyMain;
  uint8 mode_WdgMSvEnt_SftyIoReadFromHw;
  uint8 globalMode;
  Std_ReturnType status;

  status = Rte_Switch_globalMode_currentMode(globalMode);

  status = Rte_Switch_mode_WdgMSvEnt_SftyIoReadFromHw_currentMode(mode_WdgMSvEnt_SftyIoReadFromHw);

  status = Rte_Switch_mode_WdgMSvEnt_SftyMain_currentMode(mode_WdgMSvEnt_SftyMain);

  status = Rte_Switch_mode_WdgMSvEnt_SftyCalc_currentMode(mode_WdgMSvEnt_SftyCalc);

  status = Rte_Switch_mode_WdgMSvEnt_SftyPinch_currentMode(mode_WdgMSvEnt_SftyPinch);

  status = Rte_Switch_mode_WdgMSvEnt_SftyIoWriteToHw_currentMode(mode_WdgMSvEnt_SftyIoWriteToHw);

  status = Rte_Switch_mode_WdgMSvEnt_VehDetDwnSmpl_currentMode(mode_WdgMSvEnt_VehDetDwnSmpl);

  status = Rte_Switch_mode_WdgMSvEnt_VehDetMain_currentMode(mode_WdgMSvEnt_VehDetMain);

  status = Rte_Switch_mode_WdgMSvEnt_FodMgr_currentMode(mode_WdgMSvEnt_FodMgr);

  status = Rte_Switch_mode_WdgMSvEnt_StMgr_currentMode(mode_WdgMSvEnt_StMgr);

  globalMode_0 = Rte_Mode_globalMode_currentMode();

  mode_WdgMSvEnt_SftyIoReadFromHw_0 = Rte_Mode_mode_WdgMSvEnt_SftyIoReadFromHw_currentMode();

  mode_WdgMSvEnt_SftyMain_0 = Rte_Mode_mode_WdgMSvEnt_SftyMain_currentMode();

  mode_WdgMSvEnt_SftyCalc_0 = Rte_Mode_mode_WdgMSvEnt_SftyCalc_currentMode();

  mode_WdgMSvEnt_SftyPinch_0 = Rte_Mode_mode_WdgMSvEnt_SftyPinch_currentMode();

  mode_WdgMSvEnt_SftyIoWriteToHw_0 = Rte_Mode_mode_WdgMSvEnt_SftyIoWriteToHw_currentMode();

  mode_WdgMSvEnt_VehDetDwnSmpl_0 = Rte_Mode_mode_WdgMSvEnt_VehDetDwnSmpl_currentMode();

  mode_WdgMSvEnt_VehDetMain_0 = Rte_Mode_mode_WdgMSvEnt_VehDetMain_currentMode();

  mode_WdgMSvEnt_FodMgr_0 = Rte_Mode_mode_WdgMSvEnt_FodMgr_currentMode();

  mode_WdgMSvEnt_StMgr_0 = Rte_Mode_mode_WdgMSvEnt_StMgr_currentMode();

}

Std_ReturnType WdgM_Rte_UpdateAliveCounter (WdgM_SupervisedEntityIdType pdav0)
{
  Std_ReturnType status;

  return status;
}

Std_ReturnType WdgM_Rte_CheckpointReached (WdgM_SupervisedEntityIdType pdav0, WdgM_CheckpointIdType CheckpointId)
{
  Std_ReturnType status;

  return status;
}

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------

  ------------------------[per instance memory API]--------------------------

*/
/** @} doxygen end group definition */
/*==================[end of file]============================================*/

