/* --------{ EB Automotive C Source File }-------- */

/*==================[inclusions]=============================================*/

/*==================[macros]=================================================*/

/*------------------[Autosar vendor identification]--------------------------*/

#if (!defined MEM_VENDOR_ID)
/** \brief Autosar module vendor identification
 **
 ** Vendor ID of the dedicated implementation of this module according
 ** to the AUTOSAR vendor list. */
#define MEMMAP_VENDOR_ID 1U /* Elektrobit Automotive GmbH */
#endif

/*------------------[AUTOSAR module identification]-------------------------*/

#if (defined MODULE_MODULE_ID)
#error MEMMAP_MODULE_ID already defined
#endif
/** \brief AUTOSAR module identification */
#define MEMMAP_MODULE_ID 195U

/*------------------[AUTOSAR release version identification]----------------*/

#if (!defined MEM_AR_MAJOR_VERSION)
/** \brief definition of the major version of the specification */
#define MEMMAP_AR_MAJOR_VERSION 4U
#endif

#if (!defined MEM_AR_MINOR_VERSION)
/** \brief definition of a minor version of the specification */
#define MEMMAP_AR_MINOR_VERSION 0U
#endif

#if (!defined MEM_AR_PATCH_VERSION)
/** \brief definition of a patch version of the specification */
#define MEMMAP_AR_PATCH_VERSION 3U
#endif

/*------------------[AUTOSAR module version identification]------------------*/

#if (!defined MEM_SW_MAJOR_VERSION)
/** \brief definition of the major version of this implementation */
#define MEMMAP_SW_MAJOR_VERSION 1U
#endif

#if (!defined MEM_SW_MINOR_VERSION)
/** \brief definition of a minor version of this implementation */
#define MEMMAP_SW_MINOR_VERSION 1U
#endif

#if (!defined MEM_SW_PATCH_VERSION)
/** \brief definition of a patch version of this implementation */
#define MEMMAP_SW_PATCH_VERSION 3U
#endif

/*------------------[MemMap error checking]----------------------------------*/

#if (defined MEMMAP_ERROR) /* to prevent double definition */
#error MEMMAP_ERROR defined, wrong MemMap.h usage
#endif /* if (!defined MEMMAP_ERROR) */

/** \brief Checks if this file has been correctly used
 **
 ** This definition checks if this file has been correctly included
 ** the last time.
 ** We do it here, before the big if-elif. */
#define MEMMAP_ERROR


/*------------------[MemMap extensions]--------------------------------------*/

#include <BasicTemplate_MemMap.h>
#include <Vector_MemMap.h>
#include <SWCs_MemMap.h>

/*------------------[Start of a module]--------------------------------------*/


/* Memory section macros for Dem */
#if (defined DEM_START_SEC_VAR_16BIT)
	#undef DEM_START_SEC_VAR_16BIT
	#undef MEMMAP_ERROR
#elif (defined DEM_STOP_SEC_VAR_16BIT)
	#undef DEM_STOP_SEC_VAR_16BIT
	#undef MEMMAP_ERROR
#elif (defined DEM_START_SEC_VAR_8BIT)
	#undef DEM_START_SEC_VAR_8BIT
	#undef MEMMAP_ERROR
#elif (defined DEM_STOP_SEC_VAR_8BIT)
	#undef DEM_STOP_SEC_VAR_8BIT
	#undef MEMMAP_ERROR
#elif (defined DEM_START_SEC_VAR_NOINIT_8BIT)
	#undef DEM_START_SEC_VAR_NOINIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined DEM_STOP_SEC_VAR_NOINIT_8BIT)
	#undef DEM_STOP_SEC_VAR_NOINIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined DEM_START_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef DEM_START_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined DEM_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef DEM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined DEM_START_SEC_VAR_UNSPECIFIED)
	#undef DEM_START_SEC_VAR_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined DEM_STOP_SEC_VAR_UNSPECIFIED)
	#undef DEM_STOP_SEC_VAR_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined DEM_START_SEC_CONST_UNSPECIFIED)
	#undef DEM_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined DEM_STOP_SEC_CONST_UNSPECIFIED)
	#undef DEM_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined DEM_START_SEC_CODE)
	#undef DEM_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined DEM_STOP_SEC_CODE)
	#undef DEM_STOP_SEC_CODE
	#undef MEMMAP_ERROR

/* Memory section macros for Dcm */
#elif (defined DCM_START_SEC_VAR_POWER_ON_INIT_8BIT)
	#undef DCM_START_SEC_VAR_POWER_ON_INIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined DCM_STOP_SEC_VAR_POWER_ON_INIT_8BIT)
	#undef DCM_STOP_SEC_VAR_POWER_ON_INIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined DCM_START_SEC_VAR_16BIT)
	#undef DCM_START_SEC_VAR_16BIT
	#undef MEMMAP_ERROR
#elif (defined DCM_STOP_SEC_VAR_16BIT)
	#undef DCM_STOP_SEC_VAR_16BIT
	#undef MEMMAP_ERROR
#elif (defined DCM_START_SEC_VAR_8BIT)
	#undef DCM_START_SEC_VAR_8BIT
	#undef MEMMAP_ERROR
#elif (defined DCM_STOP_SEC_VAR_8BIT)
	#undef DCM_STOP_SEC_VAR_8BIT
	#undef MEMMAP_ERROR
#elif (defined DCM_START_SEC_CONST_8BIT)
	#undef DCM_START_SEC_CONST_8BIT
	#undef MEMMAP_ERROR
#elif (defined DCM_STOP_SEC_CONST_8BIT)
	#undef DCM_STOP_SEC_CONST_8BIT
	#undef MEMMAP_ERROR
#elif (defined DCM_START_SEC_VAR_NOINIT_8BIT)
	#undef DCM_START_SEC_VAR_NOINIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined DCM_STOP_SEC_VAR_NOINIT_8BIT)
	#undef DCM_STOP_SEC_VAR_NOINIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined DCM_START_SEC_VAR_NOINIT_16BIT)
	#undef DCM_START_SEC_VAR_NOINIT_16BIT
	#undef MEMMAP_ERROR
#elif (defined DCM_STOP_SEC_VAR_NOINIT_16BIT)
	#undef DCM_STOP_SEC_VAR_NOINIT_16BIT
	#undef MEMMAP_ERROR
#elif (defined DCM_START_SEC_VAR_UNSPECIFIED)
	#undef DCM_START_SEC_VAR_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined DCM_STOP_SEC_VAR_UNSPECIFIED)
	#undef DCM_STOP_SEC_VAR_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined DCM_START_SEC_CONST_UNSPECIFIED)
	#undef DCM_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined DCM_STOP_SEC_CONST_UNSPECIFIED)
	#undef DCM_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined DCM_START_SEC_CODE)
	#undef DCM_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined DCM_STOP_SEC_CODE)
	#undef DCM_STOP_SEC_CODE
	#undef MEMMAP_ERROR

/* Memory section macros for ComM */
#elif (defined COMM_START_SEC_PBCFG_ROOT)
	#undef COMM_START_SEC_PBCFG_ROOT
	#undef MEMMAP_ERROR
#elif (defined COMM_STOP_SEC_PBCFG_ROOT)
	#undef COMM_STOP_SEC_PBCFG_ROOT
	#undef MEMMAP_ERROR
#elif (defined COMM_START_SEC_VAR_SAVED_ZONE0_UNSPECIFIED)
	#undef COMM_START_SEC_VAR_SAVED_ZONE0_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined COMM_STOP_SEC_VAR_SAVED_ZONE0_UNSPECIFIED)
	#undef COMM_STOP_SEC_VAR_SAVED_ZONE0_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined COMM_START_SEC_CONST_8BIT)
	#undef COMM_START_SEC_CONST_8BIT
	#undef MEMMAP_ERROR
#elif (defined COMM_STOP_SEC_CONST_8BIT)
	#undef COMM_STOP_SEC_CONST_8BIT
	#undef MEMMAP_ERROR
#elif (defined COMM_START_SEC_CONST_32BIT)
	#undef COMM_START_SEC_CONST_32BIT
	#undef MEMMAP_ERROR
#elif (defined COMM_STOP_SEC_CONST_32BIT)
	#undef COMM_STOP_SEC_CONST_32BIT
	#undef MEMMAP_ERROR
#elif (defined COMM_START_SEC_CONST_UNSPECIFIED)
	#undef COMM_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined COMM_STOP_SEC_CONST_UNSPECIFIED)
	#undef COMM_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined COMM_START_SEC_VAR_NOINIT_16BIT)
	#undef COMM_START_SEC_VAR_NOINIT_16BIT
	#undef MEMMAP_ERROR
#elif (defined COMM_STOP_SEC_VAR_NOINIT_16BIT)
	#undef COMM_STOP_SEC_VAR_NOINIT_16BIT
	#undef MEMMAP_ERROR
#elif (defined COMM_START_SEC_VAR_NOINIT_8BIT)
	#undef COMM_START_SEC_VAR_NOINIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined COMM_STOP_SEC_VAR_NOINIT_8BIT)
	#undef COMM_STOP_SEC_VAR_NOINIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined COMM_START_SEC_VAR_ZERO_INIT_UNSPECIFIED)
	#undef COMM_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined COMM_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED)
	#undef COMM_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined COMM_START_SEC_CODE)
	#undef COMM_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined COMM_STOP_SEC_CODE)
	#undef COMM_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined COMM_START_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef COMM_START_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined COMM_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef COMM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR

/* Memory section macros for Com */
#elif (defined COM_START_SEC_APPL_CODE)
	#undef COM_START_SEC_APPL_CODE
	#undef MEMMAP_ERROR
#elif (defined COM_STOP_SEC_APPL_CODE)
	#undef COM_STOP_SEC_APPL_CODE
	#undef MEMMAP_ERROR
#elif (defined COM_START_SEC_CONST_32BIT)
	#undef COM_START_SEC_CONST_32BIT
	#undef MEMMAP_ERROR
#elif (defined COM_STOP_SEC_CONST_32BIT)
	#undef COM_STOP_SEC_CONST_32BIT
	#undef MEMMAP_ERROR
#elif (defined COM_START_SEC_PBCFG)
	#undef COM_START_SEC_PBCFG
	#undef MEMMAP_ERROR
#elif (defined COM_STOP_SEC_PBCFG)
	#undef COM_STOP_SEC_PBCFG
	#undef MEMMAP_ERROR
#elif (defined COM_START_SEC_PBCFG_ROOT)
	#undef COM_START_SEC_PBCFG_ROOT
	#undef MEMMAP_ERROR
#elif (defined COM_STOP_SEC_PBCFG_ROOT)
	#undef COM_STOP_SEC_PBCFG_ROOT
	#undef MEMMAP_ERROR
#elif (defined COM_START_SEC_VAR_NOINIT_16BIT)
	#undef COM_START_SEC_VAR_NOINIT_16BIT
	#undef MEMMAP_ERROR
#elif (defined COM_STOP_SEC_VAR_NOINIT_16BIT)
	#undef COM_STOP_SEC_VAR_NOINIT_16BIT
	#undef MEMMAP_ERROR
#elif (defined COM_START_SEC_VAR_NOINIT_8BIT)
	#undef COM_START_SEC_VAR_NOINIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined COM_STOP_SEC_VAR_NOINIT_8BIT)
	#undef COM_STOP_SEC_VAR_NOINIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined COM_START_SEC_VAR_NOINIT_BOOLEAN)
	#undef COM_START_SEC_VAR_NOINIT_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined COM_STOP_SEC_VAR_NOINIT_BOOLEAN)
	#undef COM_STOP_SEC_VAR_NOINIT_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined COM_START_SEC_VAR_INIT_UNSPECIFIED)
	#undef COM_START_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined COM_STOP_SEC_VAR_INIT_UNSPECIFIED)
	#undef COM_STOP_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined COM_START_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef COM_START_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined COM_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef COM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined COM_START_SEC_CODE)
	#undef COM_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined COM_STOP_SEC_CODE)
	#undef COM_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined COM_START_SEC_CONST_UNSPECIFIED)
	#undef COM_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined COM_STOP_SEC_CONST_UNSPECIFIED)
	#undef COM_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR

/* Memory section macros for BswM */
#elif (defined BSWM_START_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef BSWM_START_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined BSWM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef BSWM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined BSWM_START_SEC_VAR_INIT_UNSPECIFIED)
	#undef BSWM_START_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined BSWM_STOP_SEC_VAR_INIT_UNSPECIFIED)
	#undef BSWM_STOP_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined BSWM_START_SEC_CONST_UNSPECIFIED)
	#undef BSWM_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined BSWM_STOP_SEC_CONST_UNSPECIFIED)
	#undef BSWM_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined BSWM_START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED)
	#undef BSWM_START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined BSWM_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED)
	#undef BSWM_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined BSWM_START_SEC_CODE)
	#undef BSWM_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined BSWM_STOP_SEC_CODE)
	#undef BSWM_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined BSWM_START_SEC_VAR_NO_INIT_8)
	#undef BSWM_START_SEC_VAR_NO_INIT_8
	#undef MEMMAP_ERROR
#elif (defined BSWM_STOP_SEC_VAR_NO_INIT_8)
	#undef BSWM_STOP_SEC_VAR_NO_INIT_8
	#undef MEMMAP_ERROR
#elif (defined BSWM_START_SEC_VAR_POWER_ON_INIT_32)
	#undef BSWM_START_SEC_VAR_POWER_ON_INIT_32
	#undef MEMMAP_ERROR
#elif (defined BSWM_STOP_SEC_VAR_POWER_ON_INIT_32)
	#undef BSWM_STOP_SEC_VAR_POWER_ON_INIT_32
	#undef MEMMAP_ERROR

/* Memory section macros for NvmExt */
#elif (defined NVMEXT_START_SEC_CODE)
	#undef NVMEXT_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined NVMEXT_STOP_SEC_CODE)
	#undef NVMEXT_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined NVMEXT_START_SEC_VAR)
	#undef NVMEXT_START_SEC_VAR
	#undef MEMMAP_ERROR
#elif (defined NVMEXT_STOP_SEC_VAR)
	#undef NVMEXT_STOP_SEC_VAR
	#undef MEMMAP_ERROR

/* Memory section macros for BswSCI_B6Bridge */
#elif (defined BSWSCI_B6BRIDGE_START_SEC_CODE)
	#undef BSWSCI_B6BRIDGE_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined BSWSCI_B6BRIDGE_STOP_SEC_CODE)
	#undef BSWSCI_B6BRIDGE_STOP_SEC_CODE
	#undef MEMMAP_ERROR

/* Memory section macros for BswSCI_Pfc */
#elif (defined BSWSCI_PFC_START_SEC_CODE)
	#undef BSWSCI_PFC_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined BSWSCI_PFC_STOP_SEC_CODE)
	#undef BSWSCI_PFC_STOP_SEC_CODE
	#undef MEMMAP_ERROR

/* Memory section macros for BswSCI_ZMover */
#elif (defined BSWSCI_ZMOVER_START_SEC_CODE)
	#undef BSWSCI_ZMOVER_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined BSWSCI_ZMOVER_STOP_SEC_CODE)
	#undef BSWSCI_ZMOVER_STOP_SEC_CODE
	#undef MEMMAP_ERROR

/* Memory section macros for NvM */
#elif (defined NVM_START_SEC_CODE)
	#undef NVM_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined NVM_STOP_SEC_CODE)
	#undef NVM_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined NVM_START_SEC_VAR_POWER_ON_INIT_8)
	#undef NVM_START_SEC_VAR_POWER_ON_INIT_8
	#undef MEMMAP_ERROR
#elif (defined NVM_STOP_SEC_VAR_POWER_ON_INIT_8)
	#undef NVM_STOP_SEC_VAR_POWER_ON_INIT_8
	#undef MEMMAP_ERROR
#elif (defined NVM_START_SEC_VAR_INIT_8)
	#undef NVM_START_SEC_VAR_INIT_8
	#undef MEMMAP_ERROR
#elif (defined NVM_STOP_SEC_VAR_INIT_8)
	#undef NVM_STOP_SEC_VAR_INIT_8
	#undef MEMMAP_ERROR
#elif (defined NVM_START_SEC_VAR_NO_INIT_8)
	#undef NVM_START_SEC_VAR_NO_INIT_8
	#undef MEMMAP_ERROR
#elif (defined NVM_STOP_SEC_VAR_NO_INIT_8)
	#undef NVM_STOP_SEC_VAR_NO_INIT_8
	#undef MEMMAP_ERROR
#elif (defined NVM_START_SEC_VAR_APPL_DATA)
	#undef NVM_START_SEC_VAR_APPL_DATA
	#undef MEMMAP_ERROR
#elif (defined NVM_STOP_SEC_VAR_APPL_DATA)
	#undef NVM_STOP_SEC_VAR_APPL_DATA
	#undef MEMMAP_ERROR
#elif (defined NVM_START_SEC_VAR_INIT_16)
	#undef NVM_START_SEC_VAR_INIT_16
	#undef MEMMAP_ERROR
#elif (defined NVM_STOP_SEC_VAR_INIT_16)
	#undef NVM_STOP_SEC_VAR_INIT_16
	#undef MEMMAP_ERROR
#elif (defined NVM_START_SEC_VAR_NO_INIT_16)
	#undef NVM_START_SEC_VAR_NO_INIT_16
	#undef MEMMAP_ERROR
#elif (defined NVM_STOP_SEC_VAR_NO_INIT_16)
	#undef NVM_STOP_SEC_VAR_NO_INIT_16
	#undef MEMMAP_ERROR
#elif (defined NVM_START_SEC_VAR_INIT_UNSPECIFIED)
	#undef NVM_START_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined NVM_STOP_SEC_VAR_INIT_UNSPECIFIED)
	#undef NVM_STOP_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined NVM_START_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef NVM_START_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined NVM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef NVM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined NVM_START_SEC_CONFIG_DATA_APPL_DATA)
	#undef NVM_START_SEC_CONFIG_DATA_APPL_DATA
	#undef MEMMAP_ERROR
#elif (defined NVM_STOP_SEC_CONFIG_DATA_APPL_DATA)
	#undef NVM_STOP_SEC_CONFIG_DATA_APPL_DATA
	#undef MEMMAP_ERROR
#elif (defined NVM_START_CONFIG_DATA_APPL_DATA)
	#undef NVM_START_CONFIG_DATA_APPL_DATA
	#undef MEMMAP_ERROR
#elif (defined NVM_STOP_CONFIG_DATA_APPL_DATA)
	#undef NVM_STOP_CONFIG_DATA_APPL_DATA
	#undef MEMMAP_ERROR
#elif (defined NVM_START_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef NVM_START_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined NVM_STOP_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef NVM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined NVM_START_CONFIG_DATA_UNSPECIFIED)
	#undef NVM_START_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined NVM_STOP_CONFIG_DATA_UNSPECIFIED)
	#undef NVM_STOP_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined NVM_START_SEC_CONFIG_DATA_APPL_CONST)
	#undef NVM_START_SEC_CONFIG_DATA_APPL_CONST
	#undef MEMMAP_ERROR
#elif (defined NVM_STOP_SEC_CONFIG_DATA_APPL_CONST)
	#undef NVM_STOP_SEC_CONFIG_DATA_APPL_CONST
	#undef MEMMAP_ERROR
#elif (defined NVM_START_CONFIG_DATA_APPL_CONST)
	#undef NVM_START_CONFIG_DATA_APPL_CONST
	#undef MEMMAP_ERROR
#elif (defined NVM_STOP_CONFIG_DATA_APPL_CONST)
	#undef NVM_STOP_CONFIG_DATA_APPL_CONST
	#undef MEMMAP_ERROR
#elif (defined NVM_START_SEC_VAR_INIT_32)
	#undef NVM_START_SEC_VAR_INIT_32
	#undef MEMMAP_ERROR
#elif (defined NVM_STOP_SEC_VAR_INIT_32)
	#undef NVM_STOP_SEC_VAR_INIT_32
	#undef MEMMAP_ERROR

/* Memory section macros for Adc */
#elif (defined ADC_START_SEC_CODE)
	#undef ADC_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined ADC_STOP_SEC_CODE)
	#undef ADC_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined ADC_START_SEC_CONST_UNSPECIFIED)
	#undef ADC_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ADC_STOP_SEC_CONST_UNSPECIFIED)
	#undef ADC_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ADC_START_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef ADC_START_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ADC_STOP_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef ADC_STOP_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ADC_START_CONFIG_DATA_UNSPECIFIED)
	#undef ADC_START_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ADC_STOP_CONFIG_DATA_UNSPECIFIED)
	#undef ADC_STOP_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ADC_START_SEC_CONST_32)
	#undef ADC_START_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif (defined ADC_STOP_SEC_CONST_32)
	#undef ADC_STOP_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif (defined ADC_START_SEC_VAR_INIT_UNSPECIFIED)
	#undef ADC_START_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ADC_STOP_SEC_VAR_INIT_UNSPECIFIED)
	#undef ADC_STOP_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ADC_START_SEC_VAR_NO_INIT_32)
	#undef ADC_START_SEC_VAR_NO_INIT_32
	#undef MEMMAP_ERROR
#elif (defined ADC_STOP_SEC_VAR_NO_INIT_32)
	#undef ADC_STOP_SEC_VAR_NO_INIT_32
	#undef MEMMAP_ERROR
#elif (defined ADC_START_SEC_VAR_NO_INIT_32_NO_CACHEABLE)
	#undef ADC_START_SEC_VAR_NO_INIT_32_NO_CACHEABLE
	#undef MEMMAP_ERROR
#elif (defined ADC_STOP_SEC_VAR_NO_INIT_32_NO_CACHEABLE)
	#undef ADC_STOP_SEC_VAR_NO_INIT_32_NO_CACHEABLE
	#undef MEMMAP_ERROR
#elif (defined ADC_START_SEC_VAR_NO_INIT_8)
	#undef ADC_START_SEC_VAR_NO_INIT_8
	#undef MEMMAP_ERROR
#elif (defined ADC_STOP_SEC_VAR_NO_INIT_8)
	#undef ADC_STOP_SEC_VAR_NO_INIT_8
	#undef MEMMAP_ERROR
#elif (defined ADC_START_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef ADC_START_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ADC_STOP_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef ADC_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ADC_START_SEC_VAR_NO_INIT_UNSPECIFIED_NO_CACHEABLE)
	#undef ADC_START_SEC_VAR_NO_INIT_UNSPECIFIED_NO_CACHEABLE
	#undef MEMMAP_ERROR
#elif (defined ADC_STOP_SEC_VAR_NO_INIT_UNSPECIFIED_NO_CACHEABLE)
	#undef ADC_STOP_SEC_VAR_NO_INIT_UNSPECIFIED_NO_CACHEABLE
	#undef MEMMAP_ERROR

/* Memory section macros for Base */
#elif (defined BASE_START_SEC_CODE)
	#undef BASE_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined BASE_STOP_SEC_CODE)
	#undef BASE_STOP_SEC_CODE
	#undef MEMMAP_ERROR

/* Memory section macros for CanIf */
#elif (defined CANIF_START_SEC_APPL_CODE)
	#undef CANIF_START_SEC_APPL_CODE
	#undef MEMMAP_ERROR
#elif (defined CANIF_STOP_SEC_APPL_CODE)
	#undef CANIF_STOP_SEC_APPL_CODE
	#undef MEMMAP_ERROR
#elif (defined CANIF_START_SEC_PBCFG)
	#undef CANIF_START_SEC_PBCFG
	#undef MEMMAP_ERROR
#elif (defined CANIF_STOP_SEC_PBCFG)
	#undef CANIF_STOP_SEC_PBCFG
	#undef MEMMAP_ERROR
#elif (defined CANIF_START_SEC_PBCFG_ROOT)
	#undef CANIF_START_SEC_PBCFG_ROOT
	#undef MEMMAP_ERROR
#elif (defined CANIF_STOP_SEC_PBCFG_ROOT)
	#undef CANIF_STOP_SEC_PBCFG_ROOT
	#undef MEMMAP_ERROR
#elif (defined CANIF_START_SEC_VAR_ZERO_INIT_UNSPECIFIED)
	#undef CANIF_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined CANIF_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED)
	#undef CANIF_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined CANIF_START_SEC_CONST_8BIT)
	#undef CANIF_START_SEC_CONST_8BIT
	#undef MEMMAP_ERROR
#elif (defined CANIF_STOP_SEC_CONST_8BIT)
	#undef CANIF_STOP_SEC_CONST_8BIT
	#undef MEMMAP_ERROR
#elif (defined CANIF_START_SEC_CONST_32BIT)
	#undef CANIF_START_SEC_CONST_32BIT
	#undef MEMMAP_ERROR
#elif (defined CANIF_STOP_SEC_CONST_32BIT)
	#undef CANIF_STOP_SEC_CONST_32BIT
	#undef MEMMAP_ERROR
#elif (defined CANIF_START_SEC_CODE)
	#undef CANIF_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined CANIF_STOP_SEC_CODE)
	#undef CANIF_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined CANIF_START_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef CANIF_START_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined CANIF_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef CANIF_STOP_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined CANIF_START_SEC_CONST_UNSPECIFIED)
	#undef CANIF_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined CANIF_STOP_SEC_CONST_UNSPECIFIED)
	#undef CANIF_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR

/* Memory section macros for CanSM */
#elif (defined CANSM_START_SEC_VAR_ZERO_INIT_8BIT)
	#undef CANSM_START_SEC_VAR_ZERO_INIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined CANSM_STOP_SEC_VAR_ZERO_INIT_8BIT)
	#undef CANSM_STOP_SEC_VAR_ZERO_INIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined CANSM_START_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef CANSM_START_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined CANSM_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef CANSM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined CANSM_START_SEC_CODE)
	#undef CANSM_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined CANSM_STOP_SEC_CODE)
	#undef CANSM_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined CANSM_START_SEC_APPL_CODE)
	#undef CANSM_START_SEC_APPL_CODE
	#undef MEMMAP_ERROR
#elif (defined CANSM_STOP_SEC_APPL_CODE)
	#undef CANSM_STOP_SEC_APPL_CODE
	#undef MEMMAP_ERROR
#elif (defined CANSM_START_SEC_CONST_16BIT)
	#undef CANSM_START_SEC_CONST_16BIT
	#undef MEMMAP_ERROR
#elif (defined CANSM_STOP_SEC_CONST_16BIT)
	#undef CANSM_STOP_SEC_CONST_16BIT
	#undef MEMMAP_ERROR
#elif (defined CANSM_START_SEC_CONST_32BIT)
	#undef CANSM_START_SEC_CONST_32BIT
	#undef MEMMAP_ERROR
#elif (defined CANSM_STOP_SEC_CONST_32BIT)
	#undef CANSM_STOP_SEC_CONST_32BIT
	#undef MEMMAP_ERROR
#elif (defined CANSM_START_SEC_CONST_8BIT)
	#undef CANSM_START_SEC_CONST_8BIT
	#undef MEMMAP_ERROR
#elif (defined CANSM_STOP_SEC_CONST_8BIT)
	#undef CANSM_STOP_SEC_CONST_8BIT
	#undef MEMMAP_ERROR
#elif (defined CANSM_START_SEC_PBCFG)
	#undef CANSM_START_SEC_PBCFG
	#undef MEMMAP_ERROR
#elif (defined CANSM_STOP_SEC_PBCFG)
	#undef CANSM_STOP_SEC_PBCFG
	#undef MEMMAP_ERROR
#elif (defined CANSM_START_SEC_PBCFG_ROOT)
	#undef CANSM_START_SEC_PBCFG_ROOT
	#undef MEMMAP_ERROR
#elif (defined CANSM_STOP_SEC_PBCFG_ROOT)
	#undef CANSM_STOP_SEC_PBCFG_ROOT
	#undef MEMMAP_ERROR
#elif (defined CANSM_START_SEC_VAR_NOINIT_8BIT)
	#undef CANSM_START_SEC_VAR_NOINIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined CANSM_STOP_SEC_VAR_NOINIT_8BIT)
	#undef CANSM_STOP_SEC_VAR_NOINIT_8BIT
	#undef MEMMAP_ERROR

/* Memory section macros for CanTp */
#elif (defined CANTP_START_SEC_CONST_32BIT)
	#undef CANTP_START_SEC_CONST_32BIT
	#undef MEMMAP_ERROR
#elif (defined CANTP_STOP_SEC_CONST_32BIT)
	#undef CANTP_STOP_SEC_CONST_32BIT
	#undef MEMMAP_ERROR
#elif (defined CANTP_START_SEC_CONST_PBCFG_ROOT)
	#undef CANTP_START_SEC_CONST_PBCFG_ROOT
	#undef MEMMAP_ERROR
#elif (defined CANTP_STOP_SEC_CONST_PBCFG_ROOT)
	#undef CANTP_STOP_SEC_CONST_PBCFG_ROOT
	#undef MEMMAP_ERROR
#elif (defined CANTP_START_SEC_CONST_PBCFG)
	#undef CANTP_START_SEC_CONST_PBCFG
	#undef MEMMAP_ERROR
#elif (defined CANTP_STOP_SEC_CONST_PBCFG)
	#undef CANTP_STOP_SEC_CONST_PBCFG
	#undef MEMMAP_ERROR
#elif (defined CANTP_START_SEC_CODE)
	#undef CANTP_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined CANTP_STOP_SEC_CODE)
	#undef CANTP_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined CANTP_START_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef CANTP_START_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined CANTP_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef CANTP_STOP_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined CANTP_START_SEC_VAR_NOINIT_8BIT)
	#undef CANTP_START_SEC_VAR_NOINIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined CANTP_STOP_SEC_VAR_NOINIT_8BIT)
	#undef CANTP_STOP_SEC_VAR_NOINIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined CANTP_START_SEC_VAR_INIT_UNSPECIFIED)
	#undef CANTP_START_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined CANTP_STOP_SEC_VAR_INIT_UNSPECIFIED)
	#undef CANTP_STOP_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR

/* Memory section macros for Can */
#elif (defined CAN_START_SEC_CONST_UNSPECIFIED)
	#undef CAN_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined CAN_STOP_SEC_CONST_UNSPECIFIED)
	#undef CAN_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined CAN_START_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef CAN_START_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined CAN_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef CAN_STOP_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined CAN_START_SEC_STATIC_CODE)
	#undef CAN_START_SEC_STATIC_CODE
	#undef MEMMAP_ERROR
#elif (defined CAN_STOP_SEC_STATIC_CODE)
	#undef CAN_STOP_SEC_STATIC_CODE
	#undef MEMMAP_ERROR
#elif (defined CAN_START_SEC_CODE)
	#undef CAN_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined CAN_STOP_SEC_CODE)
	#undef CAN_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined CAN_START_SEC_CODE_APPL)
	#undef CAN_START_SEC_CODE_APPL
	#undef MEMMAP_ERROR
#elif (defined CAN_STOP_SEC_CODE_APPL)
	#undef CAN_STOP_SEC_CODE_APPL
	#undef MEMMAP_ERROR
#elif (defined CAN_START_SEC_PBCFG)
	#undef CAN_START_SEC_PBCFG
	#undef MEMMAP_ERROR
#elif (defined CAN_STOP_SEC_PBCFG)
	#undef CAN_STOP_SEC_PBCFG
	#undef MEMMAP_ERROR
#elif (defined CAN_START_SEC_PBCFG_ROOT)
	#undef CAN_START_SEC_PBCFG_ROOT
	#undef MEMMAP_ERROR
#elif (defined CAN_STOP_SEC_PBCFG_ROOT)
	#undef CAN_STOP_SEC_PBCFG_ROOT
	#undef MEMMAP_ERROR
#elif (defined CAN_START_SEC_VAR_INIT_UNSPECIFIED)
	#undef CAN_START_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined CAN_STOP_SEC_VAR_INIT_UNSPECIFIED)
	#undef CAN_STOP_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR

/* Memory section macros for Crc */
#elif (defined CRC_START_SEC_CONST_8)
	#undef CRC_START_SEC_CONST_8
	#undef MEMMAP_ERROR
#elif (defined CRC_STOP_SEC_CONST_8)
	#undef CRC_STOP_SEC_CONST_8
	#undef MEMMAP_ERROR
#elif (defined CRC_START_SEC_CONST_16)
	#undef CRC_START_SEC_CONST_16
	#undef MEMMAP_ERROR
#elif (defined CRC_STOP_SEC_CONST_16)
	#undef CRC_STOP_SEC_CONST_16
	#undef MEMMAP_ERROR
#elif (defined CRC_START_SEC_CONST_32)
	#undef CRC_START_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif (defined CRC_STOP_SEC_CONST_32)
	#undef CRC_STOP_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif (defined CRC_START_SEC_CODE)
	#undef CRC_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined CRC_STOP_SEC_CODE)
	#undef CRC_STOP_SEC_CODE
	#undef MEMMAP_ERROR

/* Memory section macros for Det */
#elif (defined DET_START_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef DET_START_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined DET_STOP_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef DET_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined DET_START_SEC_CODE)
	#undef DET_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined DET_STOP_SEC_CODE)
	#undef DET_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined DET_START_SEC_VAR_INIT_8)
	#undef DET_START_SEC_VAR_INIT_8
	#undef MEMMAP_ERROR
#elif (defined DET_STOP_SEC_VAR_INIT_8)
	#undef DET_STOP_SEC_VAR_INIT_8
	#undef MEMMAP_ERROR
#elif (defined DET_START_SEC_VAR_NO_INIT_16)
	#undef DET_START_SEC_VAR_NO_INIT_16
	#undef MEMMAP_ERROR
#elif (defined DET_STOP_SEC_VAR_NO_INIT_16)
	#undef DET_STOP_SEC_VAR_NO_INIT_16
	#undef MEMMAP_ERROR

/* Memory section macros for Dio */
#elif (defined DIO_START_SEC_CODE)
	#undef DIO_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined DIO_STOP_SEC_CODE)
	#undef DIO_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined DIO_START_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef DIO_START_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined DIO_STOP_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef DIO_STOP_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined DIO_START_CONFIG_DATA_UNSPECIFIED)
	#undef DIO_START_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined DIO_STOP_CONFIG_DATA_UNSPECIFIED)
	#undef DIO_STOP_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR

/* Memory section macros for EcuM */
#elif (defined ECUM_START_SEC_CODE)
	#undef ECUM_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined ECUM_STOP_SEC_CODE)
	#undef ECUM_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined ECUM_START_SEC_CONST_UNSPECIFIED)
	#undef ECUM_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ECUM_STOP_SEC_CONST_UNSPECIFIED)
	#undef ECUM_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ECUM_START_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef ECUM_START_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ECUM_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef ECUM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ECUM_START_SEC_VAR_NOINIT_8BIT)
	#undef ECUM_START_SEC_VAR_NOINIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined ECUM_STOP_SEC_VAR_NOINIT_8BIT)
	#undef ECUM_STOP_SEC_VAR_NOINIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined ECUM_START_SEC_VAR_NOINIT_16BIT)
	#undef ECUM_START_SEC_VAR_NOINIT_16BIT
	#undef MEMMAP_ERROR
#elif (defined ECUM_STOP_SEC_VAR_NOINIT_16BIT)
	#undef ECUM_STOP_SEC_VAR_NOINIT_16BIT
	#undef MEMMAP_ERROR
#elif (defined ECUM_START_SEC_CONST_8BIT)
	#undef ECUM_START_SEC_CONST_8BIT
	#undef MEMMAP_ERROR
#elif (defined ECUM_STOP_SEC_CONST_8BIT)
	#undef ECUM_STOP_SEC_CONST_8BIT
	#undef MEMMAP_ERROR
#elif (defined ECUM_START_SEC_CODE_GET_BOOT_TARGET)
	#undef ECUM_START_SEC_CODE_GET_BOOT_TARGET
	#undef MEMMAP_ERROR
#elif (defined ECUM_STOP_SEC_CODE_GET_BOOT_TARGET)
	#undef ECUM_STOP_SEC_CODE_GET_BOOT_TARGET
	#undef MEMMAP_ERROR
#elif (defined ECUM_START_SEC_CODE_SET_BOOT_TARGET)
	#undef ECUM_START_SEC_CODE_SET_BOOT_TARGET
	#undef MEMMAP_ERROR
#elif (defined ECUM_STOP_SEC_CODE_SET_BOOT_TARGET)
	#undef ECUM_STOP_SEC_CODE_SET_BOOT_TARGET
	#undef MEMMAP_ERROR
#elif (defined ECUM_START_SEC_CONST_PBCFG)
	#undef ECUM_START_SEC_CONST_PBCFG
	#undef MEMMAP_ERROR
#elif (defined ECUM_STOP_SEC_CONST_PBCFG)
	#undef ECUM_STOP_SEC_CONST_PBCFG
	#undef MEMMAP_ERROR
#elif (defined ECUM_START_SEC_CONST_PBCFG_ROOT)
	#undef ECUM_START_SEC_CONST_PBCFG_ROOT
	#undef MEMMAP_ERROR
#elif (defined ECUM_STOP_SEC_CONST_PBCFG_ROOT)
	#undef ECUM_STOP_SEC_CONST_PBCFG_ROOT
	#undef MEMMAP_ERROR
#elif (defined ECUM_START_SEC_VAR_INIT_UNSPECIFIED)
	#undef ECUM_START_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ECUM_STOP_SEC_VAR_INIT_UNSPECIFIED)
	#undef ECUM_STOP_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR

/* Memory section macros for Fee */
#elif (defined FEE_START_SEC_CODE)
	#undef FEE_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined FEE_STOP_SEC_CODE)
	#undef FEE_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined FEE_START_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef FEE_START_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined FEE_STOP_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef FEE_STOP_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined FEE_START_CONFIG_DATA_UNSPECIFIED)
	#undef FEE_START_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined FEE_STOP_CONFIG_DATA_UNSPECIFIED)
	#undef FEE_STOP_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined FEE_START_SEC_VAR_INIT_16)
	#undef FEE_START_SEC_VAR_INIT_16
	#undef MEMMAP_ERROR
#elif (defined FEE_STOP_SEC_VAR_INIT_16)
	#undef FEE_STOP_SEC_VAR_INIT_16
	#undef MEMMAP_ERROR
#elif (defined FEE_START_SEC_VAR_INIT_32)
	#undef FEE_START_SEC_VAR_INIT_32
	#undef MEMMAP_ERROR
#elif (defined FEE_STOP_SEC_VAR_INIT_32)
	#undef FEE_STOP_SEC_VAR_INIT_32
	#undef MEMMAP_ERROR
#elif (defined FEE_START_SEC_VAR_INIT_8)
	#undef FEE_START_SEC_VAR_INIT_8
	#undef MEMMAP_ERROR
#elif (defined FEE_STOP_SEC_VAR_INIT_8)
	#undef FEE_STOP_SEC_VAR_INIT_8
	#undef MEMMAP_ERROR
#elif (defined FEE_START_SEC_VAR_INIT_UNSPECIFIED)
	#undef FEE_START_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined FEE_STOP_SEC_VAR_INIT_UNSPECIFIED)
	#undef FEE_STOP_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined FEE_START_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef FEE_START_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined FEE_STOP_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef FEE_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR

/* Memory section macros for FiM */
#elif (defined FIM_START_SEC_CONST_UNSPECIFIED)
	#undef FIM_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined FIM_STOP_SEC_CONST_UNSPECIFIED)
	#undef FIM_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined FIM_START_SEC_CODE)
	#undef FIM_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined FIM_STOP_SEC_CODE)
	#undef FIM_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined FIM_START_SEC_VAR_INIT_8)
	#undef FIM_START_SEC_VAR_INIT_8
	#undef MEMMAP_ERROR
#elif (defined FIM_STOP_SEC_VAR_INIT_8)
	#undef FIM_STOP_SEC_VAR_INIT_8
	#undef MEMMAP_ERROR
#elif (defined FIM_START_SEC_VAR_NO_INIT_8)
	#undef FIM_START_SEC_VAR_NO_INIT_8
	#undef MEMMAP_ERROR
#elif (defined FIM_STOP_SEC_VAR_NO_INIT_8)
	#undef FIM_STOP_SEC_VAR_NO_INIT_8
	#undef MEMMAP_ERROR

/* Memory section macros for Fls */
#elif (defined FLS_START_SEC_CODE)
	#undef FLS_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined FLS_STOP_SEC_CODE)
	#undef FLS_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined FLS_START_SEC_CODE_AC)
	#undef FLS_START_SEC_CODE_AC
	#undef MEMMAP_ERROR
#elif (defined FLS_STOP_SEC_CODE_AC)
	#undef FLS_STOP_SEC_CODE_AC
	#undef MEMMAP_ERROR
#elif (defined FLS_START_SEC_CONFIG_DATA_8)
	#undef FLS_START_SEC_CONFIG_DATA_8
	#undef MEMMAP_ERROR
#elif (defined FLS_STOP_SEC_CONFIG_DATA_8)
	#undef FLS_STOP_SEC_CONFIG_DATA_8
	#undef MEMMAP_ERROR
#elif (defined FLS_START_CONFIG_DATA_8)
	#undef FLS_START_CONFIG_DATA_8
	#undef MEMMAP_ERROR
#elif (defined FLS_STOP_CONFIG_DATA_8)
	#undef FLS_STOP_CONFIG_DATA_8
	#undef MEMMAP_ERROR
#elif (defined FLS_START_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef FLS_START_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined FLS_STOP_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef FLS_STOP_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined FLS_START_CONFIG_DATA_UNSPECIFIED)
	#undef FLS_START_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined FLS_STOP_CONFIG_DATA_UNSPECIFIED)
	#undef FLS_STOP_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined FLS_START_SEC_CONST_32)
	#undef FLS_START_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif (defined FLS_STOP_SEC_CONST_32)
	#undef FLS_STOP_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif (defined FLS_START_SEC_CONST_UNSPECIFIED)
	#undef FLS_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined FLS_STOP_SEC_CONST_UNSPECIFIED)
	#undef FLS_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined FLS_START_SEC_VAR_INIT_32)
	#undef FLS_START_SEC_VAR_INIT_32
	#undef MEMMAP_ERROR
#elif (defined FLS_STOP_SEC_VAR_INIT_32)
	#undef FLS_STOP_SEC_VAR_INIT_32
	#undef MEMMAP_ERROR
#elif (defined FLS_START_SEC_VAR_INIT_8)
	#undef FLS_START_SEC_VAR_INIT_8
	#undef MEMMAP_ERROR
#elif (defined FLS_STOP_SEC_VAR_INIT_8)
	#undef FLS_STOP_SEC_VAR_INIT_8
	#undef MEMMAP_ERROR
#elif (defined FLS_START_SEC_VAR_INIT_BOOLEAN)
	#undef FLS_START_SEC_VAR_INIT_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined FLS_STOP_SEC_VAR_INIT_BOOLEAN)
	#undef FLS_STOP_SEC_VAR_INIT_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined FLS_START_SEC_VAR_INIT_UNSPECIFIED)
	#undef FLS_START_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined FLS_STOP_SEC_VAR_INIT_UNSPECIFIED)
	#undef FLS_STOP_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR

/* Memory section macros for Gpt */
#elif (defined GPT_START_SEC_CODE)
	#undef GPT_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined GPT_STOP_SEC_CODE)
	#undef GPT_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined GPT_START_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef GPT_START_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined GPT_STOP_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef GPT_STOP_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined GPT_START_CONFIG_DATA_UNSPECIFIED)
	#undef GPT_START_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined GPT_STOP_CONFIG_DATA_UNSPECIFIED)
	#undef GPT_STOP_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined GPT_START_SEC_CONST_32)
	#undef GPT_START_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif (defined GPT_STOP_SEC_CONST_32)
	#undef GPT_STOP_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif (defined GPT_START_SEC_VAR_INIT_32)
	#undef GPT_START_SEC_VAR_INIT_32
	#undef MEMMAP_ERROR
#elif (defined GPT_STOP_SEC_VAR_INIT_32)
	#undef GPT_STOP_SEC_VAR_INIT_32
	#undef MEMMAP_ERROR
#elif (defined GPT_START_SEC_VAR_INIT_UNSPECIFIED)
	#undef GPT_START_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined GPT_STOP_SEC_VAR_INIT_UNSPECIFIED)
	#undef GPT_STOP_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined GPT_START_SEC_VAR_NO_INIT_32)
	#undef GPT_START_SEC_VAR_NO_INIT_32
	#undef MEMMAP_ERROR
#elif (defined GPT_STOP_SEC_VAR_NO_INIT_32)
	#undef GPT_STOP_SEC_VAR_NO_INIT_32
	#undef MEMMAP_ERROR
#elif (defined GPT_START_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef GPT_START_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined GPT_STOP_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef GPT_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR

/* Memory section macros for Icu */
#elif (defined ICU_START_SEC_CODE)
	#undef ICU_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined ICU_STOP_SEC_CODE)
	#undef ICU_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined ICU_START_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef ICU_START_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ICU_STOP_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef ICU_STOP_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ICU_START_CONFIG_DATA_UNSPECIFIED)
	#undef ICU_START_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ICU_STOP_CONFIG_DATA_UNSPECIFIED)
	#undef ICU_STOP_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ICU_START_SEC_VAR_INIT_32)
	#undef ICU_START_SEC_VAR_INIT_32
	#undef MEMMAP_ERROR
#elif (defined ICU_STOP_SEC_VAR_INIT_32)
	#undef ICU_STOP_SEC_VAR_INIT_32
	#undef MEMMAP_ERROR
#elif (defined ICU_START_SEC_VAR_INIT_UNSPECIFIED)
	#undef ICU_START_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ICU_STOP_SEC_VAR_INIT_UNSPECIFIED)
	#undef ICU_STOP_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ICU_START_SEC_VAR_NO_INIT_32_NO_CACHEABLE)
	#undef ICU_START_SEC_VAR_NO_INIT_32_NO_CACHEABLE
	#undef MEMMAP_ERROR
#elif (defined ICU_STOP_SEC_VAR_NO_INIT_32_NO_CACHEABLE)
	#undef ICU_STOP_SEC_VAR_NO_INIT_32_NO_CACHEABLE
	#undef MEMMAP_ERROR
#elif (defined ICU_START_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef ICU_START_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ICU_STOP_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef ICU_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined ICU_START_SEC_VAR_NO_INIT_UNSPECIFIED_NO_CACHEABLE)
	#undef ICU_START_SEC_VAR_NO_INIT_UNSPECIFIED_NO_CACHEABLE
	#undef MEMMAP_ERROR
#elif (defined ICU_STOP_SEC_VAR_NO_INIT_UNSPECIFIED_NO_CACHEABLE)
	#undef ICU_STOP_SEC_VAR_NO_INIT_UNSPECIFIED_NO_CACHEABLE
	#undef MEMMAP_ERROR

/* Memory section macros for Mcl */
#elif (defined MCL_START_SEC_CODE)
	#undef MCL_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined MCL_STOP_SEC_CODE)
	#undef MCL_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined MCL_START_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef MCL_START_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined MCL_STOP_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef MCL_STOP_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined MCL_START_CONFIG_DATA_UNSPECIFIED)
	#undef MCL_START_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined MCL_STOP_CONFIG_DATA_UNSPECIFIED)
	#undef MCL_STOP_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined MCL_START_SEC_CONST_32)
	#undef MCL_START_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif (defined MCL_STOP_SEC_CONST_32)
	#undef MCL_STOP_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif (defined MCL_START_SEC_CONST_UNSPECIFIED)
	#undef MCL_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined MCL_STOP_SEC_CONST_UNSPECIFIED)
	#undef MCL_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined MCL_START_SEC_VAR_INIT_UNSPECIFIED)
	#undef MCL_START_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined MCL_STOP_SEC_VAR_INIT_UNSPECIFIED)
	#undef MCL_STOP_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR

/* Memory section macros for Mcu */
#elif (defined MCU_START_SEC_CODE)
	#undef MCU_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined MCU_STOP_SEC_CODE)
	#undef MCU_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined MCU_START_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef MCU_START_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined MCU_STOP_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef MCU_STOP_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined MCU_START_CONFIG_DATA_UNSPECIFIED)
	#undef MCU_START_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined MCU_STOP_CONFIG_DATA_UNSPECIFIED)
	#undef MCU_STOP_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined MCU_START_SEC_CONST_32)
	#undef MCU_START_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif (defined MCU_STOP_SEC_CONST_32)
	#undef MCU_STOP_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif (defined MCU_START_SEC_RAMCODE)
	#undef MCU_START_SEC_RAMCODE
	#undef MEMMAP_ERROR
#elif (defined MCU_STOP_SEC_RAMCODE)
	#undef MCU_STOP_SEC_RAMCODE
	#undef MEMMAP_ERROR
#elif (defined MCU_START_SEC_VAR_INIT_32)
	#undef MCU_START_SEC_VAR_INIT_32
	#undef MEMMAP_ERROR
#elif (defined MCU_STOP_SEC_VAR_INIT_32)
	#undef MCU_STOP_SEC_VAR_INIT_32
	#undef MEMMAP_ERROR
#elif (defined MCU_START_SEC_VAR_INIT_UNSPECIFIED)
	#undef MCU_START_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined MCU_STOP_SEC_VAR_INIT_UNSPECIFIED)
	#undef MCU_STOP_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined MCU_START_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef MCU_START_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined MCU_STOP_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef MCU_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined MCU_START_SEC_VAR_NO_INIT_8)
	#undef MCU_START_SEC_VAR_NO_INIT_8
	#undef MEMMAP_ERROR
#elif (defined MCU_STOP_SEC_VAR_NO_INIT_8)
	#undef MCU_STOP_SEC_VAR_NO_INIT_8
	#undef MEMMAP_ERROR

/* Memory section macros for MemIf */
#elif (defined MEMIF_START_SEC_CODE)
	#undef MEMIF_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined MEMIF_STOP_SEC_CODE)
	#undef MEMIF_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined MEMIF_START_SEC_CONST_UNSPECIFIED)
	#undef MEMIF_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined MEMIF_STOP_SEC_CONST_UNSPECIFIED)
	#undef MEMIF_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR

/* Memory section macros for PduR */
#elif (defined PDUR_START_SEC_CODE)
	#undef PDUR_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined PDUR_STOP_SEC_CODE)
	#undef PDUR_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined PDUR_START_SEC_CONST_16BIT)
	#undef PDUR_START_SEC_CONST_16BIT
	#undef MEMMAP_ERROR
#elif (defined PDUR_STOP_SEC_CONST_16BIT)
	#undef PDUR_STOP_SEC_CONST_16BIT
	#undef MEMMAP_ERROR
#elif (defined PDUR_START_SEC_CONST_32BIT)
	#undef PDUR_START_SEC_CONST_32BIT
	#undef MEMMAP_ERROR
#elif (defined PDUR_STOP_SEC_CONST_32BIT)
	#undef PDUR_STOP_SEC_CONST_32BIT
	#undef MEMMAP_ERROR
#elif (defined PDUR_START_SEC_CONST_8BIT)
	#undef PDUR_START_SEC_CONST_8BIT
	#undef MEMMAP_ERROR
#elif (defined PDUR_STOP_SEC_CONST_8BIT)
	#undef PDUR_STOP_SEC_CONST_8BIT
	#undef MEMMAP_ERROR
#elif (defined PDUR_START_SEC_CONST_UNSPECIFIED)
	#undef PDUR_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined PDUR_STOP_SEC_CONST_UNSPECIFIED)
	#undef PDUR_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined PDUR_START_SEC_PBCFG)
	#undef PDUR_START_SEC_PBCFG
	#undef MEMMAP_ERROR
#elif (defined PDUR_STOP_SEC_PBCFG)
	#undef PDUR_STOP_SEC_PBCFG
	#undef MEMMAP_ERROR
#elif (defined PDUR_START_SEC_PBCFG_ROOT)
	#undef PDUR_START_SEC_PBCFG_ROOT
	#undef MEMMAP_ERROR
#elif (defined PDUR_STOP_SEC_PBCFG_ROOT)
	#undef PDUR_STOP_SEC_PBCFG_ROOT
	#undef MEMMAP_ERROR
#elif (defined PDUR_START_SEC_VAR_NOINIT_8BIT)
	#undef PDUR_START_SEC_VAR_NOINIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined PDUR_STOP_SEC_VAR_NOINIT_8BIT)
	#undef PDUR_STOP_SEC_VAR_NOINIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined PDUR_START_SEC_VAR_NOINIT_BOOLEAN)
	#undef PDUR_START_SEC_VAR_NOINIT_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined PDUR_STOP_SEC_VAR_NOINIT_BOOLEAN)
	#undef PDUR_STOP_SEC_VAR_NOINIT_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined PDUR_START_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef PDUR_START_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined PDUR_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef PDUR_STOP_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined PDUR_START_SEC_VAR_ZERO_INIT_UNSPECIFIED)
	#undef PDUR_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined PDUR_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED)
	#undef PDUR_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR

/* Memory section macros for Port */
#elif (defined PORT_START_SEC_CODE)
	#undef PORT_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined PORT_STOP_SEC_CODE)
	#undef PORT_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined PORT_START_SEC_CONFIG_DATA_16)
	#undef PORT_START_SEC_CONFIG_DATA_16
	#undef MEMMAP_ERROR
#elif (defined PORT_STOP_SEC_CONFIG_DATA_16)
	#undef PORT_STOP_SEC_CONFIG_DATA_16
	#undef MEMMAP_ERROR
#elif (defined PORT_START_CONFIG_DATA_16)
	#undef PORT_START_CONFIG_DATA_16
	#undef MEMMAP_ERROR
#elif (defined PORT_STOP_CONFIG_DATA_16)
	#undef PORT_STOP_CONFIG_DATA_16
	#undef MEMMAP_ERROR
#elif (defined PORT_START_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef PORT_START_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined PORT_STOP_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef PORT_STOP_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined PORT_START_CONFIG_DATA_UNSPECIFIED)
	#undef PORT_START_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined PORT_STOP_CONFIG_DATA_UNSPECIFIED)
	#undef PORT_STOP_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined PORT_START_SEC_VAR_INIT_UNSPECIFIED)
	#undef PORT_START_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined PORT_STOP_SEC_VAR_INIT_UNSPECIFIED)
	#undef PORT_STOP_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined PORT_START_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef PORT_START_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined PORT_STOP_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef PORT_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined PORT_START_SEC_VAR_NO_INIT_16)
	#undef PORT_START_SEC_VAR_NO_INIT_16
	#undef MEMMAP_ERROR
#elif (defined PORT_STOP_SEC_VAR_NO_INIT_16)
	#undef PORT_STOP_SEC_VAR_NO_INIT_16
	#undef MEMMAP_ERROR

/* Memory section macros for Pwm */
#elif (defined PWM_START_SEC_CODE)
	#undef PWM_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined PWM_STOP_SEC_CODE)
	#undef PWM_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined PWM_START_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef PWM_START_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined PWM_STOP_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef PWM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined PWM_START_CONFIG_DATA_UNSPECIFIED)
	#undef PWM_START_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined PWM_STOP_CONFIG_DATA_UNSPECIFIED)
	#undef PWM_STOP_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined PWM_START_SEC_CONST_16)
	#undef PWM_START_SEC_CONST_16
	#undef MEMMAP_ERROR
#elif (defined PWM_STOP_SEC_CONST_16)
	#undef PWM_STOP_SEC_CONST_16
	#undef MEMMAP_ERROR
#elif (defined PWM_START_SEC_CONST_32)
	#undef PWM_START_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif (defined PWM_STOP_SEC_CONST_32)
	#undef PWM_STOP_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif (defined PWM_START_SEC_VAR_INIT_8)
	#undef PWM_START_SEC_VAR_INIT_8
	#undef MEMMAP_ERROR
#elif (defined PWM_STOP_SEC_VAR_INIT_8)
	#undef PWM_STOP_SEC_VAR_INIT_8
	#undef MEMMAP_ERROR
#elif (defined PWM_START_SEC_VAR_INIT_UNSPECIFIED)
	#undef PWM_START_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined PWM_STOP_SEC_VAR_INIT_UNSPECIFIED)
	#undef PWM_STOP_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined PWM_START_SEC_VAR_NO_INIT_16)
	#undef PWM_START_SEC_VAR_NO_INIT_16
	#undef MEMMAP_ERROR
#elif (defined PWM_STOP_SEC_VAR_NO_INIT_16)
	#undef PWM_STOP_SEC_VAR_NO_INIT_16
	#undef MEMMAP_ERROR
#elif (defined PWM_START_SEC_VAR_NO_INIT_8)
	#undef PWM_START_SEC_VAR_NO_INIT_8
	#undef MEMMAP_ERROR
#elif (defined PWM_STOP_SEC_VAR_NO_INIT_8)
	#undef PWM_STOP_SEC_VAR_NO_INIT_8
	#undef MEMMAP_ERROR
#elif (defined PWM_START_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef PWM_START_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined PWM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef PWM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR

/* Memory section macros for Spi */
#elif (defined SPI_START_SEC_CODE)
	#undef SPI_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined SPI_STOP_SEC_CODE)
	#undef SPI_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined SPI_START_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef SPI_START_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined SPI_STOP_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef SPI_STOP_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined SPI_START_CONFIG_DATA_UNSPECIFIED)
	#undef SPI_START_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined SPI_STOP_CONFIG_DATA_UNSPECIFIED)
	#undef SPI_STOP_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined SPI_START_SEC_CONST_32)
	#undef SPI_START_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif (defined SPI_STOP_SEC_CONST_32)
	#undef SPI_STOP_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif (defined SPI_START_SEC_VAR_INIT_32)
	#undef SPI_START_SEC_VAR_INIT_32
	#undef MEMMAP_ERROR
#elif (defined SPI_STOP_SEC_VAR_INIT_32)
	#undef SPI_STOP_SEC_VAR_INIT_32
	#undef MEMMAP_ERROR
#elif (defined SPI_START_SEC_VAR_INIT_UNSPECIFIED)
	#undef SPI_START_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined SPI_STOP_SEC_VAR_INIT_UNSPECIFIED)
	#undef SPI_STOP_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined SPI_START_SEC_VAR_NO_INIT_32)
	#undef SPI_START_SEC_VAR_NO_INIT_32
	#undef MEMMAP_ERROR
#elif (defined SPI_STOP_SEC_VAR_NO_INIT_32)
	#undef SPI_STOP_SEC_VAR_NO_INIT_32
	#undef MEMMAP_ERROR
#elif (defined SPI_START_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef SPI_START_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined SPI_STOP_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef SPI_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined SPI_START_SEC_VAR_NO_INIT_UNSPECIFIED_NO_CACHEABLE)
	#undef SPI_START_SEC_VAR_NO_INIT_UNSPECIFIED_NO_CACHEABLE
	#undef MEMMAP_ERROR
#elif (defined SPI_STOP_SEC_VAR_NO_INIT_UNSPECIFIED_NO_CACHEABLE)
	#undef SPI_STOP_SEC_VAR_NO_INIT_UNSPECIFIED_NO_CACHEABLE
	#undef MEMMAP_ERROR

/* Memory section macros for WdgIf */
#elif (defined WDGIF_START_SEC_CODE)
	#undef WDGIF_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined WDGIF_STOP_SEC_CODE)
	#undef WDGIF_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined WDGIF_START_SEC_CONST_UNSPECIFIED)
	#undef WDGIF_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined WDGIF_STOP_SEC_CONST_UNSPECIFIED)
	#undef WDGIF_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR

/* Memory section macros for WdgM */
#elif (defined WDGM_START_SEC_CODE)
	#undef WDGM_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined WDGM_STOP_SEC_CODE)
	#undef WDGM_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined WDGM_START_SEC_CONST_8)
	#undef WDGM_START_SEC_CONST_8
	#undef MEMMAP_ERROR
#elif (defined WDGM_STOP_SEC_CONST_8)
	#undef WDGM_STOP_SEC_CONST_8
	#undef MEMMAP_ERROR
#elif (defined WDGM_START_SEC_CONST_16)
	#undef WDGM_START_SEC_CONST_16
	#undef MEMMAP_ERROR
#elif (defined WDGM_STOP_SEC_CONST_16)
	#undef WDGM_STOP_SEC_CONST_16
	#undef MEMMAP_ERROR
#elif (defined WDGM_START_SEC_CONST_UNSPECIFIED)
	#undef WDGM_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined WDGM_STOP_SEC_CONST_UNSPECIFIED)
	#undef WDGM_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined WDGM_START_SEC_VAR_INIT_UNSPECIFIED)
	#undef WDGM_START_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined WDGM_STOP_SEC_VAR_INIT_UNSPECIFIED)
	#undef WDGM_STOP_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined WDGM_START_SEC_VAR_NO_INIT_16)
	#undef WDGM_START_SEC_VAR_NO_INIT_16
	#undef MEMMAP_ERROR
#elif (defined WDGM_STOP_SEC_VAR_NO_INIT_16)
	#undef WDGM_STOP_SEC_VAR_NO_INIT_16
	#undef MEMMAP_ERROR
#elif (defined WDGM_START_SEC_VAR_NO_INIT_32)
	#undef WDGM_START_SEC_VAR_NO_INIT_32
	#undef MEMMAP_ERROR
#elif (defined WDGM_STOP_SEC_VAR_NO_INIT_32)
	#undef WDGM_STOP_SEC_VAR_NO_INIT_32
	#undef MEMMAP_ERROR
#elif (defined WDGM_START_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef WDGM_START_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined WDGM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef WDGM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined WDGM_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED)
	#undef WDGM_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined WDGM_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED)
	#undef WDGM_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR

/* Memory section macros for Wdg */
#elif (defined WDG_START_SEC_CODE)
	#undef WDG_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined WDG_STOP_SEC_CODE)
	#undef WDG_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined WDG_START_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef WDG_START_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined WDG_STOP_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef WDG_STOP_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined WDG_START_CONFIG_DATA_UNSPECIFIED)
	#undef WDG_START_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined WDG_STOP_CONFIG_DATA_UNSPECIFIED)
	#undef WDG_STOP_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined WDG_START_SEC_CONFIG_DATA_8)
	#undef WDG_START_SEC_CONFIG_DATA_8
	#undef MEMMAP_ERROR
#elif (defined WDG_STOP_SEC_CONFIG_DATA_8)
	#undef WDG_STOP_SEC_CONFIG_DATA_8
	#undef MEMMAP_ERROR
#elif (defined WDG_START_CONFIG_DATA_8)
	#undef WDG_START_CONFIG_DATA_8
	#undef MEMMAP_ERROR
#elif (defined WDG_STOP_CONFIG_DATA_8)
	#undef WDG_STOP_CONFIG_DATA_8
	#undef MEMMAP_ERROR
#elif (defined WDG_START_SEC_CONST_32)
	#undef WDG_START_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif (defined WDG_STOP_SEC_CONST_32)
	#undef WDG_STOP_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif (defined WDG_START_SEC_CONST_8)
	#undef WDG_START_SEC_CONST_8
	#undef MEMMAP_ERROR
#elif (defined WDG_STOP_SEC_CONST_8)
	#undef WDG_STOP_SEC_CONST_8
	#undef MEMMAP_ERROR
#elif (defined WDG_START_SEC_CONST_UNSPECIFIED)
	#undef WDG_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined WDG_STOP_SEC_CONST_UNSPECIFIED)
	#undef WDG_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined WDG_START_SEC_RAMCODE)
	#undef WDG_START_SEC_RAMCODE
	#undef MEMMAP_ERROR
#elif (defined WDG_STOP_SEC_RAMCODE)
	#undef WDG_STOP_SEC_RAMCODE
	#undef MEMMAP_ERROR
#elif (defined WDG_START_SEC_VAR_INIT_16)
	#undef WDG_START_SEC_VAR_INIT_16
	#undef MEMMAP_ERROR
#elif (defined WDG_STOP_SEC_VAR_INIT_16)
	#undef WDG_STOP_SEC_VAR_INIT_16
	#undef MEMMAP_ERROR
#elif (defined WDG_START_SEC_VAR_INIT_UNSPECIFIED)
	#undef WDG_START_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined WDG_STOP_SEC_VAR_INIT_UNSPECIFIED)
	#undef WDG_STOP_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined WDG_START_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef WDG_START_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined WDG_STOP_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef WDG_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR

/* Memory section macros for Xcp */
#elif (defined XCP_START_SEC_CONST_16BIT)
	#undef XCP_START_SEC_CONST_16BIT
	#undef MEMMAP_ERROR
#elif (defined XCP_STOP_SEC_CONST_16BIT)
	#undef XCP_STOP_SEC_CONST_16BIT
	#undef MEMMAP_ERROR
#elif (defined XCP_START_SEC_CONST_8BIT)
	#undef XCP_START_SEC_CONST_8BIT
	#undef MEMMAP_ERROR
#elif (defined XCP_STOP_SEC_CONST_8BIT)
	#undef XCP_STOP_SEC_CONST_8BIT
	#undef MEMMAP_ERROR
#elif (defined XCP_START_SEC_CONST_UNSPECIFIED)
	#undef XCP_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined XCP_STOP_SEC_CONST_UNSPECIFIED)
	#undef XCP_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined XCP_START_SEC_VAR_16BIT)
	#undef XCP_START_SEC_VAR_16BIT
	#undef MEMMAP_ERROR
#elif (defined XCP_STOP_SEC_VAR_16BIT)
	#undef XCP_STOP_SEC_VAR_16BIT
	#undef MEMMAP_ERROR
#elif (defined XCP_START_SEC_VAR_8BIT)
	#undef XCP_START_SEC_VAR_8BIT
	#undef MEMMAP_ERROR
#elif (defined XCP_STOP_SEC_VAR_8BIT)
	#undef XCP_STOP_SEC_VAR_8BIT
	#undef MEMMAP_ERROR
#elif (defined XCP_START_SEC_VAR_UNSPECIFIED)
	#undef XCP_START_SEC_VAR_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined XCP_STOP_SEC_VAR_UNSPECIFIED)
	#undef XCP_STOP_SEC_VAR_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined XCP_START_SEC_VAR_NOINIT_16BIT)
	#undef XCP_START_SEC_VAR_NOINIT_16BIT
	#undef MEMMAP_ERROR
#elif (defined XCP_STOP_SEC_VAR_NOINIT_16BIT)
	#undef XCP_STOP_SEC_VAR_NOINIT_16BIT
	#undef MEMMAP_ERROR
#elif (defined XCP_START_SEC_VAR_NOINIT_8BIT)
	#undef XCP_START_SEC_VAR_NOINIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined XCP_STOP_SEC_VAR_NOINIT_8BIT)
	#undef XCP_STOP_SEC_VAR_NOINIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined XCP_START_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef XCP_START_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined XCP_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef XCP_STOP_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined XCP_START_SEC_CODE)
	#undef XCP_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined XCP_STOP_SEC_CODE)
	#undef XCP_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined XCP_START_SEC_APPL_CODE)
	#undef XCP_START_SEC_APPL_CODE
	#undef MEMMAP_ERROR
#elif (defined XCP_STOP_SEC_APPL_CODE)
	#undef XCP_STOP_SEC_APPL_CODE
	#undef MEMMAP_ERROR
#elif (defined XCP_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED)
	#undef XCP_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined XCP_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED)
	#undef XCP_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
	#undef MEMMAP_ERROR

/* Memory section macros for Rte */
#elif (defined RTE_START_SEC_CODE)
	#undef RTE_START_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_CODE)
	#undef RTE_STOP_SEC_CODE
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_APPL_CODE)
	#undef RTE_START_SEC_APPL_CODE
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_APPL_CODE)
	#undef RTE_STOP_SEC_APPL_CODE
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_CALLOUT_CODE)
	#undef RTE_START_SEC_CALLOUT_CODE
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_CALLOUT_CODE)
	#undef RTE_STOP_SEC_CALLOUT_CODE
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_NO_INIT_BOOLEAN)
	#undef RTE_START_SEC_VAR_NO_INIT_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_NO_INIT_BOOLEAN)
	#undef RTE_STOP_SEC_VAR_NO_INIT_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_NO_INIT_8)
	#undef RTE_START_SEC_VAR_NO_INIT_8
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_NO_INIT_8)
	#undef RTE_STOP_SEC_VAR_NO_INIT_8
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_NO_INIT_16)
	#undef RTE_START_SEC_VAR_NO_INIT_16
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_NO_INIT_16)
	#undef RTE_STOP_SEC_VAR_NO_INIT_16
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_NO_INIT_32)
	#undef RTE_START_SEC_VAR_NO_INIT_32
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_NO_INIT_32)
	#undef RTE_STOP_SEC_VAR_NO_INIT_32
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef RTE_START_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_NO_INIT_UNSPECIFIED)
	#undef RTE_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_NOINIT_BOOLEAN)
	#undef RTE_START_SEC_VAR_NOINIT_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_NOINIT_BOOLEAN)
	#undef RTE_STOP_SEC_VAR_NOINIT_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_NOINIT_8BIT)
	#undef RTE_START_SEC_VAR_NOINIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_NOINIT_8BIT)
	#undef RTE_STOP_SEC_VAR_NOINIT_8BIT
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_NOINIT_16BIT)
	#undef RTE_START_SEC_VAR_NOINIT_16BIT
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_NOINIT_16BIT)
	#undef RTE_STOP_SEC_VAR_NOINIT_16BIT
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef RTE_START_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
	#undef RTE_STOP_SEC_VAR_NOINIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_CLEARED_BOOLEAN)
	#undef RTE_START_SEC_VAR_CLEARED_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_CLEARED_BOOLEAN)
	#undef RTE_STOP_SEC_VAR_CLEARED_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_CLEARED_8)
	#undef RTE_START_SEC_VAR_CLEARED_8
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_CLEARED_8)
	#undef RTE_STOP_SEC_VAR_CLEARED_8
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_CLEARED_16)
	#undef RTE_START_SEC_VAR_CLEARED_16
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_CLEARED_16)
	#undef RTE_STOP_SEC_VAR_CLEARED_16
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_CLEARED_32)
	#undef RTE_START_SEC_VAR_CLEARED_32
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_CLEARED_32)
	#undef RTE_STOP_SEC_VAR_CLEARED_32
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_CLEARED_UNSPECIFIED)
	#undef RTE_START_SEC_VAR_CLEARED_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_CLEARED_UNSPECIFIED)
	#undef RTE_STOP_SEC_VAR_CLEARED_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN)
	#undef RTE_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN)
	#undef RTE_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_POWER_ON_CLEARED_8)
	#undef RTE_START_SEC_VAR_POWER_ON_CLEARED_8
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_POWER_ON_CLEARED_8)
	#undef RTE_STOP_SEC_VAR_POWER_ON_CLEARED_8
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_POWER_ON_CLEARED_16)
	#undef RTE_START_SEC_VAR_POWER_ON_CLEARED_16
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_POWER_ON_CLEARED_16)
	#undef RTE_STOP_SEC_VAR_POWER_ON_CLEARED_16
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_POWER_ON_CLEARED_32)
	#undef RTE_START_SEC_VAR_POWER_ON_CLEARED_32
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_POWER_ON_CLEARED_32)
	#undef RTE_STOP_SEC_VAR_POWER_ON_CLEARED_32
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED)
	#undef RTE_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED)
	#undef RTE_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_INIT_BOOLEAN)
	#undef RTE_START_SEC_VAR_INIT_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_INIT_BOOLEAN)
	#undef RTE_STOP_SEC_VAR_INIT_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_INIT_8)
	#undef RTE_START_SEC_VAR_INIT_8
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_INIT_8)
	#undef RTE_STOP_SEC_VAR_INIT_8
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_INIT_16)
	#undef RTE_START_SEC_VAR_INIT_16
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_INIT_16)
	#undef RTE_STOP_SEC_VAR_INIT_16
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_INIT_32)
	#undef RTE_START_SEC_VAR_INIT_32
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_INIT_32)
	#undef RTE_STOP_SEC_VAR_INIT_32
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_INIT_UNSPECIFIED)
	#undef RTE_START_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_INIT_UNSPECIFIED)
	#undef RTE_STOP_SEC_VAR_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_POWER_ON_INIT_BOOLEAN)
	#undef RTE_START_SEC_VAR_POWER_ON_INIT_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN)
	#undef RTE_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_POWER_ON_INIT_8)
	#undef RTE_START_SEC_VAR_POWER_ON_INIT_8
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_POWER_ON_INIT_8)
	#undef RTE_STOP_SEC_VAR_POWER_ON_INIT_8
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_POWER_ON_INIT_16)
	#undef RTE_START_SEC_VAR_POWER_ON_INIT_16
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_POWER_ON_INIT_16)
	#undef RTE_STOP_SEC_VAR_POWER_ON_INIT_16
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_POWER_ON_INIT_32)
	#undef RTE_START_SEC_VAR_POWER_ON_INIT_32
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_POWER_ON_INIT_32)
	#undef RTE_STOP_SEC_VAR_POWER_ON_INIT_32
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED)
	#undef RTE_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED)
	#undef RTE_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_CONST_BOOLEAN)
	#undef RTE_START_SEC_CONST_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_CONST_BOOLEAN)
	#undef RTE_STOP_SEC_CONST_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_CONST_8)
	#undef RTE_START_SEC_CONST_8
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_CONST_8)
	#undef RTE_STOP_SEC_CONST_8
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_CONST_16)
	#undef RTE_START_SEC_CONST_16
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_CONST_16)
	#undef RTE_STOP_SEC_CONST_16
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_CONST_32)
	#undef RTE_START_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_CONST_32)
	#undef RTE_STOP_SEC_CONST_32
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_CONST_UNSPECIFIED)
	#undef RTE_START_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_CONST_UNSPECIFIED)
	#undef RTE_STOP_SEC_CONST_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_CONST_8BIT)
	#undef RTE_START_SEC_CONST_8BIT
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_CONST_8BIT)
	#undef RTE_STOP_SEC_CONST_8BIT
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_CONST_16BIT)
	#undef RTE_START_SEC_CONST_16BIT
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_CONST_16BIT)
	#undef RTE_STOP_SEC_CONST_16BIT
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_CONST_32BIT)
	#undef RTE_START_SEC_CONST_32BIT
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_CONST_32BIT)
	#undef RTE_STOP_SEC_CONST_32BIT
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_BOOLEAN)
	#undef RTE_START_SEC_VAR_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_BOOLEAN)
	#undef RTE_STOP_SEC_VAR_BOOLEAN
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_8BIT)
	#undef RTE_START_SEC_VAR_8BIT
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_8BIT)
	#undef RTE_STOP_SEC_VAR_8BIT
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_16BIT)
	#undef RTE_START_SEC_VAR_16BIT
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_16BIT)
	#undef RTE_STOP_SEC_VAR_16BIT
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_32BIT)
	#undef RTE_START_SEC_VAR_32BIT
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_32BIT)
	#undef RTE_STOP_SEC_VAR_32BIT
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_VAR_UNSPECIFIED)
	#undef RTE_START_SEC_VAR_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_VAR_UNSPECIFIED)
	#undef RTE_STOP_SEC_VAR_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined RTE_START_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef RTE_START_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_SEC_CONFIG_DATA_UNSPECIFIED)
	#undef RTE_STOP_SEC_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined RTE_START_CONFIG_DATA_UNSPECIFIED)
	#undef RTE_START_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#elif (defined RTE_STOP_CONFIG_DATA_UNSPECIFIED)
	#undef RTE_STOP_CONFIG_DATA_UNSPECIFIED
	#undef MEMMAP_ERROR
#endif

#include <Common_MemMap.h>
#ifdef MEMMAP_ERROR
#error MEMMAP_ERROR defined, wrong MemMap.h usage
#endif
