#if !defined(RTE_FLSMGR_HOOK_H)
#define RTE_FLSMGR_HOOK_H

/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains Rte hook declarations for the software component type FLSMGR
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Thu Mar 15 14:42:40 CET 2018. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

/*==================[inclusions]=============================================*/

#include <Rte_Cfg.h>         /* RTE VFB configuration header file */
#include <Rte_Type.h>     /* Rte type definitions header file */

/*==================[macros]=================================================*/

#if (!defined RTE_CORE) /* if included by software component */
#ifndef RTE_VFB_TRACE
#define RTE_VFB_TRACE (0)
#endif /* RTE_VFB_TRACE */
#endif
#if defined(Rte_IrvWriteHook_FLSMGR_reFlsMgrMain_FlsPrecondOK_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IrvWriteHook_FLSMGR_reFlsMgrMain_FlsPrecondOK_Start
#endif
#if defined(Rte_IrvWriteHook_FLSMGR_reFlsMgrMain_FlsPrecondOK_Start)
#undef Rte_IrvWriteHook_FLSMGR_reFlsMgrMain_FlsPrecondOK_Start
extern FUNC(void, RTE_APPL_CODE) Rte_IrvWriteHook_FLSMGR_reFlsMgrMain_FlsPrecondOK_Start(boolean data);
#else
#define Rte_IrvWriteHook_FLSMGR_reFlsMgrMain_FlsPrecondOK_Start(data) ((void)0)
#endif /* Rte_IrvWriteHook_FLSMGR_reFlsMgrMain_FlsPrecondOK_Start */
#if defined(Rte_IrvWriteHook_FLSMGR_reFlsMgrMain_FlsPrecondOK_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IrvWriteHook_FLSMGR_reFlsMgrMain_FlsPrecondOK_Return
#endif
#if defined(Rte_IrvWriteHook_FLSMGR_reFlsMgrMain_FlsPrecondOK_Return)
#undef Rte_IrvWriteHook_FLSMGR_reFlsMgrMain_FlsPrecondOK_Return
extern FUNC(void, RTE_APPL_CODE) Rte_IrvWriteHook_FLSMGR_reFlsMgrMain_FlsPrecondOK_Return(boolean data);
#else
#define Rte_IrvWriteHook_FLSMGR_reFlsMgrMain_FlsPrecondOK_Return(data) ((void)0)
#endif /* Rte_IrvWriteHook_FLSMGR_reFlsMgrMain_FlsPrecondOK_Return */
#if defined(Rte_IReadHook_FLSMGR_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IReadHook_FLSMGR_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue_Start
#endif
#if defined(Rte_IReadHook_FLSMGR_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue_Start)
#undef Rte_IReadHook_FLSMGR_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue_Start
extern FUNC(void, RTE_APPL_CODE) Rte_IReadHook_FLSMGR_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue_Start(GenericByte data);
#else
#define Rte_IReadHook_FLSMGR_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue_Start(data) ((void)0)
#endif /* Rte_IReadHook_FLSMGR_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue_Start */
#if defined(Rte_IReadHook_FLSMGR_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IReadHook_FLSMGR_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue_Return
#endif
#if defined(Rte_IReadHook_FLSMGR_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue_Return)
#undef Rte_IReadHook_FLSMGR_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue_Return
extern FUNC(void, RTE_APPL_CODE) Rte_IReadHook_FLSMGR_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue_Return(GenericByte data);
#else
#define Rte_IReadHook_FLSMGR_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue_Return(data) ((void)0)
#endif /* Rte_IReadHook_FLSMGR_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue_Return */
#if defined(Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsErase_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsErase_Start
#endif
#if defined(Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsErase_Start)
#undef Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsErase_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsErase_Start(uint32 addrU32, uint32 sizeU32);
#else
#define Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsErase_Start(addrU32, sizeU32) ((void)0)
#endif /* Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsErase_Start */
#if defined(Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsErase_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsErase_Return
#endif
#if defined(Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsErase_Return)
#undef Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsErase_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsErase_Return(uint32 addrU32, uint32 sizeU32);
#else
#define Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsErase_Return(addrU32, sizeU32) ((void)0)
#endif /* Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsErase_Return */
#if defined(Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsRead_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsRead_Start
#endif
#if defined(Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsRead_Start)
#undef Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsRead_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsRead_Start(uint32 addresU32, uint32 sizeU32, uint32 destBuffAddrU32);
#else
#define Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsRead_Start(addresU32, sizeU32, destBuffAddrU32) ((void)0)
#endif /* Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsRead_Start */
#if defined(Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsRead_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsRead_Return
#endif
#if defined(Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsRead_Return)
#undef Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsRead_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsRead_Return(uint32 addresU32, uint32 sizeU32, uint32 destBuffAddrU32);
#else
#define Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsRead_Return(addresU32, sizeU32, destBuffAddrU32) ((void)0)
#endif /* Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsRead_Return */
#if defined(Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsWrite_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsWrite_Start
#endif
#if defined(Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsWrite_Start)
#undef Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsWrite_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsWrite_Start(uint32 addrU32, uint32 sizeU32, uint32 srcBuffAddrU32);
#else
#define Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsWrite_Start(addrU32, sizeU32, srcBuffAddrU32) ((void)0)
#endif /* Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsWrite_Start */
#if defined(Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsWrite_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsWrite_Return
#endif
#if defined(Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsWrite_Return)
#undef Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsWrite_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsWrite_Return(uint32 addrU32, uint32 sizeU32, uint32 srcBuffAddrU32);
#else
#define Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsWrite_Return(addrU32, sizeU32, srcBuffAddrU32) ((void)0)
#endif /* Rte_CallHook_FLSMGR_WspExtFlsCdd_stService_FlsWrite_Return */
#if defined(Rte_IrvReadHook_FLSMGR_GetPrecondState_FlsPrecondOK_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IrvReadHook_FLSMGR_GetPrecondState_FlsPrecondOK_Start
#endif
#if defined(Rte_IrvReadHook_FLSMGR_GetPrecondState_FlsPrecondOK_Start)
#undef Rte_IrvReadHook_FLSMGR_GetPrecondState_FlsPrecondOK_Start
extern FUNC(void, RTE_APPL_CODE) Rte_IrvReadHook_FLSMGR_GetPrecondState_FlsPrecondOK_Start(void);
#else
#define Rte_IrvReadHook_FLSMGR_GetPrecondState_FlsPrecondOK_Start() ((void)0)
#endif /* Rte_IrvReadHook_FLSMGR_GetPrecondState_FlsPrecondOK_Start */
#if defined(Rte_IrvReadHook_FLSMGR_GetPrecondState_FlsPrecondOK_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IrvReadHook_FLSMGR_GetPrecondState_FlsPrecondOK_Return
#endif
#if defined(Rte_IrvReadHook_FLSMGR_GetPrecondState_FlsPrecondOK_Return)
#undef Rte_IrvReadHook_FLSMGR_GetPrecondState_FlsPrecondOK_Return
extern FUNC(void, RTE_APPL_CODE) Rte_IrvReadHook_FLSMGR_GetPrecondState_FlsPrecondOK_Return(void);
#else
#define Rte_IrvReadHook_FLSMGR_GetPrecondState_FlsPrecondOK_Return() ((void)0)
#endif /* Rte_IrvReadHook_FLSMGR_GetPrecondState_FlsPrecondOK_Return */
#if defined(Rte_Runnable_FLSMGR_reFlsMgrMain_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_FLSMGR_reFlsMgrMain_Start
#endif
#if defined(Rte_Runnable_FLSMGR_reFlsMgrMain_Start)
#undef Rte_Runnable_FLSMGR_reFlsMgrMain_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_FLSMGR_reFlsMgrMain_Start(void);
#else
#define Rte_Runnable_FLSMGR_reFlsMgrMain_Start() ((void)0)
#endif /* Rte_Runnable_FLSMGR_reFlsMgrMain_Start */
#if defined(Rte_Runnable_FLSMGR_reFlsMgrMain_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_FLSMGR_reFlsMgrMain_Return
#endif
#if defined(Rte_Runnable_FLSMGR_reFlsMgrMain_Return)
#undef Rte_Runnable_FLSMGR_reFlsMgrMain_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_FLSMGR_reFlsMgrMain_Return(void);
#else
#define Rte_Runnable_FLSMGR_reFlsMgrMain_Return() ((void)0)
#endif /* Rte_Runnable_FLSMGR_reFlsMgrMain_Return */
#if defined(Rte_Runnable_FLSMGR_reNotificationCallback_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_FLSMGR_reNotificationCallback_Start
#endif
#if defined(Rte_Runnable_FLSMGR_reNotificationCallback_Start)
#undef Rte_Runnable_FLSMGR_reNotificationCallback_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_FLSMGR_reNotificationCallback_Start(void);
#else
#define Rte_Runnable_FLSMGR_reNotificationCallback_Start() ((void)0)
#endif /* Rte_Runnable_FLSMGR_reNotificationCallback_Start */
#if defined(Rte_Runnable_FLSMGR_reNotificationCallback_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_FLSMGR_reNotificationCallback_Return
#endif
#if defined(Rte_Runnable_FLSMGR_reNotificationCallback_Return)
#undef Rte_Runnable_FLSMGR_reNotificationCallback_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_FLSMGR_reNotificationCallback_Return(void);
#else
#define Rte_Runnable_FLSMGR_reNotificationCallback_Return() ((void)0)
#endif /* Rte_Runnable_FLSMGR_reNotificationCallback_Return */
#if defined(Rte_Runnable_FLSMGR_GetPrecondState_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_FLSMGR_GetPrecondState_Start
#endif
#if defined(Rte_Runnable_FLSMGR_GetPrecondState_Start)
#undef Rte_Runnable_FLSMGR_GetPrecondState_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_FLSMGR_GetPrecondState_Start(void);
#else
#define Rte_Runnable_FLSMGR_GetPrecondState_Start() ((void)0)
#endif /* Rte_Runnable_FLSMGR_GetPrecondState_Start */
#if defined(Rte_Runnable_FLSMGR_GetPrecondState_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_FLSMGR_GetPrecondState_Return
#endif
#if defined(Rte_Runnable_FLSMGR_GetPrecondState_Return)
#undef Rte_Runnable_FLSMGR_GetPrecondState_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_FLSMGR_GetPrecondState_Return(void);
#else
#define Rte_Runnable_FLSMGR_GetPrecondState_Return() ((void)0)
#endif /* Rte_Runnable_FLSMGR_GetPrecondState_Return */

/*==================[type definitions]=======================================*/

/*==================[external function declarations]=========================*/

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/
/** @} doxygen end group definition */
#endif /* !defined(RTE_FLSMGR_HOOK_H) */
/*==================[end of file]============================================*/

