#if !defined(RTE_CHRONOS_HOOK_H)
#define RTE_CHRONOS_HOOK_H

/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains Rte hook declarations for the software component type Chronos
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Thu May 03 17:50:49 CEST 2018. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

/*==================[inclusions]=============================================*/

#include <Rte_Cfg.h>         /* RTE VFB configuration header file */
#include <Rte_Type.h>     /* Rte type definitions header file */

/*==================[macros]=================================================*/

#if (!defined RTE_CORE) /* if included by software component */
#ifndef RTE_VFB_TRACE
#define RTE_VFB_TRACE (0)
#endif /* RTE_VFB_TRACE */
#endif
#if defined(Rte_Runnable_Chronos_now_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_Chronos_now_Start
#endif
#if defined(Rte_Runnable_Chronos_now_Start)
#undef Rte_Runnable_Chronos_now_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_Chronos_now_Start(void);
#else
#define Rte_Runnable_Chronos_now_Start() ((void)0)
#endif /* Rte_Runnable_Chronos_now_Start */
#if defined(Rte_Runnable_Chronos_now_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_Chronos_now_Return
#endif
#if defined(Rte_Runnable_Chronos_now_Return)
#undef Rte_Runnable_Chronos_now_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_Chronos_now_Return(void);
#else
#define Rte_Runnable_Chronos_now_Return() ((void)0)
#endif /* Rte_Runnable_Chronos_now_Return */
#if defined(Rte_Runnable_Chronos_pack_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_Chronos_pack_Start
#endif
#if defined(Rte_Runnable_Chronos_pack_Start)
#undef Rte_Runnable_Chronos_pack_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_Chronos_pack_Start(void);
#else
#define Rte_Runnable_Chronos_pack_Start() ((void)0)
#endif /* Rte_Runnable_Chronos_pack_Start */
#if defined(Rte_Runnable_Chronos_pack_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_Chronos_pack_Return
#endif
#if defined(Rte_Runnable_Chronos_pack_Return)
#undef Rte_Runnable_Chronos_pack_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_Chronos_pack_Return(void);
#else
#define Rte_Runnable_Chronos_pack_Return() ((void)0)
#endif /* Rte_Runnable_Chronos_pack_Return */
#if defined(Rte_Runnable_Chronos_unpack_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_Chronos_unpack_Start
#endif
#if defined(Rte_Runnable_Chronos_unpack_Start)
#undef Rte_Runnable_Chronos_unpack_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_Chronos_unpack_Start(void);
#else
#define Rte_Runnable_Chronos_unpack_Start() ((void)0)
#endif /* Rte_Runnable_Chronos_unpack_Start */
#if defined(Rte_Runnable_Chronos_unpack_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_Chronos_unpack_Return
#endif
#if defined(Rte_Runnable_Chronos_unpack_Return)
#undef Rte_Runnable_Chronos_unpack_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_Chronos_unpack_Return(void);
#else
#define Rte_Runnable_Chronos_unpack_Return() ((void)0)
#endif /* Rte_Runnable_Chronos_unpack_Return */

/*==================[type definitions]=======================================*/

/*==================[external function declarations]=========================*/

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/
/** @} doxygen end group definition */
#endif /* !defined(RTE_CHRONOS_HOOK_H) */
/*==================[end of file]============================================*/

