#if !defined(RTE_COMM_H)
#define RTE_COMM_H

/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains Rte component declarations for component type ComM
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Fri Feb 09 11:09:50 CET 2018. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

/*==================[inclusions]=============================================*/

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <TSMem.h>
#include <Rte_ComM_Type.h> /* RTE application types header file */
#include <Rte_ComM_Hook.h> /* RTE application trace hooks header file */

/*==================[macros]=================================================*/

#if (!defined RTE_CORE) /* if included by software component */

#if (!defined RTE_APPLICATION_HEADER_FILE_H) /* prevent double inclusion */
#define RTE_APPLICATION_HEADER_FILE_H
#else
#error Multiple application header files included.
#endif /* if !defined( RTE_APPLICATION_HEADER_FILE_H ) */

#endif

/*------------------[API mapping]--------------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#endif

/*------------------[port handle API mapping]--------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#endif

/*------------------[application errors]-------------------------------------*/

#define RTE_E_ComM_UserRequest_E_NOT_OK 1U
#define RTE_E_ComM_UserRequest_E_MODE_LIMITATION 2U
#define RTE_E_ComM_ECUModeLimitation_E_NOT_OK 1U
#define RTE_E_ComM_ChannelLimitation_E_NOT_OK 1U
#define RTE_E_ComM_ChannelWakeUp_E_NOT_OK 1U

/*------------------[init values]--------------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#endif

/*==================[type definitions]=======================================*/

/*------------------[instance handle type]-----------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */
typedef CONSTP2CONST(Rte_CDS_ComM, RTE_CONST, RTE_CONST) Rte_Instance;
#endif

/*------------------[port handle types]--------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */
#endif

/*------------------[per instance memory types]------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#endif

/*==================[external function declarations]=========================*/

/*------------------[declaration of runnable entities]-----------------------*/

#define RTE_START_SEC_APPL_CODE
#include "MemMap.h"

extern FUNC(void, RTE_APPL_CODE) ComM_MainFunction_0(void);

extern FUNC(void, RTE_APPL_CODE) ComM_MainFunction_1(void);

extern FUNC(Std_ReturnType, RTE_APPL_CODE) ComM_RequestComMode(ComM_UserHandleType pdav0, ComM_ModeType ComMode);

extern FUNC(Std_ReturnType, RTE_APPL_CODE) ComM_GetCurrentComMode(ComM_UserHandleType pdav0, P2VAR(ComM_ModeType, AUTOMATIC, RTE_APPL_DATA) ComMode);

extern FUNC(Std_ReturnType, RTE_APPL_CODE) ComM_GetMaxComMode(ComM_UserHandleType pdav0, P2VAR(ComM_ModeType, AUTOMATIC, RTE_APPL_DATA) ComMode);

extern FUNC(Std_ReturnType, RTE_APPL_CODE) ComM_GetRequestedComMode(ComM_UserHandleType pdav0, P2VAR(ComM_ModeType, AUTOMATIC, RTE_APPL_DATA) ComMode);

extern FUNC(Std_ReturnType, RTE_APPL_CODE) ComM_LimitECUToNoComMode(Boolean Status);

extern FUNC(Std_ReturnType, RTE_APPL_CODE) ComM_ReadInhibitCounter(P2VAR(UInt16, AUTOMATIC, RTE_APPL_DATA) CounterValue);

extern FUNC(Std_ReturnType, RTE_APPL_CODE) ComM_ResetInhibitCounter(void);

extern FUNC(Std_ReturnType, RTE_APPL_CODE) ComM_SetECUGroupClassification(ComM_InhibitionStatusType Status);

extern FUNC(Std_ReturnType, RTE_APPL_CODE) ComM_ServiceLimitChannelToNoComMode(ComM_NetworkHandleType pdav0, Boolean Status);

extern FUNC(Std_ReturnType, RTE_APPL_CODE) ComM_GetInhibitionStatus(ComM_NetworkHandleType pdav0, P2VAR(ComM_InhibitionStatusType, AUTOMATIC, RTE_APPL_DATA) Status);

extern FUNC(Std_ReturnType, RTE_APPL_CODE) ComM_ServicePreventWakeUp(ComM_NetworkHandleType pdav0, Boolean Status);

#define RTE_STOP_SEC_APPL_CODE
#include "MemMap.h"

/*--------------[declaration of API functions provided by Rte]--------------*/

#define RTE_START_SEC_CODE
#include "MemMap.h"

#define RTE_STOP_SEC_CODE
#include "MemMap.h"

/*--------------[declaration of API functions provided by other Appl]--------*/

#define RTE_START_SEC_APPL_CODE
#include "MemMap.h"

#if (!defined RTE_CORE) /* if included by software component */

#endif /* (!defined RTE_CORE) */

#define RTE_STOP_SEC_APPL_CODE
#include "MemMap.h"

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*------------------[instance handle declaration]----------------------------*/
#define RTE_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

extern CONSTP2CONST(Rte_CDS_ComM, RTE_CONST, RTE_CONST) Rte_Inst_ComM;

#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */
/** @} doxygen end group definition */
#endif /* !defined(RTE_COMM_H) */
/*==================[end of file]============================================*/

