#if !defined(RTE_CHRONOS_H)
#define RTE_CHRONOS_H

/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains Rte component declarations for component type Chronos
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Thu May 03 17:50:49 CEST 2018. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

/*==================[inclusions]=============================================*/

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <TSMem.h>
#include <Rte_Chronos_Type.h> /* RTE application types header file */
#include <Rte_Chronos_Hook.h> /* RTE application trace hooks header file */

/*==================[macros]=================================================*/

#if (!defined RTE_CORE) /* if included by software component */

#if (!defined RTE_APPLICATION_HEADER_FILE_H) /* prevent double inclusion */
#define RTE_APPLICATION_HEADER_FILE_H
#else
#error Multiple application header files included.
#endif /* if !defined( RTE_APPLICATION_HEADER_FILE_H ) */

#endif

/*------------------[API mapping]--------------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#endif

/*------------------[port handle API mapping]--------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#endif

/*------------------[application errors]-------------------------------------*/

/*------------------[init values]--------------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#endif

/*==================[type definitions]=======================================*/

/*------------------[instance handle type]-----------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */
typedef CONSTP2CONST(Rte_CDS_Chronos, RTE_CONST, RTE_CONST) Rte_Instance;
#endif

/*------------------[port handle types]--------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */
#endif

/*------------------[per instance memory types]------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#endif

/*==================[external function declarations]=========================*/

/*------------------[declaration of runnable entities]-----------------------*/

#define RTE_START_SEC_APPL_CODE
#include "MemMap.h"

extern FUNC(void, RTE_APPL_CODE) Chronos_now(P2VAR(Timestamp, AUTOMATIC, RTE_APPL_DATA) timestamp);

#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(void, RTE_APPL_CODE) Chronos_pack(P2CONST(Timestamp, AUTOMATIC, RTE_APPL_CONST) timestamp, P2VAR(TimestampBuffer, AUTOMATIC, RTE_APPL_DATA) buffer);
#else
extern FUNC(void, RTE_APPL_CODE) Chronos_pack(P2CONST(Timestamp, AUTOMATIC, RTE_APPL_CONST) timestamp, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) buffer);
#endif

#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(void, RTE_APPL_CODE) Chronos_unpack(P2VAR(Timestamp, AUTOMATIC, RTE_APPL_DATA) timestamp, P2CONST(TimestampBuffer, AUTOMATIC, RTE_APPL_CONST) buffer);
#else
extern FUNC(void, RTE_APPL_CODE) Chronos_unpack(P2VAR(Timestamp, AUTOMATIC, RTE_APPL_DATA) timestamp, P2CONST(uint8, AUTOMATIC, RTE_APPL_CONST) buffer);
#endif

#define RTE_STOP_SEC_APPL_CODE
#include "MemMap.h"

/*--------------[declaration of API functions provided by Rte]--------------*/

#define RTE_START_SEC_CODE
#include "MemMap.h"

#define RTE_STOP_SEC_CODE
#include "MemMap.h"

/*--------------[declaration of API functions provided by other Appl]--------*/

#define RTE_START_SEC_APPL_CODE
#include "MemMap.h"

#if (!defined RTE_CORE) /* if included by software component */

#endif /* (!defined RTE_CORE) */

#define RTE_STOP_SEC_APPL_CODE
#include "MemMap.h"

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*------------------[instance handle declaration]----------------------------*/
#define RTE_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

extern CONSTP2CONST(Rte_CDS_Chronos, RTE_CONST, RTE_CONST) Rte_Inst_Chronos;

#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */
/** @} doxygen end group definition */
#endif /* !defined(RTE_CHRONOS_H) */
/*==================[end of file]============================================*/

