#if !defined(RTE_FLSMGR_H)
#define RTE_FLSMGR_H

/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains Rte component declarations for component type FLSMGR
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Thu Mar 15 14:42:40 CET 2018. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

/*==================[inclusions]=============================================*/

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <TSMem.h>
#include <Rte_FLSMGR_Type.h> /* RTE application types header file */
#include <Rte_FLSMGR_Hook.h> /* RTE application trace hooks header file */

/*==================[macros]=================================================*/

#if (!defined RTE_CORE) /* if included by software component */

#if (!defined RTE_APPLICATION_HEADER_FILE_H) /* prevent double inclusion */
#define RTE_APPLICATION_HEADER_FILE_H
#else
#error Multiple application header files included.
#endif /* if !defined( RTE_APPLICATION_HEADER_FILE_H ) */

#endif

/*------------------[API mapping]--------------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */
#if !defined(RTE_RUNNABLEAPI_reNotificationCallback) || !defined(RTE_RUNNABLEAPI_GetPrecondState)
#define Rte_IrvWrite_reFlsMgrMain_FlsPrecondOK(data) Rte_IrvWrite_FLSMGR_reFlsMgrMain_FlsPrecondOK(data)

#define Rte_IRead_reFlsMgrMain_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue() (Rte_IReadHook_FLSMGR_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue_Start(Rte_Inst_FLSMGR->reFlsMgrMain_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue->value), Rte_IReadHook_FLSMGR_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue_Return(Rte_Inst_FLSMGR->reFlsMgrMain_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue->value), Rte_Inst_FLSMGR->reFlsMgrMain_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue->value)

#define Rte_Call_WspExtFlsCdd_stService_FlsErase Rte_Call_FLSMGR_WspExtFlsCdd_stService_FlsErase

#define Rte_Call_WspExtFlsCdd_stService_FlsRead Rte_Call_FLSMGR_WspExtFlsCdd_stService_FlsRead

#define Rte_Call_WspExtFlsCdd_stService_FlsWrite Rte_Call_FLSMGR_WspExtFlsCdd_stService_FlsWrite

#endif
#if !defined(RTE_RUNNABLEAPI_reFlsMgrMain) || !defined(RTE_RUNNABLEAPI_reNotificationCallback)
#define Rte_IrvRead_GetPrecondState_FlsPrecondOK() Rte_IrvRead_FLSMGR_GetPrecondState_FlsPrecondOK()

#endif

#endif

/*------------------[port handle API mapping]--------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#endif

/*------------------[application errors]-------------------------------------*/

#define RTE_E_ifExtFlsService_E_NOK 1U
#define RTE_E_ifExtFlsService_E_OK 0U

/*------------------[init values]--------------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#define Rte_InitValue_WspStMgr_stWsStMgr_SCI_SSM_ActStateWsValue 0U

#endif

/*==================[type definitions]=======================================*/

/*------------------[instance handle type]-----------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */
typedef CONSTP2CONST(Rte_CDS_FLSMGR, RTE_CONST, RTE_CONST) Rte_Instance;
#endif

/*------------------[port handle types]--------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */
#endif

/*------------------[per instance memory types]------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#endif

/*==================[external function declarations]=========================*/

/*------------------[declaration of runnable entities]-----------------------*/

#define RTE_START_SEC_APPL_CODE
#include "MemMap.h"

extern FUNC(void, RTE_APPL_CODE) FLSMGR_reFlsMgrMain(void);

extern FUNC(void, RTE_APPL_CODE) FLSMGR_reNotificationCallback(uint8 statusU8);

extern FUNC(void, RTE_APPL_CODE) FLSMGR_GetPrecondState(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) PrecondOk);

#define RTE_STOP_SEC_APPL_CODE
#include "MemMap.h"

/*--------------[declaration of API functions provided by Rte]--------------*/

#define RTE_START_SEC_CODE
#include "MemMap.h"
#if (!defined(RTE_RUNNABLEAPI_reNotificationCallback))  || (!defined(RTE_RUNNABLEAPI_GetPrecondState))
extern FUNC(void, RTE_CODE) Rte_IrvWrite_FLSMGR_reFlsMgrMain_FlsPrecondOK (boolean data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_FLSMGR_WspExtFlsCdd_stService_FlsErase (uint32 addrU32, uint32 sizeU32);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_FLSMGR_WspExtFlsCdd_stService_FlsRead (uint32 addresU32, uint32 sizeU32, uint32 destBuffAddrU32);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_FLSMGR_WspExtFlsCdd_stService_FlsWrite (uint32 addrU32, uint32 sizeU32, uint32 srcBuffAddrU32);

#endif
#if (!defined(RTE_RUNNABLEAPI_reFlsMgrMain))  || (!defined(RTE_RUNNABLEAPI_reNotificationCallback))
extern FUNC(boolean, RTE_CODE) Rte_IrvRead_FLSMGR_GetPrecondState_FlsPrecondOK (void);

#endif

#define RTE_STOP_SEC_CODE
#include "MemMap.h"

/*--------------[declaration of API functions provided by other Appl]--------*/

#define RTE_START_SEC_APPL_CODE
#include "MemMap.h"

#if (!defined RTE_CORE) /* if included by software component */

#endif /* (!defined RTE_CORE) */

#define RTE_STOP_SEC_APPL_CODE
#include "MemMap.h"

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*------------------[instance handle declaration]----------------------------*/
#define RTE_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

extern CONSTP2CONST(Rte_CDS_FLSMGR, RTE_CONST, RTE_CONST) Rte_Inst_FLSMGR;

#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */
/** @} doxygen end group definition */
#endif /* !defined(RTE_FLSMGR_H) */
/*==================[end of file]============================================*/

