#if !defined(RTE_FOD_HOOK_H)
#define RTE_FOD_HOOK_H

/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains Rte hook declarations for the software component type FOD
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Fri Feb 09 14:59:49 CET 2018. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

/*==================[inclusions]=============================================*/

#include <Rte_Cfg.h>         /* RTE VFB configuration header file */
#include <Rte_Type.h>     /* Rte type definitions header file */

/*==================[macros]=================================================*/

#if (!defined RTE_CORE) /* if included by software component */
#ifndef RTE_VFB_TRACE
#define RTE_VFB_TRACE (0)
#endif /* RTE_VFB_TRACE */
#endif
#if defined(Rte_IrvReadHook_FOD_WsFodMgr_MainFunction_NvFlag_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IrvReadHook_FOD_WsFodMgr_MainFunction_NvFlag_Start
#endif
#if defined(Rte_IrvReadHook_FOD_WsFodMgr_MainFunction_NvFlag_Start)
#undef Rte_IrvReadHook_FOD_WsFodMgr_MainFunction_NvFlag_Start
extern FUNC(void, RTE_APPL_CODE) Rte_IrvReadHook_FOD_WsFodMgr_MainFunction_NvFlag_Start(void);
#else
#define Rte_IrvReadHook_FOD_WsFodMgr_MainFunction_NvFlag_Start() ((void)0)
#endif /* Rte_IrvReadHook_FOD_WsFodMgr_MainFunction_NvFlag_Start */
#if defined(Rte_IrvReadHook_FOD_WsFodMgr_MainFunction_NvFlag_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IrvReadHook_FOD_WsFodMgr_MainFunction_NvFlag_Return
#endif
#if defined(Rte_IrvReadHook_FOD_WsFodMgr_MainFunction_NvFlag_Return)
#undef Rte_IrvReadHook_FOD_WsFodMgr_MainFunction_NvFlag_Return
extern FUNC(void, RTE_APPL_CODE) Rte_IrvReadHook_FOD_WsFodMgr_MainFunction_NvFlag_Return(void);
#else
#define Rte_IrvReadHook_FOD_WsFodMgr_MainFunction_NvFlag_Return() ((void)0)
#endif /* Rte_IrvReadHook_FOD_WsFodMgr_MainFunction_NvFlag_Return */
#if defined(Rte_IrvWriteHook_FOD_WsFodMgr_MainFunction_NvFlag_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IrvWriteHook_FOD_WsFodMgr_MainFunction_NvFlag_Start
#endif
#if defined(Rte_IrvWriteHook_FOD_WsFodMgr_MainFunction_NvFlag_Start)
#undef Rte_IrvWriteHook_FOD_WsFodMgr_MainFunction_NvFlag_Start
extern FUNC(void, RTE_APPL_CODE) Rte_IrvWriteHook_FOD_WsFodMgr_MainFunction_NvFlag_Start(GenericByte data);
#else
#define Rte_IrvWriteHook_FOD_WsFodMgr_MainFunction_NvFlag_Start(data) ((void)0)
#endif /* Rte_IrvWriteHook_FOD_WsFodMgr_MainFunction_NvFlag_Start */
#if defined(Rte_IrvWriteHook_FOD_WsFodMgr_MainFunction_NvFlag_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IrvWriteHook_FOD_WsFodMgr_MainFunction_NvFlag_Return
#endif
#if defined(Rte_IrvWriteHook_FOD_WsFodMgr_MainFunction_NvFlag_Return)
#undef Rte_IrvWriteHook_FOD_WsFodMgr_MainFunction_NvFlag_Return
extern FUNC(void, RTE_APPL_CODE) Rte_IrvWriteHook_FOD_WsFodMgr_MainFunction_NvFlag_Return(GenericByte data);
#else
#define Rte_IrvWriteHook_FOD_WsFodMgr_MainFunction_NvFlag_Return(data) ((void)0)
#endif /* Rte_IrvWriteHook_FOD_WsFodMgr_MainFunction_NvFlag_Return */
#if defined(Rte_IWriteHook_FOD_PP_ForeignObjectDetected_SCI_FODMGR_SftyOnOffValue_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IWriteHook_FOD_PP_ForeignObjectDetected_SCI_FODMGR_SftyOnOffValue_Start
#endif
#if defined(Rte_IWriteHook_FOD_PP_ForeignObjectDetected_SCI_FODMGR_SftyOnOffValue_Start)
#undef Rte_IWriteHook_FOD_PP_ForeignObjectDetected_SCI_FODMGR_SftyOnOffValue_Start
extern FUNC(void, RTE_APPL_CODE) Rte_IWriteHook_FOD_PP_ForeignObjectDetected_SCI_FODMGR_SftyOnOffValue_Start(P2CONST(SftyBoolOO, AUTOMATIC, RTE_APPL_CONST) data);
#else
#define Rte_IWriteHook_FOD_PP_ForeignObjectDetected_SCI_FODMGR_SftyOnOffValue_Start(data) ((void)0)
#endif /* Rte_IWriteHook_FOD_PP_ForeignObjectDetected_SCI_FODMGR_SftyOnOffValue_Start */
#if defined(Rte_IWriteHook_FOD_PP_ForeignObjectDetected_SCI_FODMGR_SftyOnOffValue_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IWriteHook_FOD_PP_ForeignObjectDetected_SCI_FODMGR_SftyOnOffValue_Return
#endif
#if defined(Rte_IWriteHook_FOD_PP_ForeignObjectDetected_SCI_FODMGR_SftyOnOffValue_Return)
#undef Rte_IWriteHook_FOD_PP_ForeignObjectDetected_SCI_FODMGR_SftyOnOffValue_Return
extern FUNC(void, RTE_APPL_CODE) Rte_IWriteHook_FOD_PP_ForeignObjectDetected_SCI_FODMGR_SftyOnOffValue_Return(P2CONST(SftyBoolOO, AUTOMATIC, RTE_APPL_CONST) data);
#else
#define Rte_IWriteHook_FOD_PP_ForeignObjectDetected_SCI_FODMGR_SftyOnOffValue_Return(data) ((void)0)
#endif /* Rte_IWriteHook_FOD_PP_ForeignObjectDetected_SCI_FODMGR_SftyOnOffValue_Return */
#if defined(Rte_IWriteHook_FOD_PP_FodCheckDuringChrg_SftyBoolValue_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IWriteHook_FOD_PP_FodCheckDuringChrg_SftyBoolValue_Start
#endif
#if defined(Rte_IWriteHook_FOD_PP_FodCheckDuringChrg_SftyBoolValue_Start)
#undef Rte_IWriteHook_FOD_PP_FodCheckDuringChrg_SftyBoolValue_Start
extern FUNC(void, RTE_APPL_CODE) Rte_IWriteHook_FOD_PP_FodCheckDuringChrg_SftyBoolValue_Start(P2CONST(SftyBoolTF, AUTOMATIC, RTE_APPL_CONST) data);
#else
#define Rte_IWriteHook_FOD_PP_FodCheckDuringChrg_SftyBoolValue_Start(data) ((void)0)
#endif /* Rte_IWriteHook_FOD_PP_FodCheckDuringChrg_SftyBoolValue_Start */
#if defined(Rte_IWriteHook_FOD_PP_FodCheckDuringChrg_SftyBoolValue_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IWriteHook_FOD_PP_FodCheckDuringChrg_SftyBoolValue_Return
#endif
#if defined(Rte_IWriteHook_FOD_PP_FodCheckDuringChrg_SftyBoolValue_Return)
#undef Rte_IWriteHook_FOD_PP_FodCheckDuringChrg_SftyBoolValue_Return
extern FUNC(void, RTE_APPL_CODE) Rte_IWriteHook_FOD_PP_FodCheckDuringChrg_SftyBoolValue_Return(P2CONST(SftyBoolTF, AUTOMATIC, RTE_APPL_CONST) data);
#else
#define Rte_IWriteHook_FOD_PP_FodCheckDuringChrg_SftyBoolValue_Return(data) ((void)0)
#endif /* Rte_IWriteHook_FOD_PP_FodCheckDuringChrg_SftyBoolValue_Return */
#if defined(Rte_IWriteHook_FOD_PP_FodCheckStartUpChrg_SftyBoolValue_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IWriteHook_FOD_PP_FodCheckStartUpChrg_SftyBoolValue_Start
#endif
#if defined(Rte_IWriteHook_FOD_PP_FodCheckStartUpChrg_SftyBoolValue_Start)
#undef Rte_IWriteHook_FOD_PP_FodCheckStartUpChrg_SftyBoolValue_Start
extern FUNC(void, RTE_APPL_CODE) Rte_IWriteHook_FOD_PP_FodCheckStartUpChrg_SftyBoolValue_Start(P2CONST(SftyBoolTF, AUTOMATIC, RTE_APPL_CONST) data);
#else
#define Rte_IWriteHook_FOD_PP_FodCheckStartUpChrg_SftyBoolValue_Start(data) ((void)0)
#endif /* Rte_IWriteHook_FOD_PP_FodCheckStartUpChrg_SftyBoolValue_Start */
#if defined(Rte_IWriteHook_FOD_PP_FodCheckStartUpChrg_SftyBoolValue_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IWriteHook_FOD_PP_FodCheckStartUpChrg_SftyBoolValue_Return
#endif
#if defined(Rte_IWriteHook_FOD_PP_FodCheckStartUpChrg_SftyBoolValue_Return)
#undef Rte_IWriteHook_FOD_PP_FodCheckStartUpChrg_SftyBoolValue_Return
extern FUNC(void, RTE_APPL_CODE) Rte_IWriteHook_FOD_PP_FodCheckStartUpChrg_SftyBoolValue_Return(P2CONST(SftyBoolTF, AUTOMATIC, RTE_APPL_CONST) data);
#else
#define Rte_IWriteHook_FOD_PP_FodCheckStartUpChrg_SftyBoolValue_Return(data) ((void)0)
#endif /* Rte_IWriteHook_FOD_PP_FodCheckStartUpChrg_SftyBoolValue_Return */
#if defined(Rte_IWriteHook_FOD_PP_FodCheckZMDown_SftyBoolValue_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IWriteHook_FOD_PP_FodCheckZMDown_SftyBoolValue_Start
#endif
#if defined(Rte_IWriteHook_FOD_PP_FodCheckZMDown_SftyBoolValue_Start)
#undef Rte_IWriteHook_FOD_PP_FodCheckZMDown_SftyBoolValue_Start
extern FUNC(void, RTE_APPL_CODE) Rte_IWriteHook_FOD_PP_FodCheckZMDown_SftyBoolValue_Start(P2CONST(SftyBoolTF, AUTOMATIC, RTE_APPL_CONST) data);
#else
#define Rte_IWriteHook_FOD_PP_FodCheckZMDown_SftyBoolValue_Start(data) ((void)0)
#endif /* Rte_IWriteHook_FOD_PP_FodCheckZMDown_SftyBoolValue_Start */
#if defined(Rte_IWriteHook_FOD_PP_FodCheckZMDown_SftyBoolValue_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IWriteHook_FOD_PP_FodCheckZMDown_SftyBoolValue_Return
#endif
#if defined(Rte_IWriteHook_FOD_PP_FodCheckZMDown_SftyBoolValue_Return)
#undef Rte_IWriteHook_FOD_PP_FodCheckZMDown_SftyBoolValue_Return
extern FUNC(void, RTE_APPL_CODE) Rte_IWriteHook_FOD_PP_FodCheckZMDown_SftyBoolValue_Return(P2CONST(SftyBoolTF, AUTOMATIC, RTE_APPL_CONST) data);
#else
#define Rte_IWriteHook_FOD_PP_FodCheckZMDown_SftyBoolValue_Return(data) ((void)0)
#endif /* Rte_IWriteHook_FOD_PP_FodCheckZMDown_SftyBoolValue_Return */
#if defined(Rte_IWriteHook_FOD_PP_FodCheckZMUp_SftyBoolValue_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IWriteHook_FOD_PP_FodCheckZMUp_SftyBoolValue_Start
#endif
#if defined(Rte_IWriteHook_FOD_PP_FodCheckZMUp_SftyBoolValue_Start)
#undef Rte_IWriteHook_FOD_PP_FodCheckZMUp_SftyBoolValue_Start
extern FUNC(void, RTE_APPL_CODE) Rte_IWriteHook_FOD_PP_FodCheckZMUp_SftyBoolValue_Start(P2CONST(SftyBoolTF, AUTOMATIC, RTE_APPL_CONST) data);
#else
#define Rte_IWriteHook_FOD_PP_FodCheckZMUp_SftyBoolValue_Start(data) ((void)0)
#endif /* Rte_IWriteHook_FOD_PP_FodCheckZMUp_SftyBoolValue_Start */
#if defined(Rte_IWriteHook_FOD_PP_FodCheckZMUp_SftyBoolValue_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IWriteHook_FOD_PP_FodCheckZMUp_SftyBoolValue_Return
#endif
#if defined(Rte_IWriteHook_FOD_PP_FodCheckZMUp_SftyBoolValue_Return)
#undef Rte_IWriteHook_FOD_PP_FodCheckZMUp_SftyBoolValue_Return
extern FUNC(void, RTE_APPL_CODE) Rte_IWriteHook_FOD_PP_FodCheckZMUp_SftyBoolValue_Return(P2CONST(SftyBoolTF, AUTOMATIC, RTE_APPL_CONST) data);
#else
#define Rte_IWriteHook_FOD_PP_FodCheckZMUp_SftyBoolValue_Return(data) ((void)0)
#endif /* Rte_IWriteHook_FOD_PP_FodCheckZMUp_SftyBoolValue_Return */
#if defined(Rte_IWriteHook_FOD_PP_FodPreCheck_SftyBoolValue_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IWriteHook_FOD_PP_FodPreCheck_SftyBoolValue_Start
#endif
#if defined(Rte_IWriteHook_FOD_PP_FodPreCheck_SftyBoolValue_Start)
#undef Rte_IWriteHook_FOD_PP_FodPreCheck_SftyBoolValue_Start
extern FUNC(void, RTE_APPL_CODE) Rte_IWriteHook_FOD_PP_FodPreCheck_SftyBoolValue_Start(P2CONST(SftyBoolTF, AUTOMATIC, RTE_APPL_CONST) data);
#else
#define Rte_IWriteHook_FOD_PP_FodPreCheck_SftyBoolValue_Start(data) ((void)0)
#endif /* Rte_IWriteHook_FOD_PP_FodPreCheck_SftyBoolValue_Start */
#if defined(Rte_IWriteHook_FOD_PP_FodPreCheck_SftyBoolValue_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IWriteHook_FOD_PP_FodPreCheck_SftyBoolValue_Return
#endif
#if defined(Rte_IWriteHook_FOD_PP_FodPreCheck_SftyBoolValue_Return)
#undef Rte_IWriteHook_FOD_PP_FodPreCheck_SftyBoolValue_Return
extern FUNC(void, RTE_APPL_CODE) Rte_IWriteHook_FOD_PP_FodPreCheck_SftyBoolValue_Return(P2CONST(SftyBoolTF, AUTOMATIC, RTE_APPL_CONST) data);
#else
#define Rte_IWriteHook_FOD_PP_FodPreCheck_SftyBoolValue_Return(data) ((void)0)
#endif /* Rte_IWriteHook_FOD_PP_FodPreCheck_SftyBoolValue_Return */
#if defined(Rte_IWriteHook_FOD_PP_FodCheckDuringChrgTh_Value_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IWriteHook_FOD_PP_FodCheckDuringChrgTh_Value_Start
#endif
#if defined(Rte_IWriteHook_FOD_PP_FodCheckDuringChrgTh_Value_Start)
#undef Rte_IWriteHook_FOD_PP_FodCheckDuringChrgTh_Value_Start
extern FUNC(void, RTE_APPL_CODE) Rte_IWriteHook_FOD_PP_FodCheckDuringChrgTh_Value_Start(FodDetectTh data);
#else
#define Rte_IWriteHook_FOD_PP_FodCheckDuringChrgTh_Value_Start(data) ((void)0)
#endif /* Rte_IWriteHook_FOD_PP_FodCheckDuringChrgTh_Value_Start */
#if defined(Rte_IWriteHook_FOD_PP_FodCheckDuringChrgTh_Value_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IWriteHook_FOD_PP_FodCheckDuringChrgTh_Value_Return
#endif
#if defined(Rte_IWriteHook_FOD_PP_FodCheckDuringChrgTh_Value_Return)
#undef Rte_IWriteHook_FOD_PP_FodCheckDuringChrgTh_Value_Return
extern FUNC(void, RTE_APPL_CODE) Rte_IWriteHook_FOD_PP_FodCheckDuringChrgTh_Value_Return(FodDetectTh data);
#else
#define Rte_IWriteHook_FOD_PP_FodCheckDuringChrgTh_Value_Return(data) ((void)0)
#endif /* Rte_IWriteHook_FOD_PP_FodCheckDuringChrgTh_Value_Return */
#if defined(Rte_IWriteHook_FOD_PP_FodCheckZMDownTh_Value_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IWriteHook_FOD_PP_FodCheckZMDownTh_Value_Start
#endif
#if defined(Rte_IWriteHook_FOD_PP_FodCheckZMDownTh_Value_Start)
#undef Rte_IWriteHook_FOD_PP_FodCheckZMDownTh_Value_Start
extern FUNC(void, RTE_APPL_CODE) Rte_IWriteHook_FOD_PP_FodCheckZMDownTh_Value_Start(FodDetectTh data);
#else
#define Rte_IWriteHook_FOD_PP_FodCheckZMDownTh_Value_Start(data) ((void)0)
#endif /* Rte_IWriteHook_FOD_PP_FodCheckZMDownTh_Value_Start */
#if defined(Rte_IWriteHook_FOD_PP_FodCheckZMDownTh_Value_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IWriteHook_FOD_PP_FodCheckZMDownTh_Value_Return
#endif
#if defined(Rte_IWriteHook_FOD_PP_FodCheckZMDownTh_Value_Return)
#undef Rte_IWriteHook_FOD_PP_FodCheckZMDownTh_Value_Return
extern FUNC(void, RTE_APPL_CODE) Rte_IWriteHook_FOD_PP_FodCheckZMDownTh_Value_Return(FodDetectTh data);
#else
#define Rte_IWriteHook_FOD_PP_FodCheckZMDownTh_Value_Return(data) ((void)0)
#endif /* Rte_IWriteHook_FOD_PP_FodCheckZMDownTh_Value_Return */
#if defined(Rte_IWriteHook_FOD_PP_FodCheckZMUpTh_Value_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IWriteHook_FOD_PP_FodCheckZMUpTh_Value_Start
#endif
#if defined(Rte_IWriteHook_FOD_PP_FodCheckZMUpTh_Value_Start)
#undef Rte_IWriteHook_FOD_PP_FodCheckZMUpTh_Value_Start
extern FUNC(void, RTE_APPL_CODE) Rte_IWriteHook_FOD_PP_FodCheckZMUpTh_Value_Start(FodDetectTh data);
#else
#define Rte_IWriteHook_FOD_PP_FodCheckZMUpTh_Value_Start(data) ((void)0)
#endif /* Rte_IWriteHook_FOD_PP_FodCheckZMUpTh_Value_Start */
#if defined(Rte_IWriteHook_FOD_PP_FodCheckZMUpTh_Value_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IWriteHook_FOD_PP_FodCheckZMUpTh_Value_Return
#endif
#if defined(Rte_IWriteHook_FOD_PP_FodCheckZMUpTh_Value_Return)
#undef Rte_IWriteHook_FOD_PP_FodCheckZMUpTh_Value_Return
extern FUNC(void, RTE_APPL_CODE) Rte_IWriteHook_FOD_PP_FodCheckZMUpTh_Value_Return(FodDetectTh data);
#else
#define Rte_IWriteHook_FOD_PP_FodCheckZMUpTh_Value_Return(data) ((void)0)
#endif /* Rte_IWriteHook_FOD_PP_FodCheckZMUpTh_Value_Return */
#if defined(Rte_IWriteHook_FOD_PP_FodPreCheckTh_Value_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IWriteHook_FOD_PP_FodPreCheckTh_Value_Start
#endif
#if defined(Rte_IWriteHook_FOD_PP_FodPreCheckTh_Value_Start)
#undef Rte_IWriteHook_FOD_PP_FodPreCheckTh_Value_Start
extern FUNC(void, RTE_APPL_CODE) Rte_IWriteHook_FOD_PP_FodPreCheckTh_Value_Start(FodDetectTh data);
#else
#define Rte_IWriteHook_FOD_PP_FodPreCheckTh_Value_Start(data) ((void)0)
#endif /* Rte_IWriteHook_FOD_PP_FodPreCheckTh_Value_Start */
#if defined(Rte_IWriteHook_FOD_PP_FodPreCheckTh_Value_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IWriteHook_FOD_PP_FodPreCheckTh_Value_Return
#endif
#if defined(Rte_IWriteHook_FOD_PP_FodPreCheckTh_Value_Return)
#undef Rte_IWriteHook_FOD_PP_FodPreCheckTh_Value_Return
extern FUNC(void, RTE_APPL_CODE) Rte_IWriteHook_FOD_PP_FodPreCheckTh_Value_Return(FodDetectTh data);
#else
#define Rte_IWriteHook_FOD_PP_FodPreCheckTh_Value_Return(data) ((void)0)
#endif /* Rte_IWriteHook_FOD_PP_FodPreCheckTh_Value_Return */
#if defined(Rte_IReadHook_FOD_RP_FodData_SCI_FODMGR_FodDataValue_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IReadHook_FOD_RP_FodData_SCI_FODMGR_FodDataValue_Start
#endif
#if defined(Rte_IReadHook_FOD_RP_FodData_SCI_FODMGR_FodDataValue_Start)
#undef Rte_IReadHook_FOD_RP_FodData_SCI_FODMGR_FodDataValue_Start
extern FUNC(void, RTE_APPL_CODE) Rte_IReadHook_FOD_RP_FodData_SCI_FODMGR_FodDataValue_Start(P2CONST(FodDataV40, AUTOMATIC, RTE_APPL_CONST) data);
#else
#define Rte_IReadHook_FOD_RP_FodData_SCI_FODMGR_FodDataValue_Start(data) ((void)0)
#endif /* Rte_IReadHook_FOD_RP_FodData_SCI_FODMGR_FodDataValue_Start */
#if defined(Rte_IReadHook_FOD_RP_FodData_SCI_FODMGR_FodDataValue_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IReadHook_FOD_RP_FodData_SCI_FODMGR_FodDataValue_Return
#endif
#if defined(Rte_IReadHook_FOD_RP_FodData_SCI_FODMGR_FodDataValue_Return)
#undef Rte_IReadHook_FOD_RP_FodData_SCI_FODMGR_FodDataValue_Return
extern FUNC(void, RTE_APPL_CODE) Rte_IReadHook_FOD_RP_FodData_SCI_FODMGR_FodDataValue_Return(P2CONST(FodDataV40, AUTOMATIC, RTE_APPL_CONST) data);
#else
#define Rte_IReadHook_FOD_RP_FodData_SCI_FODMGR_FodDataValue_Return(data) ((void)0)
#endif /* Rte_IReadHook_FOD_RP_FodData_SCI_FODMGR_FodDataValue_Return */
#if defined(Rte_IReadHook_FOD_RP_ResData_ResDataVal_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IReadHook_FOD_RP_ResData_ResDataVal_Start
#endif
#if defined(Rte_IReadHook_FOD_RP_ResData_ResDataVal_Start)
#undef Rte_IReadHook_FOD_RP_ResData_ResDataVal_Start
extern FUNC(void, RTE_APPL_CODE) Rte_IReadHook_FOD_RP_ResData_ResDataVal_Start(P2CONST(ResData, AUTOMATIC, RTE_APPL_CONST) data);
#else
#define Rte_IReadHook_FOD_RP_ResData_ResDataVal_Start(data) ((void)0)
#endif /* Rte_IReadHook_FOD_RP_ResData_ResDataVal_Start */
#if defined(Rte_IReadHook_FOD_RP_ResData_ResDataVal_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IReadHook_FOD_RP_ResData_ResDataVal_Return
#endif
#if defined(Rte_IReadHook_FOD_RP_ResData_ResDataVal_Return)
#undef Rte_IReadHook_FOD_RP_ResData_ResDataVal_Return
extern FUNC(void, RTE_APPL_CODE) Rte_IReadHook_FOD_RP_ResData_ResDataVal_Return(P2CONST(ResData, AUTOMATIC, RTE_APPL_CONST) data);
#else
#define Rte_IReadHook_FOD_RP_ResData_ResDataVal_Return(data) ((void)0)
#endif /* Rte_IReadHook_FOD_RP_ResData_ResDataVal_Return */
#if defined(Rte_IReadHook_FOD_WspDiagCtrl_cmdFodActivate_DiagCtrlFod_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IReadHook_FOD_WspDiagCtrl_cmdFodActivate_DiagCtrlFod_Start
#endif
#if defined(Rte_IReadHook_FOD_WspDiagCtrl_cmdFodActivate_DiagCtrlFod_Start)
#undef Rte_IReadHook_FOD_WspDiagCtrl_cmdFodActivate_DiagCtrlFod_Start
extern FUNC(void, RTE_APPL_CODE) Rte_IReadHook_FOD_WspDiagCtrl_cmdFodActivate_DiagCtrlFod_Start(uint8 data);
#else
#define Rte_IReadHook_FOD_WspDiagCtrl_cmdFodActivate_DiagCtrlFod_Start(data) ((void)0)
#endif /* Rte_IReadHook_FOD_WspDiagCtrl_cmdFodActivate_DiagCtrlFod_Start */
#if defined(Rte_IReadHook_FOD_WspDiagCtrl_cmdFodActivate_DiagCtrlFod_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IReadHook_FOD_WspDiagCtrl_cmdFodActivate_DiagCtrlFod_Return
#endif
#if defined(Rte_IReadHook_FOD_WspDiagCtrl_cmdFodActivate_DiagCtrlFod_Return)
#undef Rte_IReadHook_FOD_WspDiagCtrl_cmdFodActivate_DiagCtrlFod_Return
extern FUNC(void, RTE_APPL_CODE) Rte_IReadHook_FOD_WspDiagCtrl_cmdFodActivate_DiagCtrlFod_Return(uint8 data);
#else
#define Rte_IReadHook_FOD_WspDiagCtrl_cmdFodActivate_DiagCtrlFod_Return(data) ((void)0)
#endif /* Rte_IReadHook_FOD_WspDiagCtrl_cmdFodActivate_DiagCtrlFod_Return */
#if defined(Rte_IReadHook_FOD_WspDiagCtrl_cmdFodFreeze_DiagCtrlFreeze_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IReadHook_FOD_WspDiagCtrl_cmdFodFreeze_DiagCtrlFreeze_Start
#endif
#if defined(Rte_IReadHook_FOD_WspDiagCtrl_cmdFodFreeze_DiagCtrlFreeze_Start)
#undef Rte_IReadHook_FOD_WspDiagCtrl_cmdFodFreeze_DiagCtrlFreeze_Start
extern FUNC(void, RTE_APPL_CODE) Rte_IReadHook_FOD_WspDiagCtrl_cmdFodFreeze_DiagCtrlFreeze_Start(GenericByte data);
#else
#define Rte_IReadHook_FOD_WspDiagCtrl_cmdFodFreeze_DiagCtrlFreeze_Start(data) ((void)0)
#endif /* Rte_IReadHook_FOD_WspDiagCtrl_cmdFodFreeze_DiagCtrlFreeze_Start */
#if defined(Rte_IReadHook_FOD_WspDiagCtrl_cmdFodFreeze_DiagCtrlFreeze_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IReadHook_FOD_WspDiagCtrl_cmdFodFreeze_DiagCtrlFreeze_Return
#endif
#if defined(Rte_IReadHook_FOD_WspDiagCtrl_cmdFodFreeze_DiagCtrlFreeze_Return)
#undef Rte_IReadHook_FOD_WspDiagCtrl_cmdFodFreeze_DiagCtrlFreeze_Return
extern FUNC(void, RTE_APPL_CODE) Rte_IReadHook_FOD_WspDiagCtrl_cmdFodFreeze_DiagCtrlFreeze_Return(GenericByte data);
#else
#define Rte_IReadHook_FOD_WspDiagCtrl_cmdFodFreeze_DiagCtrlFreeze_Return(data) ((void)0)
#endif /* Rte_IReadHook_FOD_WspDiagCtrl_cmdFodFreeze_DiagCtrlFreeze_Return */
#if defined(Rte_CallHook_FOD_RP_NvMService_GetErrorStatus_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_RP_NvMService_GetErrorStatus_Start
#endif
#if defined(Rte_CallHook_FOD_RP_NvMService_GetErrorStatus_Start)
#undef Rte_CallHook_FOD_RP_NvMService_GetErrorStatus_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_RP_NvMService_GetErrorStatus_Start(P2VAR(NvM_RequestResultType, AUTOMATIC, RTE_APPL_DATA) RequestResultPtr);
#else
#define Rte_CallHook_FOD_RP_NvMService_GetErrorStatus_Start(RequestResultPtr) ((void)0)
#endif /* Rte_CallHook_FOD_RP_NvMService_GetErrorStatus_Start */
#if defined(Rte_CallHook_FOD_RP_NvMService_GetErrorStatus_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_RP_NvMService_GetErrorStatus_Return
#endif
#if defined(Rte_CallHook_FOD_RP_NvMService_GetErrorStatus_Return)
#undef Rte_CallHook_FOD_RP_NvMService_GetErrorStatus_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_RP_NvMService_GetErrorStatus_Return(P2VAR(NvM_RequestResultType, AUTOMATIC, RTE_APPL_DATA) RequestResultPtr);
#else
#define Rte_CallHook_FOD_RP_NvMService_GetErrorStatus_Return(RequestResultPtr) ((void)0)
#endif /* Rte_CallHook_FOD_RP_NvMService_GetErrorStatus_Return */
#if defined(Rte_CallHook_FOD_RP_NvMService_SetDataIndex_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_RP_NvMService_SetDataIndex_Start
#endif
#if defined(Rte_CallHook_FOD_RP_NvMService_SetDataIndex_Start)
#undef Rte_CallHook_FOD_RP_NvMService_SetDataIndex_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_RP_NvMService_SetDataIndex_Start(uint8 DataIndex);
#else
#define Rte_CallHook_FOD_RP_NvMService_SetDataIndex_Start(DataIndex) ((void)0)
#endif /* Rte_CallHook_FOD_RP_NvMService_SetDataIndex_Start */
#if defined(Rte_CallHook_FOD_RP_NvMService_SetDataIndex_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_RP_NvMService_SetDataIndex_Return
#endif
#if defined(Rte_CallHook_FOD_RP_NvMService_SetDataIndex_Return)
#undef Rte_CallHook_FOD_RP_NvMService_SetDataIndex_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_RP_NvMService_SetDataIndex_Return(uint8 DataIndex);
#else
#define Rte_CallHook_FOD_RP_NvMService_SetDataIndex_Return(DataIndex) ((void)0)
#endif /* Rte_CallHook_FOD_RP_NvMService_SetDataIndex_Return */
#if defined(Rte_CallHook_FOD_RP_NvMService_GetDataIndex_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_RP_NvMService_GetDataIndex_Start
#endif
#if defined(Rte_CallHook_FOD_RP_NvMService_GetDataIndex_Start)
#undef Rte_CallHook_FOD_RP_NvMService_GetDataIndex_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_RP_NvMService_GetDataIndex_Start(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DataIndexPtr);
#else
#define Rte_CallHook_FOD_RP_NvMService_GetDataIndex_Start(DataIndexPtr) ((void)0)
#endif /* Rte_CallHook_FOD_RP_NvMService_GetDataIndex_Start */
#if defined(Rte_CallHook_FOD_RP_NvMService_GetDataIndex_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_RP_NvMService_GetDataIndex_Return
#endif
#if defined(Rte_CallHook_FOD_RP_NvMService_GetDataIndex_Return)
#undef Rte_CallHook_FOD_RP_NvMService_GetDataIndex_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_RP_NvMService_GetDataIndex_Return(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DataIndexPtr);
#else
#define Rte_CallHook_FOD_RP_NvMService_GetDataIndex_Return(DataIndexPtr) ((void)0)
#endif /* Rte_CallHook_FOD_RP_NvMService_GetDataIndex_Return */
#if defined(Rte_CallHook_FOD_RP_NvMService_SetRamBlockStatus_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_RP_NvMService_SetRamBlockStatus_Start
#endif
#if defined(Rte_CallHook_FOD_RP_NvMService_SetRamBlockStatus_Start)
#undef Rte_CallHook_FOD_RP_NvMService_SetRamBlockStatus_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_RP_NvMService_SetRamBlockStatus_Start(boolean BlockChanged);
#else
#define Rte_CallHook_FOD_RP_NvMService_SetRamBlockStatus_Start(BlockChanged) ((void)0)
#endif /* Rte_CallHook_FOD_RP_NvMService_SetRamBlockStatus_Start */
#if defined(Rte_CallHook_FOD_RP_NvMService_SetRamBlockStatus_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_RP_NvMService_SetRamBlockStatus_Return
#endif
#if defined(Rte_CallHook_FOD_RP_NvMService_SetRamBlockStatus_Return)
#undef Rte_CallHook_FOD_RP_NvMService_SetRamBlockStatus_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_RP_NvMService_SetRamBlockStatus_Return(boolean BlockChanged);
#else
#define Rte_CallHook_FOD_RP_NvMService_SetRamBlockStatus_Return(BlockChanged) ((void)0)
#endif /* Rte_CallHook_FOD_RP_NvMService_SetRamBlockStatus_Return */
#if defined(Rte_CallHook_FOD_RP_NvMService_ReadBlock_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_RP_NvMService_ReadBlock_Start
#endif
#if defined(Rte_CallHook_FOD_RP_NvMService_ReadBlock_Start)
#undef Rte_CallHook_FOD_RP_NvMService_ReadBlock_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_RP_NvMService_ReadBlock_Start(NvM_DstPtrType DstPtr);
#else
#define Rte_CallHook_FOD_RP_NvMService_ReadBlock_Start(DstPtr) ((void)0)
#endif /* Rte_CallHook_FOD_RP_NvMService_ReadBlock_Start */
#if defined(Rte_CallHook_FOD_RP_NvMService_ReadBlock_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_RP_NvMService_ReadBlock_Return
#endif
#if defined(Rte_CallHook_FOD_RP_NvMService_ReadBlock_Return)
#undef Rte_CallHook_FOD_RP_NvMService_ReadBlock_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_RP_NvMService_ReadBlock_Return(NvM_DstPtrType DstPtr);
#else
#define Rte_CallHook_FOD_RP_NvMService_ReadBlock_Return(DstPtr) ((void)0)
#endif /* Rte_CallHook_FOD_RP_NvMService_ReadBlock_Return */
#if defined(Rte_CallHook_FOD_RP_NvMService_WriteBlock_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_RP_NvMService_WriteBlock_Start
#endif
#if defined(Rte_CallHook_FOD_RP_NvMService_WriteBlock_Start)
#undef Rte_CallHook_FOD_RP_NvMService_WriteBlock_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_RP_NvMService_WriteBlock_Start(NvM_SrcPtrType SrcPtr);
#else
#define Rte_CallHook_FOD_RP_NvMService_WriteBlock_Start(SrcPtr) ((void)0)
#endif /* Rte_CallHook_FOD_RP_NvMService_WriteBlock_Start */
#if defined(Rte_CallHook_FOD_RP_NvMService_WriteBlock_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_RP_NvMService_WriteBlock_Return
#endif
#if defined(Rte_CallHook_FOD_RP_NvMService_WriteBlock_Return)
#undef Rte_CallHook_FOD_RP_NvMService_WriteBlock_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_RP_NvMService_WriteBlock_Return(NvM_SrcPtrType SrcPtr);
#else
#define Rte_CallHook_FOD_RP_NvMService_WriteBlock_Return(SrcPtr) ((void)0)
#endif /* Rte_CallHook_FOD_RP_NvMService_WriteBlock_Return */
#if defined(Rte_CallHook_FOD_RP_NvMService_RestoreBlockDefaults_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_RP_NvMService_RestoreBlockDefaults_Start
#endif
#if defined(Rte_CallHook_FOD_RP_NvMService_RestoreBlockDefaults_Start)
#undef Rte_CallHook_FOD_RP_NvMService_RestoreBlockDefaults_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_RP_NvMService_RestoreBlockDefaults_Start(NvM_DstPtrType DstPtr);
#else
#define Rte_CallHook_FOD_RP_NvMService_RestoreBlockDefaults_Start(DstPtr) ((void)0)
#endif /* Rte_CallHook_FOD_RP_NvMService_RestoreBlockDefaults_Start */
#if defined(Rte_CallHook_FOD_RP_NvMService_RestoreBlockDefaults_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_RP_NvMService_RestoreBlockDefaults_Return
#endif
#if defined(Rte_CallHook_FOD_RP_NvMService_RestoreBlockDefaults_Return)
#undef Rte_CallHook_FOD_RP_NvMService_RestoreBlockDefaults_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_RP_NvMService_RestoreBlockDefaults_Return(NvM_DstPtrType DstPtr);
#else
#define Rte_CallHook_FOD_RP_NvMService_RestoreBlockDefaults_Return(DstPtr) ((void)0)
#endif /* Rte_CallHook_FOD_RP_NvMService_RestoreBlockDefaults_Return */
#if defined(Rte_CallHook_FOD_RP_NvMService_InvalidateNvBlock_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_RP_NvMService_InvalidateNvBlock_Start
#endif
#if defined(Rte_CallHook_FOD_RP_NvMService_InvalidateNvBlock_Start)
#undef Rte_CallHook_FOD_RP_NvMService_InvalidateNvBlock_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_RP_NvMService_InvalidateNvBlock_Start(void);
#else
#define Rte_CallHook_FOD_RP_NvMService_InvalidateNvBlock_Start() ((void)0)
#endif /* Rte_CallHook_FOD_RP_NvMService_InvalidateNvBlock_Start */
#if defined(Rte_CallHook_FOD_RP_NvMService_InvalidateNvBlock_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_RP_NvMService_InvalidateNvBlock_Return
#endif
#if defined(Rte_CallHook_FOD_RP_NvMService_InvalidateNvBlock_Return)
#undef Rte_CallHook_FOD_RP_NvMService_InvalidateNvBlock_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_RP_NvMService_InvalidateNvBlock_Return(void);
#else
#define Rte_CallHook_FOD_RP_NvMService_InvalidateNvBlock_Return() ((void)0)
#endif /* Rte_CallHook_FOD_RP_NvMService_InvalidateNvBlock_Return */
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_SetEventStatus_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_SetEventStatus_Start
#endif
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_SetEventStatus_Start)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_SetEventStatus_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_Event_METAL_ON_PAD_SetEventStatus_Start(Dem_EventStatusType EventStatus);
#else
#define Rte_CallHook_FOD_Event_METAL_ON_PAD_SetEventStatus_Start(EventStatus) ((void)0)
#endif /* Rte_CallHook_FOD_Event_METAL_ON_PAD_SetEventStatus_Start */
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_SetEventStatus_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_SetEventStatus_Return
#endif
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_SetEventStatus_Return)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_SetEventStatus_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_Event_METAL_ON_PAD_SetEventStatus_Return(Dem_EventStatusType EventStatus);
#else
#define Rte_CallHook_FOD_Event_METAL_ON_PAD_SetEventStatus_Return(EventStatus) ((void)0)
#endif /* Rte_CallHook_FOD_Event_METAL_ON_PAD_SetEventStatus_Return */
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_ResetEventStatus_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_ResetEventStatus_Start
#endif
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_ResetEventStatus_Start)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_ResetEventStatus_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_Event_METAL_ON_PAD_ResetEventStatus_Start(void);
#else
#define Rte_CallHook_FOD_Event_METAL_ON_PAD_ResetEventStatus_Start() ((void)0)
#endif /* Rte_CallHook_FOD_Event_METAL_ON_PAD_ResetEventStatus_Start */
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_ResetEventStatus_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_ResetEventStatus_Return
#endif
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_ResetEventStatus_Return)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_ResetEventStatus_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_Event_METAL_ON_PAD_ResetEventStatus_Return(void);
#else
#define Rte_CallHook_FOD_Event_METAL_ON_PAD_ResetEventStatus_Return() ((void)0)
#endif /* Rte_CallHook_FOD_Event_METAL_ON_PAD_ResetEventStatus_Return */
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventStatus_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventStatus_Start
#endif
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventStatus_Start)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventStatus_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventStatus_Start(P2VAR(Dem_EventStatusExtendedType, AUTOMATIC, RTE_APPL_DATA) EventStatusExtended);
#else
#define Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventStatus_Start(EventStatusExtended) ((void)0)
#endif /* Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventStatus_Start */
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventStatus_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventStatus_Return
#endif
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventStatus_Return)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventStatus_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventStatus_Return(P2VAR(Dem_EventStatusExtendedType, AUTOMATIC, RTE_APPL_DATA) EventStatusExtended);
#else
#define Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventStatus_Return(EventStatusExtended) ((void)0)
#endif /* Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventStatus_Return */
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventFailed_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventFailed_Start
#endif
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventFailed_Start)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventFailed_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventFailed_Start(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) EventFailed);
#else
#define Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventFailed_Start(EventFailed) ((void)0)
#endif /* Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventFailed_Start */
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventFailed_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventFailed_Return
#endif
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventFailed_Return)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventFailed_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventFailed_Return(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) EventFailed);
#else
#define Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventFailed_Return(EventFailed) ((void)0)
#endif /* Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventFailed_Return */
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventTested_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventTested_Start
#endif
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventTested_Start)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventTested_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventTested_Start(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) EventTested);
#else
#define Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventTested_Start(EventTested) ((void)0)
#endif /* Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventTested_Start */
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventTested_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventTested_Return
#endif
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventTested_Return)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventTested_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventTested_Return(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) EventTested);
#else
#define Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventTested_Return(EventTested) ((void)0)
#endif /* Rte_CallHook_FOD_Event_METAL_ON_PAD_GetEventTested_Return */
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_GetDTCOfEvent_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_GetDTCOfEvent_Start
#endif
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_GetDTCOfEvent_Start)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_GetDTCOfEvent_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_Event_METAL_ON_PAD_GetDTCOfEvent_Start(Dem_DTCKindType DTCKind, P2VAR(Dem_DTCType, AUTOMATIC, RTE_APPL_DATA) DTCofEvent);
#else
#define Rte_CallHook_FOD_Event_METAL_ON_PAD_GetDTCOfEvent_Start(DTCKind, DTCofEvent) ((void)0)
#endif /* Rte_CallHook_FOD_Event_METAL_ON_PAD_GetDTCOfEvent_Start */
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_GetDTCOfEvent_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_GetDTCOfEvent_Return
#endif
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_GetDTCOfEvent_Return)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_GetDTCOfEvent_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_Event_METAL_ON_PAD_GetDTCOfEvent_Return(Dem_DTCKindType DTCKind, P2VAR(Dem_DTCType, AUTOMATIC, RTE_APPL_DATA) DTCofEvent);
#else
#define Rte_CallHook_FOD_Event_METAL_ON_PAD_GetDTCOfEvent_Return(DTCKind, DTCofEvent) ((void)0)
#endif /* Rte_CallHook_FOD_Event_METAL_ON_PAD_GetDTCOfEvent_Return */
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_PrestoreFreezeFrame_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_PrestoreFreezeFrame_Start
#endif
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_PrestoreFreezeFrame_Start)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_PrestoreFreezeFrame_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_Event_METAL_ON_PAD_PrestoreFreezeFrame_Start(void);
#else
#define Rte_CallHook_FOD_Event_METAL_ON_PAD_PrestoreFreezeFrame_Start() ((void)0)
#endif /* Rte_CallHook_FOD_Event_METAL_ON_PAD_PrestoreFreezeFrame_Start */
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_PrestoreFreezeFrame_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_PrestoreFreezeFrame_Return
#endif
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_PrestoreFreezeFrame_Return)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_PrestoreFreezeFrame_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_Event_METAL_ON_PAD_PrestoreFreezeFrame_Return(void);
#else
#define Rte_CallHook_FOD_Event_METAL_ON_PAD_PrestoreFreezeFrame_Return() ((void)0)
#endif /* Rte_CallHook_FOD_Event_METAL_ON_PAD_PrestoreFreezeFrame_Return */
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_ClearPrestoredFreezeFrame_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_ClearPrestoredFreezeFrame_Start
#endif
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_ClearPrestoredFreezeFrame_Start)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_ClearPrestoredFreezeFrame_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_Event_METAL_ON_PAD_ClearPrestoredFreezeFrame_Start(void);
#else
#define Rte_CallHook_FOD_Event_METAL_ON_PAD_ClearPrestoredFreezeFrame_Start() ((void)0)
#endif /* Rte_CallHook_FOD_Event_METAL_ON_PAD_ClearPrestoredFreezeFrame_Start */
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_ClearPrestoredFreezeFrame_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_ClearPrestoredFreezeFrame_Return
#endif
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_ClearPrestoredFreezeFrame_Return)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_ClearPrestoredFreezeFrame_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_Event_METAL_ON_PAD_ClearPrestoredFreezeFrame_Return(void);
#else
#define Rte_CallHook_FOD_Event_METAL_ON_PAD_ClearPrestoredFreezeFrame_Return() ((void)0)
#endif /* Rte_CallHook_FOD_Event_METAL_ON_PAD_ClearPrestoredFreezeFrame_Return */
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_GetFaultDetectionCounter_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_GetFaultDetectionCounter_Start
#endif
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_GetFaultDetectionCounter_Start)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_GetFaultDetectionCounter_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_Event_METAL_ON_PAD_GetFaultDetectionCounter_Start(P2VAR(Dem_FaultDetectionCounterType, AUTOMATIC, RTE_APPL_DATA) EventIdFaultDetectionCounter);
#else
#define Rte_CallHook_FOD_Event_METAL_ON_PAD_GetFaultDetectionCounter_Start(EventIdFaultDetectionCounter) ((void)0)
#endif /* Rte_CallHook_FOD_Event_METAL_ON_PAD_GetFaultDetectionCounter_Start */
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_GetFaultDetectionCounter_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_GetFaultDetectionCounter_Return
#endif
#if defined(Rte_CallHook_FOD_Event_METAL_ON_PAD_GetFaultDetectionCounter_Return)
#undef Rte_CallHook_FOD_Event_METAL_ON_PAD_GetFaultDetectionCounter_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_Event_METAL_ON_PAD_GetFaultDetectionCounter_Return(P2VAR(Dem_FaultDetectionCounterType, AUTOMATIC, RTE_APPL_DATA) EventIdFaultDetectionCounter);
#else
#define Rte_CallHook_FOD_Event_METAL_ON_PAD_GetFaultDetectionCounter_Return(EventIdFaultDetectionCounter) ((void)0)
#endif /* Rte_CallHook_FOD_Event_METAL_ON_PAD_GetFaultDetectionCounter_Return */
#if defined(Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_CheckpointReached_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_CheckpointReached_Start
#endif
#if defined(Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_CheckpointReached_Start)
#undef Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_CheckpointReached_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_CheckpointReached_Start(WdgM_CheckpointIdType CheckpointId);
#else
#define Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_CheckpointReached_Start(CheckpointId) ((void)0)
#endif /* Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_CheckpointReached_Start */
#if defined(Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_CheckpointReached_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_CheckpointReached_Return
#endif
#if defined(Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_CheckpointReached_Return)
#undef Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_CheckpointReached_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_CheckpointReached_Return(WdgM_CheckpointIdType CheckpointId);
#else
#define Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_CheckpointReached_Return(CheckpointId) ((void)0)
#endif /* Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_CheckpointReached_Return */
#if defined(Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_UpdateAliveCounter_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_UpdateAliveCounter_Start
#endif
#if defined(Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_UpdateAliveCounter_Start)
#undef Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_UpdateAliveCounter_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_UpdateAliveCounter_Start(void);
#else
#define Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_UpdateAliveCounter_Start() ((void)0)
#endif /* Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_UpdateAliveCounter_Start */
#if defined(Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_UpdateAliveCounter_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_UpdateAliveCounter_Return
#endif
#if defined(Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_UpdateAliveCounter_Return)
#undef Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_UpdateAliveCounter_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_UpdateAliveCounter_Return(void);
#else
#define Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_UpdateAliveCounter_Return() ((void)0)
#endif /* Rte_CallHook_FOD_alive_WdgMSvEnt_FodMgr_UpdateAliveCounter_Return */
#if defined(Rte_IrvReadHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IrvReadHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Start
#endif
#if defined(Rte_IrvReadHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Start)
#undef Rte_IrvReadHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Start
extern FUNC(void, RTE_APPL_CODE) Rte_IrvReadHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Start(void);
#else
#define Rte_IrvReadHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Start() ((void)0)
#endif /* Rte_IrvReadHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Start */
#if defined(Rte_IrvReadHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IrvReadHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Return
#endif
#if defined(Rte_IrvReadHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Return)
#undef Rte_IrvReadHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Return
extern FUNC(void, RTE_APPL_CODE) Rte_IrvReadHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Return(void);
#else
#define Rte_IrvReadHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Return() ((void)0)
#endif /* Rte_IrvReadHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Return */
#if defined(Rte_IrvWriteHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IrvWriteHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Start
#endif
#if defined(Rte_IrvWriteHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Start)
#undef Rte_IrvWriteHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Start
extern FUNC(void, RTE_APPL_CODE) Rte_IrvWriteHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Start(GenericByte data);
#else
#define Rte_IrvWriteHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Start(data) ((void)0)
#endif /* Rte_IrvWriteHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Start */
#if defined(Rte_IrvWriteHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_IrvWriteHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Return
#endif
#if defined(Rte_IrvWriteHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Return)
#undef Rte_IrvWriteHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Return
extern FUNC(void, RTE_APPL_CODE) Rte_IrvWriteHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Return(GenericByte data);
#else
#define Rte_IrvWriteHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Return(data) ((void)0)
#endif /* Rte_IrvWriteHook_FOD_WsFodMgr_NullVector_Start_NvFlag_Return */
#if defined(Rte_Runnable_FOD_WsFodMgr_MainFunction_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_FOD_WsFodMgr_MainFunction_Start
#endif
#if defined(Rte_Runnable_FOD_WsFodMgr_MainFunction_Start)
#undef Rte_Runnable_FOD_WsFodMgr_MainFunction_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_FOD_WsFodMgr_MainFunction_Start(void);
#else
#define Rte_Runnable_FOD_WsFodMgr_MainFunction_Start() ((void)0)
#endif /* Rte_Runnable_FOD_WsFodMgr_MainFunction_Start */
#if defined(Rte_Runnable_FOD_WsFodMgr_MainFunction_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_FOD_WsFodMgr_MainFunction_Return
#endif
#if defined(Rte_Runnable_FOD_WsFodMgr_MainFunction_Return)
#undef Rte_Runnable_FOD_WsFodMgr_MainFunction_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_FOD_WsFodMgr_MainFunction_Return(void);
#else
#define Rte_Runnable_FOD_WsFodMgr_MainFunction_Return() ((void)0)
#endif /* Rte_Runnable_FOD_WsFodMgr_MainFunction_Return */
#if defined(Rte_Runnable_FOD_WsFodMgr_NullVector_Start_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_FOD_WsFodMgr_NullVector_Start_Start
#endif
#if defined(Rte_Runnable_FOD_WsFodMgr_NullVector_Start_Start)
#undef Rte_Runnable_FOD_WsFodMgr_NullVector_Start_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_FOD_WsFodMgr_NullVector_Start_Start(void);
#else
#define Rte_Runnable_FOD_WsFodMgr_NullVector_Start_Start() ((void)0)
#endif /* Rte_Runnable_FOD_WsFodMgr_NullVector_Start_Start */
#if defined(Rte_Runnable_FOD_WsFodMgr_NullVector_Start_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_FOD_WsFodMgr_NullVector_Start_Return
#endif
#if defined(Rte_Runnable_FOD_WsFodMgr_NullVector_Start_Return)
#undef Rte_Runnable_FOD_WsFodMgr_NullVector_Start_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_FOD_WsFodMgr_NullVector_Start_Return(void);
#else
#define Rte_Runnable_FOD_WsFodMgr_NullVector_Start_Return() ((void)0)
#endif /* Rte_Runnable_FOD_WsFodMgr_NullVector_Start_Return */

/*==================[type definitions]=======================================*/

/*==================[external function declarations]=========================*/

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/
/** @} doxygen end group definition */
#endif /* !defined(RTE_FOD_HOOK_H) */
/*==================[end of file]============================================*/

