#if !defined(RTE_FOD_TYPE_H)
#define RTE_FOD_TYPE_H

/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains the application-specific types for component type FOD
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Fri Feb 09 14:59:49 CET 2018. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

/*==================[inclusions]=============================================*/

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <Rte_Type.h>         /* RTE types header file */

/*==================[macros]=================================================*/

/*------------------[enumeration constants]----------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#ifndef SFTY_NO_INIT
#define SFTY_NO_INIT 0U
#endif /* SFTY_NO_INIT */

#ifndef SFTY_OFF
#define SFTY_OFF 90U
#endif /* SFTY_OFF */

#ifndef SFTY_ON
#define SFTY_ON 150U
#endif /* SFTY_ON */

#ifndef SFTY_OFF_C1
#define SFTY_OFF_C1 165U
#endif /* SFTY_OFF_C1 */

#ifndef SFTY_ON_C1
#define SFTY_ON_C1 105U
#endif /* SFTY_ON_C1 */

#ifndef NVM_REQ_OK
#define NVM_REQ_OK 0U
#endif /* NVM_REQ_OK */

#ifndef NVM_REQ_NOT_OK
#define NVM_REQ_NOT_OK 1U
#endif /* NVM_REQ_NOT_OK */

#ifndef NVM_REQ_PENDING
#define NVM_REQ_PENDING 2U
#endif /* NVM_REQ_PENDING */

#ifndef NVM_REQ_INTEGRITY_FAILED
#define NVM_REQ_INTEGRITY_FAILED 3U
#endif /* NVM_REQ_INTEGRITY_FAILED */

#ifndef NVM_REQ_BLOCK_SKIPPED
#define NVM_REQ_BLOCK_SKIPPED 4U
#endif /* NVM_REQ_BLOCK_SKIPPED */

#ifndef NVM_REQ_NV_INVALIDATED
#define NVM_REQ_NV_INVALIDATED 5U
#endif /* NVM_REQ_NV_INVALIDATED */

#ifndef NVM_REQ_CANCELED
#define NVM_REQ_CANCELED 6U
#endif /* NVM_REQ_CANCELED */

#ifndef NVM_REQ_REDUNDANCY_FAILED
#define NVM_REQ_REDUNDANCY_FAILED 7U
#endif /* NVM_REQ_REDUNDANCY_FAILED */

#ifndef NVM_REQ_RESTORED_FROM_ROM
#define NVM_REQ_RESTORED_FROM_ROM 8U
#endif /* NVM_REQ_RESTORED_FROM_ROM */

#ifndef DEM_EVENT_STATUS_PASSED
#define DEM_EVENT_STATUS_PASSED 0U
#endif /* DEM_EVENT_STATUS_PASSED */

#ifndef DEM_EVENT_STATUS_FAILED
#define DEM_EVENT_STATUS_FAILED 1U
#endif /* DEM_EVENT_STATUS_FAILED */

#ifndef DEM_EVENT_STATUS_PREPASSED
#define DEM_EVENT_STATUS_PREPASSED 2U
#endif /* DEM_EVENT_STATUS_PREPASSED */

#ifndef DEM_EVENT_STATUS_PREFAILED
#define DEM_EVENT_STATUS_PREFAILED 3U
#endif /* DEM_EVENT_STATUS_PREFAILED */

#ifndef DEM_UDS_STATUS_TF
#define DEM_UDS_STATUS_TF 1U
#endif /* DEM_UDS_STATUS_TF */

#ifndef DEM_UDS_STATUS_TFTOC
#define DEM_UDS_STATUS_TFTOC 2U
#endif /* DEM_UDS_STATUS_TFTOC */

#ifndef DEM_UDS_STATUS_PDTC
#define DEM_UDS_STATUS_PDTC 4U
#endif /* DEM_UDS_STATUS_PDTC */

#ifndef DEM_UDS_STATUS_CDTC
#define DEM_UDS_STATUS_CDTC 8U
#endif /* DEM_UDS_STATUS_CDTC */

#ifndef DEM_UDS_STATUS_TNCSLC
#define DEM_UDS_STATUS_TNCSLC 16U
#endif /* DEM_UDS_STATUS_TNCSLC */

#ifndef DEM_UDS_STATUS_TFSLC
#define DEM_UDS_STATUS_TFSLC 32U
#endif /* DEM_UDS_STATUS_TFSLC */

#ifndef DEM_UDS_STATUS_TNCTOC
#define DEM_UDS_STATUS_TNCTOC 64U
#endif /* DEM_UDS_STATUS_TNCTOC */

#ifndef DEM_UDS_STATUS_WIR
#define DEM_UDS_STATUS_WIR 128U
#endif /* DEM_UDS_STATUS_WIR */

#ifndef DEM_DTC_KIND_ALL_DTCS
#define DEM_DTC_KIND_ALL_DTCS 1U
#endif /* DEM_DTC_KIND_ALL_DTCS */

#ifndef DEM_DTC_KIND_EMISSION_REL_DTCS
#define DEM_DTC_KIND_EMISSION_REL_DTCS 2U
#endif /* DEM_DTC_KIND_EMISSION_REL_DTCS */

#ifndef SFTY_FALSE
#define SFTY_FALSE 90U
#endif /* SFTY_FALSE */

#ifndef SFTY_TRUE
#define SFTY_TRUE 150U
#endif /* SFTY_TRUE */

#ifndef SFTY_FALSE_C1
#define SFTY_FALSE_C1 165U
#endif /* SFTY_FALSE_C1 */

#ifndef SFTY_TRUE_C1
#define SFTY_TRUE_C1 105U
#endif /* SFTY_TRUE_C1 */

#ifndef WdgMConf_WdgMCheckpoint_WdgMCheckpoint_SftyIoReadFromHw
#define WdgMConf_WdgMCheckpoint_WdgMCheckpoint_SftyIoReadFromHw 0U
#endif /* WdgMConf_WdgMCheckpoint_WdgMCheckpoint_SftyIoReadFromHw */

#ifndef WdgMConf_WdgMCheckpoint_WdgMCheckpoint_SftyMain
#define WdgMConf_WdgMCheckpoint_WdgMCheckpoint_SftyMain 0U
#endif /* WdgMConf_WdgMCheckpoint_WdgMCheckpoint_SftyMain */

#ifndef WdgMConf_WdgMCheckpoint_WdgMCheckpoint_SftyCalc
#define WdgMConf_WdgMCheckpoint_WdgMCheckpoint_SftyCalc 0U
#endif /* WdgMConf_WdgMCheckpoint_WdgMCheckpoint_SftyCalc */

#ifndef WdgMConf_WdgMCheckpoint_WdgMCheckpoint_SftyPinch
#define WdgMConf_WdgMCheckpoint_WdgMCheckpoint_SftyPinch 0U
#endif /* WdgMConf_WdgMCheckpoint_WdgMCheckpoint_SftyPinch */

#ifndef WdgMConf_WdgMCheckpoint_WdgMCheckpoint_SftyIoWriteToHw
#define WdgMConf_WdgMCheckpoint_WdgMCheckpoint_SftyIoWriteToHw 0U
#endif /* WdgMConf_WdgMCheckpoint_WdgMCheckpoint_SftyIoWriteToHw */

#ifndef WdgMConf_WdgMCheckpoint_WdgMCheckpoint_VehDetDwnSmpl
#define WdgMConf_WdgMCheckpoint_WdgMCheckpoint_VehDetDwnSmpl 0U
#endif /* WdgMConf_WdgMCheckpoint_WdgMCheckpoint_VehDetDwnSmpl */

#ifndef WdgMConf_WdgMCheckpoint_WdgMCheckpoint_VehDetMain
#define WdgMConf_WdgMCheckpoint_WdgMCheckpoint_VehDetMain 0U
#endif /* WdgMConf_WdgMCheckpoint_WdgMCheckpoint_VehDetMain */

#ifndef WdgMConf_WdgMCheckpoint_WdgMCheckpoint_FodMgr
#define WdgMConf_WdgMCheckpoint_WdgMCheckpoint_FodMgr 0U
#endif /* WdgMConf_WdgMCheckpoint_WdgMCheckpoint_FodMgr */

#ifndef WdgMConf_WdgMCheckpoint_WdgMCheckpoint_StMgr
#define WdgMConf_WdgMCheckpoint_WdgMCheckpoint_StMgr 0U
#endif /* WdgMConf_WdgMCheckpoint_WdgMCheckpoint_StMgr */

#endif /* (!defined RTE_CORE) */

/*------------------[range definitions]--------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#endif /* (!defined RTE_CORE) */

/*------------------[invalid values]-----------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#endif /* (!defined RTE_CORE) */

/*------------------[mode declarations]--------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#ifndef RTE_TRANSITION_ModModeGroup
#define RTE_TRANSITION_ModModeGroup 5U
#endif

#ifndef RTE_MODE_ModModeGroup_MOD_FOD_ACTIVE
#define RTE_MODE_ModModeGroup_MOD_FOD_ACTIVE 0U
#endif

#ifndef RTE_MODE_ModModeGroup_MOD_FREEZE
#define RTE_MODE_ModModeGroup_MOD_FREEZE 1U
#endif

#ifndef RTE_MODE_ModModeGroup_MOD_INACTIVE
#define RTE_MODE_ModModeGroup_MOD_INACTIVE 2U
#endif

#ifndef RTE_MODE_ModModeGroup_MOD_ON_CHANGE
#define RTE_MODE_ModModeGroup_MOD_ON_CHANGE 3U
#endif

#ifndef RTE_MODE_ModModeGroup_MOD_POS_ACTIVE
#define RTE_MODE_ModModeGroup_MOD_POS_ACTIVE 4U
#endif

#endif /* (!defined RTE_CORE) */

/*==================[type definitions]=======================================*/

/*------------------[mode declaration group types]---------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#ifndef RTE_MODETYPE_ModModeGroup
#define RTE_MODETYPE_ModModeGroup
typedef uint8 Rte_ModeType_ModModeGroup;
#endif

#endif /* (!defined RTE_CORE) */

/*==================[external function declarations]=========================*/

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */
/** @} doxygen end group definition */
#endif /* !defined(RTE_FOD_TYPE_H) */
/*==================[end of file]============================================*/

