
/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains an Rte component template / example code
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Mon Sep 11 10:38:58 CEST 2017. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#include "Rte_SCI_Pfc.h"
#include "LINFlexUARTMode.h"

/*------------------------[BSW runnable entity skeletons]------------------------*/

void BswSCI_Pfc_BswMainFunction(void)
{
    PFC_SYNC();
}

/*------------------------[runnable entity skeletons]------------------------*/

void pfc_MainFunction (void)
{
  ErrorState WSErrorState;
  uint16 ErrorId;
  /*Dem_FaultDetectionCounterType EventIdFaultDetectionCounter_6;
  Dem_DTCType DTCofEvent_6;
  Dem_DTCKindType DTCKind_6;
  boolean EventTested_6;
  boolean EventFailed_6;
  Dem_EventStatusExtendedType EventStatusExtended_6;
  Dem_EventStatusType EventStatus_6;
  Dem_FaultDetectionCounterType EventIdFaultDetectionCounter_5;
  Dem_DTCType DTCofEvent_5;
  Dem_DTCKindType DTCKind_5;
  boolean EventTested_5;
  boolean EventFailed_5;
  Dem_EventStatusExtendedType EventStatusExtended_5;
  Dem_EventStatusType EventStatus_5;
  Dem_FaultDetectionCounterType EventIdFaultDetectionCounter_4;
  Dem_DTCType DTCofEvent_4;
  Dem_DTCKindType DTCKind_4;
  boolean EventTested_4;
  boolean EventFailed_4;
  Dem_EventStatusExtendedType EventStatusExtended_4;
  Dem_EventStatusType EventStatus_4;
  Dem_FaultDetectionCounterType EventIdFaultDetectionCounter_3;
  Dem_DTCType DTCofEvent_3;
  Dem_DTCKindType DTCKind_3;
  boolean EventTested_3;
  boolean EventFailed_3;
  Dem_EventStatusExtendedType EventStatusExtended_3;
  Dem_EventStatusType EventStatus_3;
  Dem_FaultDetectionCounterType EventIdFaultDetectionCounter_2;
  Dem_DTCType DTCofEvent_2;
  Dem_DTCKindType DTCKind_2;
  boolean EventTested_2;
  boolean EventFailed_2;
  Dem_EventStatusExtendedType EventStatusExtended_2;
  Dem_EventStatusType EventStatus_2;
  Dem_FaultDetectionCounterType EventIdFaultDetectionCounter_1;
  Dem_DTCType DTCofEvent_1;
  Dem_DTCKindType DTCKind_1;
  boolean EventTested_1;
  boolean EventFailed_1;
  Dem_EventStatusExtendedType EventStatusExtended_1;
  Dem_EventStatusType EventStatus_1;
  Dem_FaultDetectionCounterType EventIdFaultDetectionCounter_0;
  Dem_DTCType DTCofEvent_0;
  Dem_DTCKindType DTCKind_0;
  boolean EventTested_0;
  boolean EventFailed_0;
  Dem_EventStatusExtendedType EventStatusExtended_0;
  Dem_EventStatusType EventStatus_0;
  Dem_FaultDetectionCounterType EventIdFaultDetectionCounter;
  Dem_DTCType DTCofEvent;
  Dem_DTCKindType DTCKind;
  boolean EventTested;
  boolean EventFailed;
  Dem_EventStatusExtendedType EventStatusExtended;
  Dem_EventStatusType EventStatus; */
  Voltage_s32 milliVoltValue;
  uint8 Cmd;
  //P2VAR(Power_u16, AUTOMATIC, AUTOMATIC) PowerValue_0;
  Power_u16 PowerValue;
 // P2VAR(Period_u32, AUTOMATIC, AUTOMATIC) SCI_Pfc_Period_u32_TValue_0;
  Period_u32 SCI_Pfc_Period_u32_TValue;
  //P2VAR(Voltage_s32, AUTOMATIC, AUTOMATIC) SCI_Pfc_Voltage_s32Value_2;
  Voltage_s32 SCI_Pfc_Voltage_s32Value_1;
 // P2VAR(Current_s32, AUTOMATIC, AUTOMATIC) SCI_Pfc_Current_s32Value_0;
  Current_s32 SCI_Pfc_Current_s32Value;
  //P2VAR(Voltage_s32, AUTOMATIC, AUTOMATIC) SCI_Pfc_Voltage_s32Value_0;
  Voltage_s32 SCI_Pfc_Voltage_s32Value;
  //P2VAR(ErrorCode_u32, AUTOMATIC, AUTOMATIC) SCI_Pfc_ErrorState_u32_TValue_0;
  ErrorCode_u32 SCI_Pfc_ErrorState_u32_TValue;
  //P2VAR(GenericByte, AUTOMATIC, AUTOMATIC) SCI_Pfc_State_u8_TValue_0;
  GenericByte SCI_Pfc_State_u8_TValue;
  //Std_ReturnType status;

  SCI_Pfc_State_u8_TValue = PFC_GET_STATE();
// TODO  Rte_IWrite_pfc_MainFunction_WspPfcCdd_stPfc_SCI_Pfc_State_u8_TValue(SCI_Pfc_State_u8_TValue);
  //SCI_Pfc_State_u8_TValue_0 = Rte_IWriteRef_pfc_MainFunction_PP_State_u8_T_SCI_Pfc_State_u8_TValue();
  
  SCI_Pfc_ErrorState_u32_TValue = PFC_GET_ErrorCode();
  Rte_IWrite_pfc_MainFunction_WspPfcCdd_stPfcErr_SCI_Pfc_ErrorState_u32_TValue(SCI_Pfc_ErrorState_u32_TValue);
  //SCI_Pfc_ErrorState_u32_TValue_0 = Rte_IWriteRef_pfc_MainFunction_PP_ErrorState_u32_T_SCI_Pfc_ErrorState_u32_TValue();
 
  if(SCI_Pfc_ErrorState_u32_TValue & PFC_ERR_IN_UART_INIT)
  { /* in case of the relevant errors are present */
    (void)Rte_Call_Event_PFC_MCU_UART_ERROR_SetEventStatus(DEM_EVENT_STATUS_PREFAILED);
  }
  else
  { /* in case of the relevant errors are NOT present */
    (void)Rte_Call_Event_PFC_MCU_UART_ERROR_SetEventStatus(DEM_EVENT_STATUS_PREPASSED);
  }
  
  if(SCI_Pfc_ErrorState_u32_TValue & PFC_STATE_NO_COM_ERR)
  { /* in case of the relevant errors are present */
    (void)Rte_Call_Event_PFC_UART_COMM_ERROR_SetEventStatus(DEM_EVENT_STATUS_PREFAILED);
  }
  else
  { /* in case of the relevant errors are NOT present */
    (void)Rte_Call_Event_PFC_UART_COMM_ERROR_SetEventStatus(DEM_EVENT_STATUS_PREPASSED);
  }
  
  if(SCI_Pfc_ErrorState_u32_TValue & PFC_STATE_VIN_UV_FLT)
  { /* in case of the relevant errors are present */
    // Remove. DTC to be set in Protec  (SCO 179611) (void)Rte_Call_Event_GRID_INPUT_VOLTAGE_LOW_SetEventStatus(DEM_EVENT_STATUS_PREFAILED);
  }
  else
  { /* in case of the relevant errors are NOT present */
    // Remove. DTC to be set in Protec  (SCO 179611) (void)Rte_Call_Event_GRID_INPUT_VOLTAGE_LOW_SetEventStatus(DEM_EVENT_STATUS_PREPASSED);
  }
  
  if(SCI_Pfc_ErrorState_u32_TValue & PFC_STATE_VIN_OV_FLT )
  { /* in case of the relevant errors are present */
    // Remove. DTC to be set in Protec  (SCO 179608) (void)Rte_Call_Event_GRID_INPUT_VOLTAGE_HIGH_SetEventStatus(DEM_EVENT_STATUS_PREFAILED);
  }
  else
  { /* in case of the relevant errors are NOT present */
    // Remove. DTC to be set in Protec  (SCO 179608) (void)Rte_Call_Event_GRID_INPUT_VOLTAGE_HIGH_SetEventStatus(DEM_EVENT_STATUS_PREPASSED);
  }
  
  if(SCI_Pfc_ErrorState_u32_TValue & PFC_STATE_IIN_OC_FLT)
  { /* in case of the relevant errors are present */
    // Remove. DTC to be set in Protec  (SCO 179606) (void)Rte_Call_Event_GRID_INPUT_CURRENT_HIGH_SetEventStatus(DEM_EVENT_STATUS_PREFAILED);
  }
  else
  { /* in case of the relevant errors are NOT present */
    // Remove. DTC to be set in Protec  (SCO 179606) (void)Rte_Call_Event_GRID_INPUT_CURRENT_HIGH_SetEventStatus(DEM_EVENT_STATUS_PREPASSED);
  }
  SCI_Pfc_Voltage_s32Value = PFC_GET_VIN_mV();
  Rte_IWrite_pfc_MainFunction_WspPfcCdd_uGrid_Voltage(SCI_Pfc_Voltage_s32Value);
  //((SCI_Pfc_Voltage_s32Value_0 = Rte_IWriteRef_pfc_MainFunction_PP_Vin_Rms_s32_T_SCI_Pfc_Voltage_s32Value();
 
  SCI_Pfc_Current_s32Value = PFC_GET_IIN_mA();
  Rte_IWrite_pfc_MainFunction_WspPfcCdd_iGrid_Current(SCI_Pfc_Current_s32Value);
  //((SCI_Pfc_Current_s32Value_0 = Rte_IWriteRef_pfc_MainFunction_PP_Iin_Rms_s32_T_SCI_Pfc_Current_s32Value();

  SCI_Pfc_Voltage_s32Value_1 = PFC_GET_VOUT_mV();
  Rte_IWrite_pfc_MainFunction_WspPfcCdd_uBoost_Voltage(SCI_Pfc_Voltage_s32Value_1);
  //SCI_Pfc_Voltage_s32Value_2 = Rte_IWriteRef_pfc_MainFunction_PP_Vout_Rms_s32_T_SCI_Pfc_Voltage_s32Value();
  
  SCI_Pfc_Period_u32_TValue = PFC_GET_VIN_LINE_PERIOD_ns();
  Rte_IWrite_pfc_MainFunction_WspPfcCdd_tiGrid_Period(SCI_Pfc_Period_u32_TValue);
  //SCI_Pfc_Period_u32_TValue_0 = Rte_IWriteRef_pfc_MainFunction_PP_GridPeriod_u32_T_SCI_Pfc_Period_u32_TValue();

  PowerValue = PFC_GET_PIN_W();
  Rte_IWrite_pfc_MainFunction_WspPfcCdd_pwrGrid_PowerValue(PowerValue);
  //PowerValue_0 = Rte_IWriteRef_pfc_MainFunction_PP_Pin_Rms_PowerValue();

// TODO:  Cmd = Rte_IRead_pfc_MainFunction_WspPwrTrf_cmdClearFaultsPfc_Cmd();
  // TODO:  PFC_CLEAR_FAULTS(Cmd);

  milliVoltValue = Rte_IRead_pfc_MainFunction_WspPwrTrf_uReqPfc_Voltage();
  PFC_SET_VOUT_mV(milliVoltValue);
  
/*
  status = Rte_Call_Event_PFC_VOUT_SENSOR_SHORT_GND_SetEventStatus(EventStatus);

  status = Rte_Call_Event_PFC_VOUT_SENSOR_SHORT_GND_ResetEventStatus();

  status = Rte_Call_Event_PFC_VOUT_SENSOR_SHORT_GND_GetEventStatus(&EventStatusExtended);

  status = Rte_Call_Event_PFC_VOUT_SENSOR_SHORT_GND_GetEventFailed(&EventFailed);

  status = Rte_Call_Event_PFC_VOUT_SENSOR_SHORT_GND_GetEventTested(&EventTested);

  status = Rte_Call_Event_PFC_VOUT_SENSOR_SHORT_GND_GetDTCOfEvent(DTCKind, &DTCofEvent);

  status = Rte_Call_Event_PFC_VOUT_SENSOR_SHORT_GND_PrestoreFreezeFrame();

  status = Rte_Call_Event_PFC_VOUT_SENSOR_SHORT_GND_ClearPrestoredFreezeFrame();

  status = Rte_Call_Event_PFC_VOUT_SENSOR_SHORT_GND_GetFaultDetectionCounter(&EventIdFaultDetectionCounter);

  status = Rte_Call_Event_PFC_VOUT_SENSOR_SHORT_SUPP_SetEventStatus(EventStatus_0);

  status = Rte_Call_Event_PFC_VOUT_SENSOR_SHORT_SUPP_ResetEventStatus();

  status = Rte_Call_Event_PFC_VOUT_SENSOR_SHORT_SUPP_GetEventStatus(&EventStatusExtended_0);

  status = Rte_Call_Event_PFC_VOUT_SENSOR_SHORT_SUPP_GetEventFailed(&EventFailed_0);

  status = Rte_Call_Event_PFC_VOUT_SENSOR_SHORT_SUPP_GetEventTested(&EventTested_0);

  status = Rte_Call_Event_PFC_VOUT_SENSOR_SHORT_SUPP_GetDTCOfEvent(DTCKind_0, &DTCofEvent_0);

  status = Rte_Call_Event_PFC_VOUT_SENSOR_SHORT_SUPP_PrestoreFreezeFrame();

  status = Rte_Call_Event_PFC_VOUT_SENSOR_SHORT_SUPP_ClearPrestoredFreezeFrame();

  status = Rte_Call_Event_PFC_VOUT_SENSOR_SHORT_SUPP_GetFaultDetectionCounter(&EventIdFaultDetectionCounter_0);

  status = Rte_Call_Event_PFC_VOUT_SENSOR_OPEN_SetEventStatus(EventStatus_1);

  status = Rte_Call_Event_PFC_VOUT_SENSOR_OPEN_ResetEventStatus();

  status = Rte_Call_Event_PFC_VOUT_SENSOR_OPEN_GetEventStatus(&EventStatusExtended_1);

  status = Rte_Call_Event_PFC_VOUT_SENSOR_OPEN_GetEventFailed(&EventFailed_1);

  status = Rte_Call_Event_PFC_VOUT_SENSOR_OPEN_GetEventTested(&EventTested_1);

  status = Rte_Call_Event_PFC_VOUT_SENSOR_OPEN_GetDTCOfEvent(DTCKind_1, &DTCofEvent_1);

  status = Rte_Call_Event_PFC_VOUT_SENSOR_OPEN_PrestoreFreezeFrame();

  status = Rte_Call_Event_PFC_VOUT_SENSOR_OPEN_ClearPrestoredFreezeFrame();

  status = Rte_Call_Event_PFC_VOUT_SENSOR_OPEN_GetFaultDetectionCounter(&EventIdFaultDetectionCounter_1);

  status = Rte_Call_Event_UART_COMM_ERROR_SetEventStatus(EventStatus_2);

  status = Rte_Call_Event_UART_COMM_ERROR_ResetEventStatus();

  status = Rte_Call_Event_UART_COMM_ERROR_GetEventStatus(&EventStatusExtended_2);

  status = Rte_Call_Event_UART_COMM_ERROR_GetEventFailed(&EventFailed_2);

  status = Rte_Call_Event_UART_COMM_ERROR_GetEventTested(&EventTested_2);

  status = Rte_Call_Event_UART_COMM_ERROR_GetDTCOfEvent(DTCKind_2, &DTCofEvent_2);

  status = Rte_Call_Event_UART_COMM_ERROR_PrestoreFreezeFrame();

  status = Rte_Call_Event_UART_COMM_ERROR_ClearPrestoredFreezeFrame();

  status = Rte_Call_Event_UART_COMM_ERROR_GetFaultDetectionCounter(&EventIdFaultDetectionCounter_2);

  status = Rte_Call_Event_PFC_MCU_UART_ERROR_SetEventStatus(EventStatus_3);

  status = Rte_Call_Event_PFC_MCU_UART_ERROR_ResetEventStatus();

  status = Rte_Call_Event_PFC_MCU_UART_ERROR_GetEventStatus(&EventStatusExtended_3);

  status = Rte_Call_Event_PFC_MCU_UART_ERROR_GetEventFailed(&EventFailed_3);

  status = Rte_Call_Event_PFC_MCU_UART_ERROR_GetEventTested(&EventTested_3);

  status = Rte_Call_Event_PFC_MCU_UART_ERROR_GetDTCOfEvent(DTCKind_3, &DTCofEvent_3);

  status = Rte_Call_Event_PFC_MCU_UART_ERROR_PrestoreFreezeFrame();

  status = Rte_Call_Event_PFC_MCU_UART_ERROR_ClearPrestoredFreezeFrame();

  status = Rte_Call_Event_PFC_MCU_UART_ERROR_GetFaultDetectionCounter(&EventIdFaultDetectionCounter_3);

  status = Rte_Call_Event_GRID_INPUT_VOLTAGE_LOW_SetEventStatus(EventStatus_4);

  status = Rte_Call_Event_GRID_INPUT_VOLTAGE_LOW_ResetEventStatus();

  status = Rte_Call_Event_GRID_INPUT_VOLTAGE_LOW_GetEventStatus(&EventStatusExtended_4);

  status = Rte_Call_Event_GRID_INPUT_VOLTAGE_LOW_GetEventFailed(&EventFailed_4);

  status = Rte_Call_Event_GRID_INPUT_VOLTAGE_LOW_GetEventTested(&EventTested_4);

  status = Rte_Call_Event_GRID_INPUT_VOLTAGE_LOW_GetDTCOfEvent(DTCKind_4, &DTCofEvent_4);

  status = Rte_Call_Event_GRID_INPUT_VOLTAGE_LOW_PrestoreFreezeFrame();

  status = Rte_Call_Event_GRID_INPUT_VOLTAGE_LOW_ClearPrestoredFreezeFrame();

  status = Rte_Call_Event_GRID_INPUT_VOLTAGE_LOW_GetFaultDetectionCounter(&EventIdFaultDetectionCounter_4);

  status = Rte_Call_Event_GRID_INPUT_VOLTAGE_HIGH_SetEventStatus(EventStatus_5);

  status = Rte_Call_Event_GRID_INPUT_VOLTAGE_HIGH_ResetEventStatus();

  status = Rte_Call_Event_GRID_INPUT_VOLTAGE_HIGH_GetEventStatus(&EventStatusExtended_5);

  status = Rte_Call_Event_GRID_INPUT_VOLTAGE_HIGH_GetEventFailed(&EventFailed_5);

  status = Rte_Call_Event_GRID_INPUT_VOLTAGE_HIGH_GetEventTested(&EventTested_5);

  status = Rte_Call_Event_GRID_INPUT_VOLTAGE_HIGH_GetDTCOfEvent(DTCKind_5, &DTCofEvent_5);

  status = Rte_Call_Event_GRID_INPUT_VOLTAGE_HIGH_PrestoreFreezeFrame();

  status = Rte_Call_Event_GRID_INPUT_VOLTAGE_HIGH_ClearPrestoredFreezeFrame();

  status = Rte_Call_Event_GRID_INPUT_VOLTAGE_HIGH_GetFaultDetectionCounter(&EventIdFaultDetectionCounter_5);

  status = Rte_Call_Event_GRID_INPUT_CURRENT_HIGH_SetEventStatus(EventStatus_6);

  status = Rte_Call_Event_GRID_INPUT_CURRENT_HIGH_ResetEventStatus();

  status = Rte_Call_Event_GRID_INPUT_CURRENT_HIGH_GetEventStatus(&EventStatusExtended_6);

  status = Rte_Call_Event_GRID_INPUT_CURRENT_HIGH_GetEventFailed(&EventFailed_6);

  status = Rte_Call_Event_GRID_INPUT_CURRENT_HIGH_GetEventTested(&EventTested_6);

  status = Rte_Call_Event_GRID_INPUT_CURRENT_HIGH_GetDTCOfEvent(DTCKind_6, &DTCofEvent_6);

  status = Rte_Call_Event_GRID_INPUT_CURRENT_HIGH_PrestoreFreezeFrame();

  status = Rte_Call_Event_GRID_INPUT_CURRENT_HIGH_ClearPrestoredFreezeFrame();

  status = Rte_Call_Event_GRID_INPUT_CURRENT_HIGH_GetFaultDetectionCounter(&EventIdFaultDetectionCounter_6);
*/
  
  //PFC_SYNC();
  
  //status = Rte_Call_RP_PfcError_SetErrorState(ErrorId, WSErrorState);
  
}

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------

  ------------------------[per instance memory API]--------------------------

*/
/** @} doxygen end group definition */
/*==================[end of file]============================================*/

